# Generated by Django 4.2.22 on 2025-11-07 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translator", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="autotranslatedfield",
            name="field_type",
            field=models.CharField(
                choices=[("plain", "Plain"), ("html", "Html")],
                default="plain",
                max_length=10,
            ),
        ),
    ]
