environment:
    sensitive:
        EMAIL_HOST_PASSWORD: ENC[AES256_GCM,data:x7ndwjaKB1vt4yIWaYhu2NLKbGE2aapB6Myy+cePAd2X93ILipDK9Q1Z5Z9NqIAeJjk=,iv:vofLoLW8BWThDLDOhb5btm38vUFxRj/sepY91Zy4KeE=,tag:5p3PTjCqIVa+oOo0L8hP2w==,type:str]
        KEYCLOAK_CLIENT_SECRET: ENC[AES256_GCM,data:f5exrQjC66fG0hLh32120s3k3C47W4ACbRpiqMNmlKo=,iv:FX2zoRErbjgjFjQDagngp2Txlolg/UHo0SydVA+6a9o=,tag:VJ7tr76v/ztMqpD1P1h4nw==,type:str]
        KEYCLOAK_CLIENT_ID: ENC[AES256_GCM,data:slroMORtga4xIkvqKYu19LC10Bs=,iv:ykVdN5BPjyGCYePlQdFdtO3mfI2rcVrnCnx7arEM+OE=,tag:s+DQj4cJUXJoQjf3e1SGoQ==,type:str]
        SECRET_KEY: ENC[AES256_GCM,data:lhCOvB9lTCem/WSsLAlk8HHsr/S5x0/FOf2oofVd2hT3e3vP4tul9HAe2PCI5dPWDQFCxLUczT/7LmwAzRp5LA==,iv:nZP8gDspNV7L4dTaYbYHMDDMx1dvlRDuOI7+lQ+omJ8=,tag:mYiBZrFaZZ8fmeO73gAZ8w==,type:str]
        AZURE_ACCOUNT_KEY: ENC[AES256_GCM,data:GZiIxF/2DgXcXVeKkBEkwil686mNJtLDPluNbTPP3logJki3/tPfYPyZMdZE6hAKIFu5e0CuXPXdPnyWSrJrR+OfqfQJqFwEq1V3vrXRYPzJraJ7f5xNjQ==,iv:jVJmD6xJyfDIYo8eWhkvqLQrzMGmDxDZ6E/YiTvIt68=,tag:9bq0TS0WMnuL99UOFYWZOA==,type:str]
        POSTGRES_USER: ENC[AES256_GCM,data:UgFaOj36c40=,iv:J5466mKxdLxKJsdGgJZQGjLikA/BSNactrvw7SmKBsk=,tag:QcRW9Ku4LnOyp/rW0vA9TQ==,type:str]
        POSTGRES_PASSWORD: ENC[AES256_GCM,data:PHALvlxGR+SCp7p8OZE=,iv:8S7/2mhd2fUjs5jjptXi/V1vXZ+oRrsjq2pquibPvPs=,tag:f/R6ziB1PwBxgp7ajz/PTw==,type:str]
        RECAPTCHA_SECRET_KEY: ENC[AES256_GCM,data:jECLuRgDo8L9CRSVwI6ciQ6HlZGQkydqOs4gox+M4kV99L8MqSXsGw==,iv:btPyhdPMenEvVQiJjC/FiRU9QnD5ZwJg2YzprwH4gyM=,tag:egQhMk8SbCLNGiFssi5vRw==,type:str]
        ALGOLIA_KEY: ENC[AES256_GCM,data:WimgLwWdGQAtPd8aJEKDvi+y83bn5dfCXCReFrvA8+c=,iv:ir4sQ/b56lDSEuVpDotW+oi255Tt+DWEHoWAVztL3BQ=,tag:LH8RmuovBkS8sLNIGbtK6g==,type:str]
        PROJECTS_PEOPLE_TOKEN: ENC[AES256_GCM,data:pdquMe0WcYDTsf4WYMTwtBcUxP5vgZU3vZCI34AD3GQ=,iv:ClB2nd0lxsXmgqWPyzofW6ST9C7Szi8AzMlj3Indp+E=,tag:8J55+wuKSq36quMnwERyTA==,type:str]
        MIXPANEL_API_SECRET: ENC[AES256_GCM,data:1M15GRtdzTG7glsG4XQw+9nbTyVtxK4x/TQu+OD+2tg=,iv:sU+hgOim4aOUI21ivENTZuOl7h2uibDYyYLQdmRyXEU=,tag:oK0LGiabpeAbf0xb7nS5Gw==,type:str]
        CELERY_BROKER_URL: ENC[AES256_GCM,data:tsPT5wdaJKs4hWaYCMST1r/dpAy7hX+FH7Xvp6AlWEl96wJkaostGehFtlfbdVY7Od5l85oYHnBm,iv:NaOFYBPchNupZpp5spaLfr1Eij29qp4xSeilIUxY45Q=,tag:fvsMYhZBRsh+dx+4FporJQ==,type:str]
        CELERY_RESULT_BACKEND: ENC[AES256_GCM,data:tjG5QSa4Q/cQeA0fNIjbaFV4oViVW3/0JIT6GTgeGe1f+f2pIaQwvCYxoMhvKN5w30VX7jaxKOZE,iv:/e2mJLBACOVcsJ+1KLCiyFB0Awc7WdKCdiqnWvGnSw0=,tag:HsoTFpSU3WQ/IBl/giqBNg==,type:str]
        CACHE_REDIS_URL: ENC[AES256_GCM,data:Naimqc55YEPVdEx2sUGTxn33S2clU+8Ex/W/duhe1V5Jdt/G7dnPZZVnkGXkm/RUZMy4mYSZ8F38,iv:cVMbkueYpqaQm+qEWx/2zk5zmpZavOm2G2bI8uRhgZ4=,tag:Ezoq3hh65DBWdIm35b5Xeg==,type:str]
        GOOGLE_PRIVATE_KEY_ID: ENC[AES256_GCM,data:8w64DwuW2OE4S7AM55ZV2LRplsfkvfuXEVw1/VsoV/9gauIZlUpH9g==,iv:Xrwb4zZZ9KPLGs0QJr2JqJdpu4vImj+h8iWE3rTXdXg=,tag:zaCeXZPLGx/ejFITnFVHPw==,type:str]
        GOOGLE_PRIVATE_KEY: ENC[AES256_GCM,data:oofrobbU8vyq9Z11k50Fc51IIBic6+fmLFYHhQWJs5G7dV8Ry1P2W8bSbgMENMVskQ6PX9akai4l2AmdkzWOTXcs8y87wzi7JLZJfrCA9nLfPppSp0r8TZQrBtyFMFvNAcH/fxoEtViEznQ5iJXK85JM2RVxX4GVpZZucwTD2+VWQMIQhLMRdsqyDKbyfJa1pwrzozKPUjkKngqhiIGxL0ZRDoZfJokdO/3U4nnVGkF0I4tV6dMtyloax6NfFyJlCJeVe1a2MR1G9CExyHvZal0WdQrwGaoIXDufe/+sAUFjZmuzKmTwv0BSPhb772LANuQbqtplCRebZ7BWCA1zHChQRDuC7f2BB1ACwyapy4Wyju9/xxoKWbjx9rKC8WzL/b9emGfCC0Z5e5aHrMomxR655xP35LXFeEdLPG72p/rDxjkTK1EHOu84sGf5sm5eM0NC/IDhClPBJLI/+rzbcAL9uFj8bqYn0nvNNq8uuB4u8x4+73Yf9y2js5WU0ndp0+DLMNdOzM/CQBLSI0VsA3qpzZrwW2mPl+1J8svF+VUte+e8JqskTcfbfBWgDvy2PKc02HFdKi/Ob3yW2smc212a4ZW4a3koROd+Q7zLt9Uvzz+1naDkXvOlJT0kDz/9uYzkwDY/LZoPVOtfqGMzBbFZh7CCz6r/hwE61aSBxCrIDRG0vjAs3oTDd2TIysSpJbTrpu/D/jDRWWs8Xltu0UzF7JhQKikYrsqcZesPD9wyEyYt9KNZjU55PBnLWAU3b4+TVx1w+2AJn909aNaFJoIAcC9aXRxdSGVP9XKVFpG7EE9qpm0s7U7I1BnvGBu4bmwmeP0Q6wggtsrELKgkXVJ3dv7TQhjwqr8vUiCcIYwA0SVZw9TG1JM688gRsKHj+FgCmRIWoiEGMW+U/sfhqMiBPOL/6QQzhIweUptn5W+ipMp8njTE4R56+NCdBsmRfUg+w0OgLbOoPCfGYJYwzAW7mj5FuSmUwN6V9INTfcXw8eLm1/2QJwhiA7sTDIKgOBz2Huw9ah396FNSbdnihZmaRJZ26Xus15V+KwJM1HX5X/sPuXnoXiEedkIakrlH97tIfNEZ4rPoc1FjgPcpQHbqoL4lt6oor7GJWBrxYVDMr5osPQyg/s3EpKNex/ExBPI7y40v5vK/WZ2LjgCZ54K837ct85fGiAJ1yr5mka52r/8MXfeV/ahKyWo60nnBm9PNbRyE+sakj2Wsz+oM+3ejhDLChh9uLWYUeK9tWmEHgXkBryBRiBbHxErWqeNwq9k3o9V+Jk9ALBTnX0ljaLIP8Nn79Rn3rJNWIj/L1NNMA1EFAKH8LTJxddy5bZDE3Tckg+wgHXioQGDanxNbjoKEtRgVWKbxeTlsMPzh4jqQLVVDlURhDsp8JtkHGvzSLmt5k8rHULOlFslibgnvNDBnIbU1zQZ9x+t5c4SBp1Y3CdxzT1gWnzvV+pRb6o06hS2C0vFyKZMuJZceEzqZqpb0MJ0MZoh4v2fy9W2FcVNx9CqJu9C14FhmgMh1yihU8Q1kKb+HWFq9cqQaSYm+V7pBYK4N9l6ydKpg64ciNLjqTylTvKaGOQxuv9c6LHrYbr6b2zi4qLK+jO39YZHumtepC2/QUxuFo+8VifXpFqEZImIH51cLXwijByIcTXrwfzRAH83pBorHWxMrEQgcXbYnAobCOJK6Vkye4i+/8GhSkB7jGNbp3bM9WfeQoslhtJDrZsGynCXaHX4iC4sp9z80gVXSbKshdntQD8R5HFF2cDKkBNNugn5/kjd7Z3aDS7498WNAjpmMv2SbT/brSTaSZCLFMKT++oMTWAJCn7YDV1Qow0GgOCvUHzqqFp8BnUZamN9YI4KkeT7bNrDPe982NKhzea8HsxWGOV4x1Q3bewYiNosF43zxYgN2Z4vkoX2PqmwtikpQstb1apf4HH+Tj0j7TzI2R1oHX4WcVk8I7nNyx5ciHl4/CqXP5nL0NEMlbU248DuOl8GulC9Ki7fTVKJAGfSty4EEZ1/0EqMZzbuBj2SUcCK2bZX50xdsVni06ZhaWoThuDrUZDFRXcLab+P+c1CoovwUuePUZevsDe9tCQAiCGaRmpd1bCANcC221RIp7Rvw7Eg4TWsAuXVbSvV8zI0l5C7mdfdDkEGiCRwF0tGRxIyc7mmud6/awpKkqX5vMkwqY23rQybeyLD1H1cO63fOA4H73xJ87LEgxyvgaskabLibBA+EJ11C45QXuNb/QjADv2B6eNm8COfeeK4z8msW,iv:LcVTdIbX4RPmEasROeo85hw0+p7xo+/gzFmlE2v0l9c=,tag:CSB4GMBOUHG2CaN/DU3oNA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dvu205sflecfu6uewgwmgs83nkm2c2fzfxs55zfkjs2gmqjya50qmm6lck
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXdk43UU0renNFVlVyM200
            QU5JSEI5WjR0d1Nka0JUdm1GaUpQZVZvbWgwCjhVaXJCUlVncHNpZ0x6d3k3MUNW
            MTVrWXh2Ti8zUjYxdkpTNDI2SCtsRVUKLS0tIE5XRXo3dUhPTUZpbDQ5L3kraTV6
            TlNianBVdzUxM1pGNUR5MHg2WUh4amMKjTUqKH8EXTsNPSLoEqx+9NG9YZhuJy4D
            t6GI4L85uhmeI+kfUzWV100cRKcxST1VtJo20+BjWFO1XfmX/LAa/g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1x3t3s6e7hslylj6p37tt24mm5lj53ngeekrgphm5lfryg3qjpscs3l5g40
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwNmo1d3kyZEJjZzZpQUlD
            WE96ZTJBV0hNYjhsYVVXbWVTbjFmOGZ5U2xrClBKam1jZ2VWVXp2TU9mWmpnd0ln
            U1pMKzJGa1J4NFQyVWlHVVZsN2FqOWcKLS0tIHR3SGx1WUlranhhWThQajlnMzF6
            SFN6ek5GNUpJRFNqVi9SVEkvUDgxOUkKdZz7dcGItSvEXN3TgFrRDASO6/WXzUwf
            ZpggCsnmj6VsNX+eLnh36LelqhBtgKPrUbCeARa/7R5JoJlCVhdHgQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yc3dc5322xx03sx2xy5n8w95fzfrc46qcgj6c8hcfes2288cgdvsq0wapf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArenNaODJobnNxUTFPcno0
            T3F6emIxTytOSW1DSGxadXh5aWlVNGRraUJRCnM4WXlZRWoybUQ4SURXalZ3RExl
            dWxqa2YwdExHYnN2c25GVk84ZC9nUncKLS0tIHJKUXB1SWRxay8vZUFrYmJLc0dk
            UXN4MDR5QUthMkRnNjFSSjFiakp3RW8KyVi4unucvq2t24UYCkI25jyrXOaj7tag
            DhzX6Kgmlx2zGaYQaVgtHpXXpvYhGJcFnZ0wSCOyurHmSjPmSvi3sQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age195mrdujpg239kfgzq45je9fr7xsdnplt7etu35l0u8y6g67h3a3qxtzam2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiS3ZTQkl0aVNZQ2RhdFNa
            WGJVK0l3OEo3cXdhdDZhdG9YVzlpaVZLNWtFCnR2bE9XZVBEd0JLcWo1VjZkcnU0
            YmY4eGlJVFRXaVJYL215Y0VLeVNuVmsKLS0tIDA1L05pdG9NcFkvQWptQlFFQ1pI
            UWRmZEVpK3lNdjBnelcrV2R2L3MwTEEKPxYHVl+Pt9+sYNO6pWvvHlWRHbRU8tT1
            k7Dpie9FyQEbAZ9yuJY37VX35N+lL4rlacvlJTzwiuUOPdHiV+UZEQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age14qavd6070runmtefwsh60ps3kxnu36fhsp76wvct4w4k4g7wqeksmk3r9z
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxT25vRVZISy9MT3V1TnFr
            K2krOW9aQVo0a0tWcGR0aVV6MHVTcWZjL1hjCk53K0swSUJKaVlnb3pGeWt5MWlv
            N2dCS1o5Ukh6SVgxSno0OVhwQ3dlQlkKLS0tIE1qNmduYWJWeVE1NUVtc0MrUVNF
            dFdOVXUwbHRxc1pvdUJycnFtN2c0cWcKX7AanfpqdfXNF8ZrQGBKtDwR3M5RBCPx
            TOyq/aw4p2Bsx63bUMboDrcUISbxER2fGkBb1K9RTHqlOJe/u1LlZg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1ca09pc0uh58kee7tsajs9yvjcfk3nhzu2k7c83n5h2j49r4wzu5sjy8vm3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSWTB0eWpZbHpKN3ZjZDRG
            clRpS2hYeGRSbFRjMG0xRWFkeC8vL3VMejBRCnUyVWt0dFNrc2ZNbVpkNVlWSG9u
            SE4wOWxqU2ZUN0JjZVV2TitLS2NiMUUKLS0tIHpmb3N1OERTYmhEVFB0SHVWQmow
            MVE1SkZJbWFvenArdCtMcmFBWmx0aXcKEbn991RoA83KjhkPE88A5HowWB5B9nzf
            XdWKtPhWoleDASx7AB+vLgt0l0MY9BvnpVbdIt1s4/RvUaO18MhrGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-14T13:37:36Z"
    mac: ENC[AES256_GCM,data:dFqNW7Y/BdncX9RLqonwgyTgB4QS1ayq7dcbb/EJ81oV4nNNJHl0jmSkQ5Sd/6xopyzzIW1BITtizQLujMg6Fyw8CeNBzid52Umix1Ck0G19BqLcVZDJoq+fECS3kiy0tB8vppl5A2aH5P8bYeHuu7xwyAxRm7B2gh8KzPt+1JA=,iv:Af81vxdqkblLAHofKKiozlOHQz2A5own85Jb4XLD3L8=,tag:k77PQGDsz/cVcco6hxvo0Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
