# Generated by Django 4.2.22 on 2025-09-29 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("google_id", models.CharField(blank=True, default="", max_length=50)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                (
                    "organizational_unit",
                    models.CharField(default="/CRI/Admin Staff", max_length=50),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GoogleGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("google_id", models.CharField(blank=True, default="", max_length=50)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                (
                    "people_group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_group",
                        to="accounts.peoplegroup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GoogleSyncErrors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "on_task",
                    models.CharField(
                        choices=[
                            ("create_user", "Create user"),
                            ("update_user", "Update user"),
                            ("suspend_user", "Suspend user"),
                            ("user_alias", "Create user alias"),
                            ("sync_groups", "Sync user groups"),
                            ("create_group", "Create group"),
                            ("update_group", "Update group"),
                            ("group_alias", "Create group alias"),
                            ("sync_members", "Sync group members"),
                        ],
                        max_length=50,
                    ),
                ),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("retries_count", models.PositiveIntegerField(default=0)),
                ("solved", models.BooleanField(default=False)),
                (
                    "google_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_sync_errors",
                        to="google.googleaccount",
                    ),
                ),
                (
                    "google_group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_sync_errors",
                        to="google.googlegroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "google sync error",
                "verbose_name_plural": "google sync errors",
                "ordering": ("-created_at",),
            },
        ),
    ]
