# Generated by Django 4.0.10 on 2023-05-15 13:57

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0030_peoplegroup_publication_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LPIGoogleAccount',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.projectuser',),
        ),
        migrations.CreateModel(
            name='LPIGoogleGroup',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.peoplegroup',),
        ),
    ]
