# Generated by Django 4.2.3 on 2023-10-30 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0053_projectuser_show_welcome"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("google", "0002_googlesyncerrors"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("google_id", models.CharField(blank=True, default="", max_length=50)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                (
                    "organizational_unit",
                    models.CharField(default="/CRI/Admin Staff", max_length=50),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_account",
                        to=settings.AUTH_USER_MODEL,
                        to_field="keycloak_id",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GoogleGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("google_id", models.CharField(blank=True, default="", max_length=50)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                (
                    "people_group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_group",
                        to="accounts.peoplegroup",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="LPIGoogleAccount",
        ),
        migrations.DeleteModel(
            name="LPIGoogleGroup",
        ),
        migrations.RemoveField(
            model_name="googlesyncerrors",
            name="people_group",
        ),
        migrations.RemoveField(
            model_name="googlesyncerrors",
            name="task_kwargs",
        ),
        migrations.RemoveField(
            model_name="googlesyncerrors",
            name="user",
        ),
        migrations.AddField(
            model_name="googlesyncerrors",
            name="retries_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="googlesyncerrors",
            name="solved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="googlesyncerrors",
            name="error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="googlesyncerrors",
            name="on_task",
            field=models.CharField(
                choices=[
                    ("create_user", "Create user"),
                    ("update_user", "Update user"),
                    ("suspend_user", "Suspend user"),
                    ("user_alias", "Create user alias"),
                    ("keycloak_username", "Update keycloak username"),
                    ("sync_groups", "Sync user groups"),
                    ("create_group", "Create group"),
                    ("update_group", "Update group"),
                    ("group_alias", "Create group alias"),
                    ("sync_members", "Sync group members"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="googlesyncerrors",
            name="google_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="google_sync_errors",
                to="google.googleaccount",
            ),
        ),
        migrations.AddField(
            model_name="googlesyncerrors",
            name="google_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="google_sync_errors",
                to="google.googlegroup",
            ),
        ),
    ]
