# Generated by Django 4.2.3 on 2023-10-06 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("google", "0002_googlesyncerrors"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LPIGoogleAccount",
        ),
        migrations.DeleteModel(
            name="LPIGoogleGroup",
        ),
    ]
