# Generated by Django 4.2.3 on 2023-10-09 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0052_peoplegroup_slug_projectuser_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("google", "0003_delete_lpigoogleaccount_delete_lpigooglegroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="googlesyncerrors",
            name="retried_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="googlesyncerrors",
            name="retries_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="googlesyncerrors",
            name="on_task",
            field=models.CharField(
                choices=[
                    ("create_user", "Create user"),
                    ("update_user", "Update user"),
                    ("suspend_user", "Suspend user"),
                    ("user_alias", "Create user alias"),
                    ("keycloak_username", "Update keycloak username"),
                    ("sync_groups", "Sync user groups"),
                    ("create_group", "Create group"),
                    ("update_group", "Update group"),
                    ("group_alias", "Create group alias"),
                    ("sync_members", "Sync group members"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="GoogleGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("google_id", models.CharField(max_length=50, null=True, unique=True)),
                ("email", models.EmailField(max_length=254, null=True, unique=True)),
                (
                    "people_group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_group",
                        to="accounts.peoplegroup",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GoogleAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("google_id", models.CharField(max_length=50, unique=True)),
                ("email", models.EmailField(max_length=254, null=True, unique=True)),
                ("organizational_unit", models.CharField(max_length=50, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
