# Generated by Django 4.2.7 on 2023-12-06 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def migrate_google_accounts(apps, schema_editor):
    GoogleAccount = apps.get_model("google", "GoogleAccount")
    for google_account in GoogleAccount.objects.all():
        google_account._user = google_account.user
        google_account.save()

def migrate_google_accounts_reverse(apps, schema_editor):
    GoogleAccount = apps.get_model("google", "GoogleAccount")
    for google_account in GoogleAccount.objects.all():
        google_account.user = google_account._user
        google_account.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("google", "0003_googleaccount_googlegroup_delete_lpigoogleaccount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="googleaccount",
            name="_user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_google_account",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(migrate_google_accounts, migrate_google_accounts_reverse),
        migrations.RemoveField(
            model_name="googleaccount",
            name="user",
        ),
        migrations.RenameField(
            model_name="googleaccount",
            old_name="_user",
            new_name="user",
        ),
        migrations.AlterField(
            model_name="googleaccount",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="google_account",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
