# Generated by Django 4.2.3 on 2023-10-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("google", "0003_googleaccount_googlegroup_delete_lpigoogleaccount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="googleaccount",
            name="organizational_unit",
            field=models.CharField(default="/CRI/Admin Staff", max_length=50),
        ),
    ]
