# Generated by Django 4.2.7 on 2023-12-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("google", "0004_googleaccount__user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="googlesyncerrors",
            name="on_task",
            field=models.CharField(
                choices=[
                    ("create_user", "Create user"),
                    ("update_user", "Update user"),
                    ("suspend_user", "Suspend user"),
                    ("user_alias", "Create user alias"),
                    ("sync_groups", "Sync user groups"),
                    ("create_group", "Create group"),
                    ("update_group", "Update group"),
                    ("group_alias", "Create group alias"),
                    ("sync_members", "Sync group members"),
                ],
                max_length=50,
            ),
        ),
    ]
