# Generated by Django 4.2.3 on 2023-10-09 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0052_peoplegroup_slug_projectuser_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("google", "0004_googlesyncerrors_retried_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="googleaccount",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="google_account",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="googlegroup",
            name="people_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="google_group",
                to="accounts.peoplegroup",
            ),
        ),
    ]
