# Generated by Django 4.2.22 on 2025-09-29 16:05

import apps.commons.mixins
import apps.projects.models
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("files", "0002_initial"),
        ("organizations", "0002_initial"),
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalProject",
            fields=[
                (
                    "id",
                    models.CharField(
                        auto_created=True,
                        db_index=True,
                        default=apps.projects.models.uuid_generator,
                        max_length=8,
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("slug", models.SlugField()),
                (
                    "outdated_slugs",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.SlugField(), default=list, size=None
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("purpose", models.TextField(blank=True, verbose_name="main goal")),
                ("is_locked", models.BooleanField(default=False)),
                ("is_shareable", models.BooleanField(default=False)),
                (
                    "publication_status",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("private", "Private"),
                            ("org", "Org"),
                        ],
                        default="private",
                        max_length=10,
                        verbose_name="visibility",
                    ),
                ),
                (
                    "life_status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("canceled", "Canceled"),
                            ("toreview", "To Review"),
                        ],
                        default="running",
                        max_length=10,
                        verbose_name="life status",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("fr", "Français"),
                            ("de", "Deutsch"),
                            ("nl", "Dutch"),
                            ("et", "Estonian"),
                            ("ca", "Catalan"),
                            ("es", "Español"),
                        ],
                        default="en",
                        max_length=2,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("deleted_at", models.DateTimeField(null=True)),
                (
                    "sdgs",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveSmallIntegerField(
                            choices=[
                                (1, "No poverty"),
                                (2, "Zero hunger"),
                                (3, "Good health and well-being"),
                                (4, "Quality education"),
                                (5, "Gender equality"),
                                (6, "Clean water and sanitation"),
                                (7, "Affordable and clean energy"),
                                (8, "Decent work and economic growth"),
                                (9, "Industry, innovation and infrastructure"),
                                (10, "Reduces inequalities"),
                                (11, "Sustainable cities and communities"),
                                (12, "Responsible consumption & production"),
                                (13, "Climate action"),
                                (14, "Life below water"),
                                (15, "Life on land"),
                                (16, "Peace, justice and strong institutions"),
                                (17, "Partnerships for the goals"),
                            ]
                        ),
                        blank=True,
                        default=list,
                        size=17,
                        verbose_name="sustainable development goals",
                    ),
                ),
                (
                    "duplicated_from",
                    models.CharField(blank=True, default=None, max_length=8, null=True),
                ),
                ("permissions_up_to_date", models.BooleanField(default=False)),
                (
                    "title_detected_language",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "description_detected_language",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "purpose_detected_language",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "header_image",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="files.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical project",
                "verbose_name_plural": "historical projects",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.CharField(
                        auto_created=True,
                        default=apps.projects.models.uuid_generator,
                        max_length=8,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("slug", models.SlugField(unique=True)),
                (
                    "outdated_slugs",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.SlugField(), default=list, size=None
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("purpose", models.TextField(blank=True, verbose_name="main goal")),
                ("is_locked", models.BooleanField(default=False)),
                ("is_shareable", models.BooleanField(default=False)),
                (
                    "publication_status",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("private", "Private"),
                            ("org", "Org"),
                        ],
                        default="private",
                        max_length=10,
                        verbose_name="visibility",
                    ),
                ),
                (
                    "life_status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("canceled", "Canceled"),
                            ("toreview", "To Review"),
                        ],
                        default="running",
                        max_length=10,
                        verbose_name="life status",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("fr", "Français"),
                            ("de", "Deutsch"),
                            ("nl", "Dutch"),
                            ("et", "Estonian"),
                            ("ca", "Catalan"),
                            ("es", "Español"),
                        ],
                        default="en",
                        max_length=2,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(null=True)),
                (
                    "sdgs",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveSmallIntegerField(
                            choices=[
                                (1, "No poverty"),
                                (2, "Zero hunger"),
                                (3, "Good health and well-being"),
                                (4, "Quality education"),
                                (5, "Gender equality"),
                                (6, "Clean water and sanitation"),
                                (7, "Affordable and clean energy"),
                                (8, "Decent work and economic growth"),
                                (9, "Industry, innovation and infrastructure"),
                                (10, "Reduces inequalities"),
                                (11, "Sustainable cities and communities"),
                                (12, "Responsible consumption & production"),
                                (13, "Climate action"),
                                (14, "Life below water"),
                                (15, "Life on land"),
                                (16, "Peace, justice and strong institutions"),
                                (17, "Partnerships for the goals"),
                            ]
                        ),
                        blank=True,
                        default=list,
                        size=17,
                        verbose_name="sustainable development goals",
                    ),
                ),
                (
                    "duplicated_from",
                    models.CharField(blank=True, default=None, max_length=8, null=True),
                ),
                ("permissions_up_to_date", models.BooleanField(default=False)),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="title"
                    ),
                ),
                (
                    "title_fr",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="title"
                    ),
                ),
                (
                    "title_de",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="title"
                    ),
                ),
                (
                    "title_nl",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="title"
                    ),
                ),
                (
                    "title_et",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="title"
                    ),
                ),
                (
                    "title_ca",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="title"
                    ),
                ),
                (
                    "title_detected_language",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "title_es",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="title"
                    ),
                ),
                ("description_en", models.TextField(blank=True, default="", null=True)),
                ("description_fr", models.TextField(blank=True, default="", null=True)),
                ("description_de", models.TextField(blank=True, default="", null=True)),
                ("description_nl", models.TextField(blank=True, default="", null=True)),
                ("description_et", models.TextField(blank=True, default="", null=True)),
                ("description_ca", models.TextField(blank=True, default="", null=True)),
                (
                    "description_detected_language",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("description_es", models.TextField(blank=True, default="", null=True)),
                (
                    "purpose_en",
                    models.TextField(blank=True, null=True, verbose_name="main goal"),
                ),
                (
                    "purpose_fr",
                    models.TextField(blank=True, null=True, verbose_name="main goal"),
                ),
                (
                    "purpose_de",
                    models.TextField(blank=True, null=True, verbose_name="main goal"),
                ),
                (
                    "purpose_nl",
                    models.TextField(blank=True, null=True, verbose_name="main goal"),
                ),
                (
                    "purpose_et",
                    models.TextField(blank=True, null=True, verbose_name="main goal"),
                ),
                (
                    "purpose_ca",
                    models.TextField(blank=True, null=True, verbose_name="main goal"),
                ),
                (
                    "purpose_detected_language",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "purpose_es",
                    models.TextField(blank=True, null=True, verbose_name="main goal"),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="projects",
                        to="organizations.projectcategory",
                        verbose_name="categories",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(related_name="projects", to="auth.group"),
                ),
                (
                    "header_image",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="project_header",
                        to="files.image",
                    ),
                ),
                (
                    "images",
                    models.ManyToManyField(related_name="projects", to="files.image"),
                ),
                (
                    "main_category",
                    simple_history.models.HistoricForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="organizations.projectcategory",
                        verbose_name="main category",
                    ),
                ),
                (
                    "organizations",
                    models.ManyToManyField(
                        related_name="projects", to="organizations.organization"
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        db_table="projects_project_skills_tags",
                        related_name="projects",
                        to="skills.tag",
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("view_projectmessage", "Can view project messages"),
                    ("add_projectmessage", "Can add project messages"),
                    ("lock_project", "Can lock and unlock a project"),
                    ("duplicate_project", "Can duplicate a project"),
                    ("change_locked_project", "Can update a locked project"),
                    ("add_review", "Can add project's reviews"),
                    ("change_review", "Can change project's reviews"),
                    ("delete_review", "Can delete project's reviews"),
                    ("add_comment", "Can add project's comments"),
                    ("change_comment", "Can change project's comments"),
                    ("delete_comment", "Can delete project's comments"),
                    ("add_follow", "Can add project's follows"),
                    ("change_follow", "Can change project's follows"),
                    ("delete_follow", "Can delete project's follows"),
                ),
                "write_only_subscopes": (
                    ("review", "project's reviews"),
                    ("comment", "project's comments"),
                    ("follow", "project's follows"),
                ),
            },
            bases=(
                apps.commons.mixins.HasMultipleIDs,
                apps.commons.mixins.HasPermissionsSetup,
                apps.commons.mixins.ProjectRelated,
                apps.commons.mixins.DuplicableModel,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="ProjectTab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("text", "Text"), ("blog", "Blog")],
                        default="text",
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=255)),
                ("title_en", models.CharField(blank=True, max_length=255, null=True)),
                ("title_fr", models.CharField(blank=True, max_length=255, null=True)),
                ("title_de", models.CharField(blank=True, max_length=255, null=True)),
                ("title_nl", models.CharField(blank=True, max_length=255, null=True)),
                ("title_et", models.CharField(blank=True, max_length=255, null=True)),
                ("title_ca", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "title_detected_language",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("title_es", models.CharField(blank=True, max_length=255, null=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                ("description_fr", models.TextField(blank=True, null=True)),
                ("description_de", models.TextField(blank=True, null=True)),
                ("description_nl", models.TextField(blank=True, null=True)),
                ("description_et", models.TextField(blank=True, null=True)),
                ("description_ca", models.TextField(blank=True, null=True)),
                (
                    "description_detected_language",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("description_es", models.TextField(blank=True, null=True)),
                (
                    "images",
                    models.ManyToManyField(
                        related_name="project_tabs", to="files.image"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_tabs",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(apps.commons.mixins.ProjectRelated, models.Model),
        ),
        migrations.CreateModel(
            name="ProjectTabItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title_en", models.CharField(blank=True, max_length=255, null=True)),
                ("title_fr", models.CharField(blank=True, max_length=255, null=True)),
                ("title_de", models.CharField(blank=True, max_length=255, null=True)),
                ("title_nl", models.CharField(blank=True, max_length=255, null=True)),
                ("title_et", models.CharField(blank=True, max_length=255, null=True)),
                ("title_ca", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "title_detected_language",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("title_es", models.CharField(blank=True, max_length=255, null=True)),
                ("content_en", models.TextField(blank=True, null=True)),
                ("content_fr", models.TextField(blank=True, null=True)),
                ("content_de", models.TextField(blank=True, null=True)),
                ("content_nl", models.TextField(blank=True, null=True)),
                ("content_et", models.TextField(blank=True, null=True)),
                ("content_ca", models.TextField(blank=True, null=True)),
                (
                    "content_detected_language",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("content_es", models.TextField(blank=True, null=True)),
                (
                    "images",
                    models.ManyToManyField(
                        related_name="project_tab_items", to="files.image"
                    ),
                ),
                (
                    "tab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="projects.projecttab",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
            bases=(apps.commons.mixins.ProjectRelated, models.Model),
        ),
        migrations.CreateModel(
            name="ProjectScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completeness", models.FloatField(default=0)),
                ("popularity", models.FloatField(default=0)),
                ("activity", models.FloatField(default=0)),
                ("score", models.FloatField(default=0)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score",
                        to="projects.project",
                    ),
                ),
            ],
            bases=(models.Model, apps.commons.mixins.ProjectRelated),
        ),
        migrations.CreateModel(
            name="ProjectMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(default=None, null=True)),
                ("content_en", models.TextField(blank=True, null=True)),
                ("content_fr", models.TextField(blank=True, null=True)),
                ("content_de", models.TextField(blank=True, null=True)),
                ("content_nl", models.TextField(blank=True, null=True)),
                ("content_et", models.TextField(blank=True, null=True)),
                ("content_ca", models.TextField(blank=True, null=True)),
                (
                    "content_detected_language",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("content_es", models.TextField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "images",
                    models.ManyToManyField(
                        related_name="project_messages", to="files.image"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="projects.project",
                    ),
                ),
                (
                    "reply_on",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="projects.projectmessage",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
            bases=(
                apps.commons.mixins.ProjectRelated,
                apps.commons.mixins.HasOwner,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                (
                    "type",
                    models.CharField(
                        choices=[("team", "Team"), ("impact", "Impact")],
                        default="team",
                        max_length=6,
                    ),
                ),
                ("title_en", models.CharField(blank=True, max_length=255, null=True)),
                ("title_fr", models.CharField(blank=True, max_length=255, null=True)),
                ("title_de", models.CharField(blank=True, max_length=255, null=True)),
                ("title_nl", models.CharField(blank=True, max_length=255, null=True)),
                ("title_et", models.CharField(blank=True, max_length=255, null=True)),
                ("title_ca", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "title_detected_language",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("title_es", models.CharField(blank=True, max_length=255, null=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                ("description_fr", models.TextField(blank=True, null=True)),
                ("description_de", models.TextField(blank=True, null=True)),
                ("description_nl", models.TextField(blank=True, null=True)),
                ("description_et", models.TextField(blank=True, null=True)),
                ("description_ca", models.TextField(blank=True, null=True)),
                (
                    "description_detected_language",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("description_es", models.TextField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                apps.commons.mixins.ProjectRelated,
                apps.commons.mixins.DuplicableModel,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="HistoricalProject_tags",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("m2m_history_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "history",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="projects.historicalproject",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="projects.project",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="skills.tag",
                    ),
                ),
            ],
            options={
                "verbose_name": "HistoricalProject_tags",
            },
        ),
        migrations.CreateModel(
            name="HistoricalProject_categories",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("m2m_history_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "history",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="projects.historicalproject",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="projects.project",
                    ),
                ),
                (
                    "projectcategory",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="organizations.projectcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "HistoricalProject_categories",
            },
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="history_relation",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="archive",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="main_category",
            field=simple_history.models.HistoricForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="organizations.projectcategory",
                verbose_name="main category",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalLinkedProject",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="projects.project",
                    ),
                ),
                (
                    "target",
                    simple_history.models.HistoricForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical linked project",
                "verbose_name_plural": "historical linked projects",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("deadline_at", models.DateField(null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("na", "None"),
                            ("ongoing", "Ongoing"),
                            ("complete", "Complete"),
                            ("cancel", "Cancel"),
                        ],
                        default="na",
                        max_length=24,
                    ),
                ),
                ("title_en", models.CharField(blank=True, max_length=255, null=True)),
                ("title_fr", models.CharField(blank=True, max_length=255, null=True)),
                ("title_de", models.CharField(blank=True, max_length=255, null=True)),
                ("title_nl", models.CharField(blank=True, max_length=255, null=True)),
                ("title_et", models.CharField(blank=True, max_length=255, null=True)),
                ("title_ca", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "title_detected_language",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("title_es", models.CharField(blank=True, max_length=255, null=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                ("description_fr", models.TextField(blank=True, null=True)),
                ("description_de", models.TextField(blank=True, null=True)),
                ("description_nl", models.TextField(blank=True, null=True)),
                ("description_et", models.TextField(blank=True, null=True)),
                ("description_ca", models.TextField(blank=True, null=True)),
                (
                    "description_detected_language",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("description_es", models.TextField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                apps.commons.mixins.ProjectRelated,
                apps.commons.mixins.DuplicableModel,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="BlogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title_en", models.CharField(blank=True, max_length=255, null=True)),
                ("title_fr", models.CharField(blank=True, max_length=255, null=True)),
                ("title_de", models.CharField(blank=True, max_length=255, null=True)),
                ("title_nl", models.CharField(blank=True, max_length=255, null=True)),
                ("title_et", models.CharField(blank=True, max_length=255, null=True)),
                ("title_ca", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "title_detected_language",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("title_es", models.CharField(blank=True, max_length=255, null=True)),
                ("content_en", models.TextField(blank=True, null=True)),
                ("content_fr", models.TextField(blank=True, null=True)),
                ("content_de", models.TextField(blank=True, null=True)),
                ("content_nl", models.TextField(blank=True, null=True)),
                ("content_et", models.TextField(blank=True, null=True)),
                ("content_ca", models.TextField(blank=True, null=True)),
                (
                    "content_detected_language",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("content_es", models.TextField(blank=True, null=True)),
                (
                    "images",
                    models.ManyToManyField(
                        related_name="blog_entries", to="files.image"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_entries",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Blog entries",
                "ordering": ["-created_at"],
            },
            bases=(
                apps.commons.mixins.ProjectRelated,
                apps.commons.mixins.DuplicableModel,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="LinkedProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linked_to",
                        to="projects.project",
                    ),
                ),
                (
                    "target",
                    simple_history.models.HistoricForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linked_projects",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "target")},
            },
            bases=(models.Model, apps.commons.mixins.ProjectRelated),
        ),
    ]
