# Generated by Django 3.2.12 on 2022-04-15 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL('ALTER TEXT SEARCH CONFIGURATION english_conf '
                          'ALTER MAPPING FOR numword, numhword, hword_numpart '
                          'WITH unaccent, english_stem;'),
    ]
