# Generated by Django 4.2.7 on 2024-02-12 13:52

from django.db import migrations, models
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproject",
            name="embedding",
            field=pgvector.django.VectorField(dimensions=1024, null=True),
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="embedding_summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="project",
            name="embedding",
            field=pgvector.django.VectorField(dimensions=1024, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="embedding_summary",
            field=models.TextField(blank=True),
        ),
    ]
