# Generated by Django 4.2.11 on 2024-04-16 10:19

import apps.commons.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completeness", models.FloatField(default=0)),
                ("popularity", models.FloatField(default=0)),
                ("activity", models.FloatField(default=0)),
                ("score", models.FloatField(default=0)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score",
                        to="projects.project",
                    ),
                ),
            ],
            bases=(
                models.Model,
                apps.commons.mixins.ProjectRelated,
                apps.commons.mixins.OrganizationRelated,
            ),
        ),
    ]
