# Generated by Django 5.2.10 on 2026-01-21 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="type",
            field=models.CharField(
                choices=[
                    ("team", "Team"),
                    ("impact", "Impact"),
                    ("address", "Address"),
                ],
                default="team",
                max_length=10,
            ),
        ),
    ]
