# Generated by Django 5.2.12 on 2026-03-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_alter_location_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="type",
            field=models.CharField(
                choices=[
                    ("team", "Team"),
                    ("impact", "Impact"),
                    ("address", "Address"),
                    ("news", "News"),
                    ("event", "Event"),
                ],
                default="team",
                max_length=10,
            ),
        ),
    ]
