# Generated by Django 3.2.13 on 2022-05-03 21:34

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_add_unaccent_to_more_parsers'),
    ]

    operations = [
        TrigramExtension(),
    ]
