# Generated by Django 4.2.14 on 2024-09-05 12:49

import apps.commons.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("files", "0002_initial"),
        ("projects", "0002_projectscore"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(default=None, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "images",
                    models.ManyToManyField(
                        related_name="project_messages", to="files.image"
                    ),
                ),
                (
                    "project",
                    simple_history.models.HistoricForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="projects.project",
                    ),
                ),
                (
                    "reply_on",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="projects.projectmessage",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
            bases=(
                models.Model,
                apps.commons.models.ProjectRelated,
                apps.commons.models.OrganizationRelated,
            ),
        ),
    ]
