# Generated by Django 6.0.4 on 2026-06-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_alter_location_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="projecttab",
            name="show_preview",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="projecttab",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="projecttab",
            name="icon",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="projecttabitem",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
