# Generated by Django 4.2.15 on 2024-09-19 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_projectmessage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "permissions": (
                    ("view_projectmessage", "Can view project messages"),
                    ("add_projectmessage", "Can add project messages"),
                    ("lock_project", "Can lock and unlock a project"),
                    ("duplicate_project", "Can duplicate a project"),
                    ("change_locked_project", "Can update a locked project"),
                    ("add_review", "Can add project's reviews"),
                    ("change_review", "Can change project's reviews"),
                    ("delete_review", "Can delete project's reviews"),
                    ("add_comment", "Can add project's comments"),
                    ("change_comment", "Can change project's comments"),
                    ("delete_comment", "Can delete project's comments"),
                    ("add_follow", "Can add project's follows"),
                    ("change_follow", "Can change project's follows"),
                    ("delete_follow", "Can delete project's follows"),
                )
            },
        ),
    ]
