# Generated by Django 3.2.13 on 2022-05-06 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_enable_trigram_extension'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalproject_tags',
            old_name='tag',
            new_name='wikipediatag',
        ),
    ]
