# Generated by Django 6.0.4 on 2026-06-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects",
            "0004_remove_projecttab_type_alter_projecttab_description_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="projecttab",
            name="type",
            field=models.CharField(
                choices=[("text", "Text"), ("blog", "Blog")],
                default="text",
                max_length=32,
            ),
        ),
    ]
