# Generated by Django 6.0.5 on 2026-08-21 09:44

import django.contrib.postgres.fields
from django.db import migrations, models
from django.utils.text import slugify

def generate_tab_slug(apps, schema_editor):
    ProjectTab = apps.get_model("projects", "ProjectTab")
    conn_alias = schema_editor.connection.alias

    for tab in ProjectTab.objects.using(conn_alias).select_related("project").filter(slug__isnull=True):
        slug = f"{slugify(tab.title)}-{tab.project.id}"
        tab.slug = slug
        index = 0
        while ProjectTab.objects.using(conn_alias).slug_or_id(tab.slug).exists():
            index += 1
            tab.slug = f"{slug}-{index}"
        tab.save(update_fields=["slug"], using=conn_alias)

class Migration(migrations.Migration):

    dependencies = [
        ("files", "0005_alter_image_options_peoplegroupimage"),
        (
            "projects",
            "0004_projecttab_show_preview_alter_projecttab_description_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="projecttab",
            name="outdated_slugs",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.SlugField(), default=list
            ),
        ),
        migrations.AddField(
            model_name="projecttab",
            name="slug",
            # don't create index in db to avoid error in migrations
            field=models.SlugField(default=None, null=True, db_index=False, unique=False),
            preserve_default=False,
        ),
        migrations.RunPython(generate_tab_slug, atomic=True),
        migrations.AlterField(
            model_name="projecttab",
            name="slug",
            field=models.SlugField(unique=True, null=False, db_index=True),
        ),
        migrations.AddField(
            model_name="projecttab",
            name="uuid",
            field=models.UUIDField(default=None, null=True),
        ),
        migrations.AddConstraint(
            model_name="projecttab",
            constraint=models.UniqueConstraint(
                condition=models.Q(("uuid__isnull", False)),
                fields=("uuid", "project"),
                name="unique_project_tab",
            ),
        ),
    ]
