# Generated by Django 6.0.5 on 2026-08-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0005_alter_image_options_peoplegroupimage"),
        (
            "projects",
            "0004_projecttab_show_preview_alter_projecttab_description_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="projecttab",
            name="uuid",
            field=models.UUIDField(default=None, null=True),
        ),
        migrations.AddConstraint(
            model_name="projecttab",
            constraint=models.UniqueConstraint(
                condition=models.Q(("uuid__isnull", False)),
                fields=("uuid", "project"),
                name="unique_project_tab",
            ),
        ),
    ]
