# Generated by Django 6.0.5 on 2026-08-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "projects",
            "0004_projecttab_show_preview_alter_projecttab_description_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="projecttab",
            name="uuid",
            field=models.UUIDField(default=None, null=True),
        ),
    ]
