# Generated by Django 6.0.5 on 2026-08-21 09:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0005_alter_image_options_peoplegroupimage"),
        (
            "projects",
            "0004_projecttab_show_preview_alter_projecttab_description_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="projecttab",
            name="outdated_slugs",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.SlugField(), default=list
            ),
        ),
        migrations.AddField(
            model_name="projecttab",
            name="slug",
            field=models.SlugField(default=None, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projecttab",
            name="uuid",
            field=models.UUIDField(default=None, null=True),
        ),
        migrations.AddConstraint(
            model_name="projecttab",
            constraint=models.UniqueConstraint(
                condition=models.Q(("uuid__isnull", False)),
                fields=("uuid", "project"),
                name="unique_project_tab",
            ),
        ),
    ]
