# Generated by Django 4.2.15 on 2024-10-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0001_initial"),
        ("projects", "0005_remove_historicalproject_categories_history_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                db_table="projects_project_skills_tags",
                related_name="projects",
                to="skills.tag",
            ),
        ),
    ]
