# Generated by Django 6.0.4 on 2026-06-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_projecttab_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="projecttab",
            name="show_preview",
            field=models.BooleanField(default=True),
        ),
    ]
