# Generated by Django 6.0.8 on 2026-10-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_alter_image_options_peoplegroupimage'),
        ('projects', '0005_projecttab_outdated_slugs_projecttab_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projecttab',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='projecttab',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projecttab',
            name='show_tab',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='projecttab',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='projecttab',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('blog', 'Blog'), ('members', 'Members'), ('groups', 'Groups'), ('linked_projects', 'Linked Projects'), ('locations', 'Locations'), ('comments', 'Comments'), ('goals', 'Goals'), ('resources', 'Resources'), ('blogs', 'Blogs'), ('announcements', 'Announcements'), ('messages', 'Messages'), ('reviews', 'Reviews'), ('description', 'Description')], default='text', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='projecttab',
            constraint=models.UniqueConstraint(condition=models.Q(('type__in', ('blog', 'text')), _negated=True), fields=('type', 'project'), name='unique_project_tab_type_bridge'),
        ),
        migrations.AddConstraint(
            model_name='projecttab',
            constraint=models.UniqueConstraint(fields=('slug', 'project'), name='unique_project_tab_slug'),
        ),
    ]
