# Generated by Django 3.2.13 on 2022-05-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0003_tag'),
        ('projects', '0005_auto_20220506_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='organization_tags',
            field=models.ManyToManyField(to='misc.WikipediaTag'),
        ),
    ]
