# Generated by Django 6.0.5 on 2026-08-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0005_alter_image_options_peoplegroupimage"),
        ("projects", "0005_projecttab_uuid"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="projecttab",
            constraint=models.UniqueConstraint(
                condition=models.Q(("uuid__isnull", False)),
                fields=("uuid", "project"),
                name="unique_project_tab",
            ),
        ),
    ]
