# Generated by Django 4.2.15 on 2024-10-02 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_project_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectmessage",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="projects.project",
            ),
        ),
    ]
