# Generated by Django 6.0.8 on 2026-09-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projecttab_show_tab_alter_projecttab_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projecttab',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='projecttab',
            name='order',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
