# Generated by Django 3.2.13 on 2022-05-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0003_tag'),
        ('projects', '0006_project_organization_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='organization_tags',
            field=models.ManyToManyField(to='misc.Tag'),
        ),
    ]
