# Generated by Django 6.0.8 on 2026-09-21 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_projecttab_options_projecttab_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttab',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
