# Generated by Django 3.2.13 on 2022-05-12 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_auto_20220512_1840'),
        ('projects', '0007_alter_project_organization_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproject',
            name='template',
        ),
        migrations.RemoveField(
            model_name='project',
            name='template',
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='main_category',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.projectcategory'),
        ),
        migrations.AddField(
            model_name='project',
            name='main_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.projectcategory'),
        ),
    ]
