# Generated by Django 3.2.13 on 2022-05-17 16:09

from django.db import migrations, models
from django.utils.text import slugify


def generate_slug_for_existing_projects(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    HistoricalProject = apps.get_model("projects", "HistoricalProject")
    db_alias = schema_editor.connection.alias
    projects = Project.objects.using(db_alias).filter(slug__isnull=True)
    for index, project in enumerate(projects):
        raw_slug = slugify(project.title[0:46])
        # Check that the slug is not already in use
        same_slug_count = 0
        slug = raw_slug
        while Project.objects.filter(slug=slug).exists():
            same_slug_count += 1
            slug = f"{raw_slug}-{same_slug_count}"
        Project.objects.filter(id=project.id).update(slug=slug)
        project.refresh_from_db()
        HistoricalProject.objects.using(db_alias) \
            .filter(id=project.id) \
            .update(slug=project.slug)
        print(f"{index} / {len(projects)}")


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20220512_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.RunPython(generate_slug_for_existing_projects, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
