# Generated by Django 3.2.13 on 2022-05-18 09:24

from django.db import migrations, models


def truncate_existing_projects_title(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    HistoricalProject = apps.get_model("projects", "HistoricalProject")
    db_alias = schema_editor.connection.alias

    projects = Project.objects.using(db_alias) \
        .annotate(title_len=models.functions.Length('title')) \
        .filter(title_len__gte=255)
    historical_projects = HistoricalProject.objects.using(db_alias) \
        .annotate(title_len=models.functions.Length('title')) \
        .filter(title_len__gte=255)

    for project in projects:
        Project.objects.using(db_alias).filter(id=project.id).update(title=project.title[0:255])
    for project in historical_projects:
        HistoricalProject.objects.using(db_alias).filter(id=project.id).update(title=project.title[0:255])


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20220512_1840'),
    ]

    operations = [
        migrations.RunPython(truncate_existing_projects_title, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='historicalproject',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
