# Generated by Django 6.0.8 on 2026-09-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_projecttab_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttab',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('blog', 'Blog'), ('members', 'Members'), ('groups', 'Groups'), ('linked_projects', 'Linked Projects'), ('locations', 'Locations'), ('comments', 'Comments'), ('goals', 'Goals'), ('resources', 'Resources'), ('blogs', 'Blogs'), ('announcements', 'Announcements'), ('messages', 'Messages')], default='text', max_length=32),
        ),
    ]
