# Generated by Django 3.2.13 on 2022-05-19 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20220517_1609'),
        ('projects', '0009_auto_20220518_0924'),
    ]

    operations = [
    ]
