# Generated by Django 4.2.17 on 2025-01-21 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_historicalproject_duplicated_from_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="organization_tags",
        ),
        migrations.RemoveField(
            model_name="project",
            name="wikipedia_tags",
        ),
    ]
