# Generated by Django 3.2.13 on 2022-05-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_merge_0009_auto_20220517_1609_0009_auto_20220518_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='slug',
            field=models.SlugField(),
        ),
    ]
