# Generated by Django 4.2.18 on 2025-02-11 14:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_remove_project_organization_tags_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproject",
            name="outdated_slugs",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.SlugField(), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="outdated_slugs",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.SlugField(), default=list, size=None
            ),
        ),
    ]
