# Generated by Django 6.0.8 on 2026-09-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_alter_image_options_peoplegroupimage'),
        ('projects', '0011_alter_projecttab_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='projecttab',
            constraint=models.UniqueConstraint(condition=models.Q(('type__in', ('blog', 'text')), _negated=True), fields=('type', 'project'), name='unique_project_tab_type_bridge'),
        ),
    ]
