# Generated by Django 4.2.20 on 2025-04-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0011_historicalproject_outdated_slugs_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproject",
            name="language",
            field=models.CharField(
                choices=[("fr", "French"), ("en", "English"), ("de", "German")],
                default="en",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="language",
            field=models.CharField(
                choices=[("fr", "French"), ("en", "English"), ("de", "German")],
                default="en",
                max_length=2,
            ),
        ),
    ]
