# Generated by Django 6.0.8 on 2026-10-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_alter_image_options_peoplegroupimage'),
        ('projects', '0012_projecttab_unique_project_tab_type_bridge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttab',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AddConstraint(
            model_name='projecttab',
            constraint=models.UniqueConstraint(fields=('slug', 'project'), name='unique_project_tab_slug'),
        ),
    ]
