# Generated by Django 4.0.5 on 2022-06-27 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


def give_reason_to_existing_versions(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    HistoricalProject = apps.get_model("projects", "HistoricalProject")

    updated_projects = HistoricalProject.objects.using(db_alias).exclude(
        history_date__year=2022, history_date__month=5, history_date__day=6
    ).filter(history_change_reason=None)
    updated_projects.update(history_change_reason="Unknown")


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0003_tag'),
        ('organizations', '0013_organization_is_logo_visible_on_parent_dashboard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0012_alter_projectmember_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='main_category',
            field=simple_history.models.HistoricForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.projectcategory'),
        ),
        migrations.AlterField(
            model_name='historicalprojectmember',
            name='project',
            field=simple_history.models.HistoricForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='linkedproject',
            name='target',
            field=simple_history.models.HistoricForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_projects', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='project',
            name='main_category',
            field=simple_history.models.HistoricForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.projectcategory'),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='project',
            field=simple_history.models.HistoricForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.CreateModel(
            name='HistoricalProject_organization_tags',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='projects.historicalproject')),
                ('project', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.project')),
                ('tag', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='misc.tag')),
            ],
            options={
                'verbose_name': 'HistoricalProject_organization_tags',
            },
        ),
        migrations.CreateModel(
            name='HistoricalProject_categories',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('m2m_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to='projects.historicalproject')),
                ('project', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.project')),
                ('projectcategory', models.ForeignKey(blank=True, db_constraint=False, db_tablespace='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.projectcategory')),
            ],
            options={
                'verbose_name': 'HistoricalProject_categories',
            },
        ),
        migrations.CreateModel(
            name='HistoricalLinkedProject',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.project')),
                ('target', simple_history.models.HistoricForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.project')),
            ],
            options={
                'verbose_name': 'historical linked project',
                'verbose_name_plural': 'historical linked projects',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RunPython(give_reason_to_existing_versions, migrations.RunPython.noop),
    ]
