# Generated by Django 4.2.20 on 2025-04-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0012_alter_historicalproject_language_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproject",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("fr", "Français"), ("de", "Deutsch")],
                default="en",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("fr", "Français"), ("de", "Deutsch")],
                default="en",
                max_length=2,
            ),
        ),
    ]
