# Generated by Django 4.2.20 on 2025-04-24 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0023_new_template_model"),
        ("projects", "0013_alter_historicalproject_language_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproject",
            name="template",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="organizations.template",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="organizations.template",
            ),
        ),
    ]
