# Generated by Django 4.2.20 on 2025-04-24 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0013_alter_historicalproject_language_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalproject",
            name="main_category",
        ),
        migrations.RemoveField(
            model_name="project",
            name="main_category",
        ),
    ]
