# Generated by Django 4.2.20 on 2025-04-28 14:14

import apps.commons.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0002_initial"),
        ("projects", "0013_alter_historicalproject_language_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectTab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("text", "Text"), ("blog", "Blog")],
                        default="text",
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "images",
                    models.ManyToManyField(
                        related_name="project_tabs", to="files.image"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_tabs",
                        to="projects.project",
                    ),
                ),
            ],
            bases=(
                models.Model,
                apps.commons.mixins.ProjectRelated,
                apps.commons.mixins.OrganizationRelated,
            ),
        ),
        migrations.CreateModel(
            name="ProjectTabItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "images",
                    models.ManyToManyField(
                        related_name="project_tab_items", to="files.image"
                    ),
                ),
                (
                    "tab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="projects.projecttab",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
            bases=(
                models.Model,
                apps.commons.mixins.ProjectRelated,
                apps.commons.mixins.OrganizationRelated,
            ),
        ),
    ]
