# Generated by Django 4.2.20 on 2025-04-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0014_projecttab_projecttabitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="projecttab",
            name="icon",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
