# Generated by Django 4.0.7 on 2022-12-14 13:29

from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0003_tag'),
        ('organizations', '0021_alter_historicalprojectcategory_template_and_more'),
        ('projects', '0015_alter_historicalproject_publication_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='life_status',
            field=models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('toreview', 'To Review')], default='running', max_length=10, verbose_name='life status'),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='main_category',
            field=simple_history.models.HistoricForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.projectcategory', verbose_name='main category'),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='project',
            name='categories',
            field=models.ManyToManyField(related_name='projects', to='organizations.projectcategory', verbose_name='categories'),
        ),
        migrations.AlterField(
            model_name='project',
            name='life_status',
            field=models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('canceled', 'Canceled'), ('toreview', 'To Review')], default='running', max_length=10, verbose_name='life status'),
        ),
        migrations.AlterField(
            model_name='project',
            name='main_category',
            field=simple_history.models.HistoricForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizations.projectcategory', verbose_name='main category'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='project',
            name='wikipedia_tags',
            field=models.ManyToManyField(related_name='projects', to='misc.wikipediatag', verbose_name='wikipedia tags'),
        ),
    ]
