# Generated by Django 4.2.20 on 2025-06-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0015_projecttab_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproject",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("fr", "Français"),
                    ("de", "Deutsch"),
                    ("nl", "Dutch"),
                    ("et", "Estonian"),
                    ("ca", "Catalan"),
                ],
                default="en",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("fr", "Français"),
                    ("de", "Deutsch"),
                    ("nl", "Dutch"),
                    ("et", "Estonian"),
                    ("ca", "Catalan"),
                ],
                default="en",
                max_length=2,
            ),
        ),
    ]
