# Generated by Django 4.0.7 on 2022-12-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_alter_historicalproject_life_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='language',
            field=models.CharField(choices=[('fr', 'French'), ('en', 'English')], default='en', max_length=2),
        ),
        migrations.AlterField(
            model_name='project',
            name='language',
            field=models.CharField(choices=[('fr', 'French'), ('en', 'English')], default='en', max_length=2),
        ),
    ]
