# Generated by Django 4.2.22 on 2025-06-18 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0016_alter_historicalproject_language_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogentry",
            options={
                "ordering": ["-created_at"],
                "verbose_name_plural": "Blog entries",
            },
        ),
    ]
