# Generated by Django 4.2.22 on 2025-07-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0017_alter_blogentry_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="description_ca",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="description_de",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="description_en",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="description_et",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="description_fr",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="description_nl",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="title_ca",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="title"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="title_de",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="title"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="title_en",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="title"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="title_et",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="title"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="title_fr",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="title"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="title_nl",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="title"
            ),
        ),
    ]
