# Generated by Django 4.0.8 on 2022-12-21 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_alter_historicalproject_language_and_more'),
        ('notifications', '0012_remove_membernotificationsettings_member_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='members',
        ),
    ]
