# Generated by Django 4.2.22 on 2025-06-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0017_alter_blogentry_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproject",
            name="translated_description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="historicalproject",
            name="translated_title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="project",
            name="translated_description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="project",
            name="translated_description_ca",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="translated_description_de",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="translated_description_en",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="translated_description_et",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="translated_description_fr",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="translated_description_nl",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="translated_title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="project",
            name="translated_title_ca",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="translated_title_de",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="translated_title_en",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="translated_title_et",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="translated_title_fr",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="translated_title_nl",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
