# Generated by Django 4.0.8 on 2023-01-26 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_remove_project_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallinkedproject',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='linkedproject',
            name='reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
