# Generated by Django 4.2.22 on 2025-07-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0018_project_description_ca_project_description_de_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogentry",
            name="content_ca",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogentry",
            name="content_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogentry",
            name="content_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogentry",
            name="content_et",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogentry",
            name="content_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogentry",
            name="content_nl",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogentry",
            name="title_ca",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="blogentry",
            name="title_de",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="blogentry",
            name="title_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="blogentry",
            name="title_et",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="blogentry",
            name="title_fr",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="blogentry",
            name="title_nl",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="description_ca",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="description_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="description_et",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="description_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="description_nl",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="title_ca",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="title_de",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="title_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="title_et",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="title_fr",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="title_nl",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="description_ca",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="description_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="description_et",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="description_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="description_nl",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="title_ca",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="title_de",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="title_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="title_et",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="title_fr",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="title_nl",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="purpose_ca",
            field=models.TextField(blank=True, null=True, verbose_name="main goal"),
        ),
        migrations.AddField(
            model_name="project",
            name="purpose_de",
            field=models.TextField(blank=True, null=True, verbose_name="main goal"),
        ),
        migrations.AddField(
            model_name="project",
            name="purpose_en",
            field=models.TextField(blank=True, null=True, verbose_name="main goal"),
        ),
        migrations.AddField(
            model_name="project",
            name="purpose_et",
            field=models.TextField(blank=True, null=True, verbose_name="main goal"),
        ),
        migrations.AddField(
            model_name="project",
            name="purpose_fr",
            field=models.TextField(blank=True, null=True, verbose_name="main goal"),
        ),
        migrations.AddField(
            model_name="project",
            name="purpose_nl",
            field=models.TextField(blank=True, null=True, verbose_name="main goal"),
        ),
        migrations.AddField(
            model_name="projectmessage",
            name="content_ca",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectmessage",
            name="content_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectmessage",
            name="content_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectmessage",
            name="content_et",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectmessage",
            name="content_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectmessage",
            name="content_nl",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projecttab",
            name="description_ca",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projecttab",
            name="description_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projecttab",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projecttab",
            name="description_et",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projecttab",
            name="description_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projecttab",
            name="description_nl",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projecttab",
            name="title_ca",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="projecttab",
            name="title_de",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="projecttab",
            name="title_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="projecttab",
            name="title_et",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="projecttab",
            name="title_fr",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="projecttab",
            name="title_nl",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="projecttabitem",
            name="content_ca",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projecttabitem",
            name="content_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projecttabitem",
            name="content_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projecttabitem",
            name="content_et",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projecttabitem",
            name="content_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projecttabitem",
            name="content_nl",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projecttabitem",
            name="title_ca",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="projecttabitem",
            name="title_de",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="projecttabitem",
            name="title_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="projecttabitem",
            name="title_et",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="projecttabitem",
            name="title_fr",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="projecttabitem",
            name="title_nl",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
