# Generated by Django 4.2.22 on 2025-09-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0019_blogentry_content_detected_language_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogentry",
            name="content_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogentry",
            name="title_es",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="description_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="title_es",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="description_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="title_es",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="description_es",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="project",
            name="purpose_es",
            field=models.TextField(blank=True, null=True, verbose_name="main goal"),
        ),
        migrations.AddField(
            model_name="project",
            name="title_es",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="title"
            ),
        ),
        migrations.AddField(
            model_name="projectmessage",
            name="content_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projecttab",
            name="description_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projecttab",
            name="title_es",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="projecttabitem",
            name="content_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projecttabitem",
            name="title_es",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="historicalproject",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("fr", "Français"),
                    ("de", "Deutsch"),
                    ("nl", "Dutch"),
                    ("et", "Estonian"),
                    ("ca", "Catalan"),
                    ("es", "Español"),
                ],
                default="en",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("fr", "Français"),
                    ("de", "Deutsch"),
                    ("nl", "Dutch"),
                    ("et", "Estonian"),
                    ("ca", "Catalan"),
                    ("es", "Español"),
                ],
                default="en",
                max_length=2,
            ),
        ),
    ]
