# Generated by Django 4.0.10 on 2023-05-17 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_alter_historicallinkedproject_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicallinkedproject',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='linkedproject',
            name='reason',
        ),
    ]
