# Generated by Django 4.2.1 on 2023-07-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0037_alter_privacysettings_facebook_and_more"),
        ("projects", "0020_remove_historicallinkedproject_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="member_people_groups",
            field=models.ManyToManyField(
                related_name="memberProjects", to="accounts.peoplegroup"
            ),
        ),
    ]
