# Generated by Django 4.2.22 on 2025-10-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0020_blogentry_content_es_blogentry_title_es_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogentry",
            name="title_ca",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="blogentry",
            name="title_de",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="blogentry",
            name="title_en",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="blogentry",
            name="title_es",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="blogentry",
            name="title_et",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="blogentry",
            name="title_fr",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="blogentry",
            name="title_nl",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="goal",
            name="title_ca",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="goal",
            name="title_de",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="goal",
            name="title_en",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="goal",
            name="title_es",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="goal",
            name="title_et",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="goal",
            name="title_fr",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="goal",
            name="title_nl",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="title_ca",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="title_de",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="title_en",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="title_es",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="title_et",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="title_fr",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="title_nl",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="title_ca",
            field=models.CharField(
                blank=True, max_length=1020, null=True, verbose_name="title"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="title_de",
            field=models.CharField(
                blank=True, max_length=1020, null=True, verbose_name="title"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="title_en",
            field=models.CharField(
                blank=True, max_length=1020, null=True, verbose_name="title"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="title_es",
            field=models.CharField(
                blank=True, max_length=1020, null=True, verbose_name="title"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="title_et",
            field=models.CharField(
                blank=True, max_length=1020, null=True, verbose_name="title"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="title_fr",
            field=models.CharField(
                blank=True, max_length=1020, null=True, verbose_name="title"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="title_nl",
            field=models.CharField(
                blank=True, max_length=1020, null=True, verbose_name="title"
            ),
        ),
        migrations.AlterField(
            model_name="projecttab",
            name="title_ca",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="projecttab",
            name="title_de",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="projecttab",
            name="title_en",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="projecttab",
            name="title_es",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="projecttab",
            name="title_et",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="projecttab",
            name="title_fr",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="projecttab",
            name="title_nl",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="projecttabitem",
            name="title_ca",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="projecttabitem",
            name="title_de",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="projecttabitem",
            name="title_en",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="projecttabitem",
            name="title_es",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="projecttabitem",
            name="title_et",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="projecttabitem",
            name="title_fr",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="projecttabitem",
            name="title_nl",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
    ]
