# Generated by Django 4.2.22 on 2025-10-01 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0030_alter_organization_options_and_more"),
        ("projects", "0020_blogentry_content_es_blogentry_title_es_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproject",
            name="template",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="organizations.template",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="organizations.template",
            ),
        ),
    ]
