# Generated by Django 4.2.22 on 2025-10-21 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0021_alter_blogentry_title_ca_alter_blogentry_title_de_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproject",
            name="template",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="organizations.template",
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="organizations.template",
            ),
        ),
    ]
