# Generated by Django 4.2.3 on 2023-08-01 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0021_project_member_people_groups"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="groups",
        ),
    ]
