# Generated by Django 4.2.3 on 2023-08-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("accounts", "0044_remove_peoplegroup_groups_remove_projectuser_groups_and_more"),
        ("projects", "0022_remove_project_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="groups",
            field=models.ManyToManyField(related_name="projects", to="auth.group"),
        ),
    ]
