# Generated by Django 4.2.22 on 2025-10-22 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0032_alter_organization_options_and_more"),
        ("projects", "0022_historicalproject_template_project_template"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalproject",
            name="main_category",
        ),
        migrations.RemoveField(
            model_name="project",
            name="main_category",
        ),
    ]
