# Generated by Django 4.2.3 on 2023-08-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0024_alter_project_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalproject",
            name="permissions_up_to_date",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="permissions_up_to_date",
            field=models.BooleanField(default=False),
        ),
    ]
