# Generated by Django 4.2.3 on 2023-08-11 13:28

from functools import reduce
from django.conf import settings
from django.db import migrations


def migrate_member_people_groups(apps, schema_editor):
    Project = apps.get_model("projects", "Project")  # noqa
    Group = apps.get_model("auth", "Group")
    for project in Project.objects.all():
        name = f"project:#{project.pk}:people_groups"
        group, _ = Group.objects.get_or_create(name=name)
        people_groups = project.member_people_groups.all()
        people_groups_groups = [people_group.groups.all() for people_group in people_groups]
        people_groups_groups = reduce(lambda x, y: x.union(y), people_groups_groups, set())
        people_groups_users = [group.users.all() for group in people_groups_groups]
        people_groups_users = reduce(lambda x, y: x.union(y), people_groups_users, set())
        group.projects.set([project])
        group.people_groups.set(people_groups)
        group.users.set(people_groups_users)


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0025_historicalproject_permissions_up_to_date_and_more"),
    ]

    operations = [
        migrations.RunPython(migrate_member_people_groups, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="project",
            name="member_people_groups",
        ),
    ]
