# Generated by Django 4.2.3 on 2023-08-23 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0026_remove_project_member_people_groups"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={
                "permissions": (
                    ("lock_project", "Can lock and unlock a project"),
                    ("duplicate_project", "Can duplicate a project"),
                    ("add_review", "Can add project's reviews"),
                    ("change_review", "Can change project's reviews"),
                    ("delete_review", "Can delete project's reviews"),
                    ("add_comment", "Can add project's comments"),
                    ("change_comment", "Can change project's comments"),
                    ("delete_comment", "Can delete project's comments"),
                    ("add_follow", "Can add project's follows"),
                    ("change_follow", "Can change project's follows"),
                    ("delete_follow", "Can delete project's follows"),
                )
            },
        ),
    ]
