# Generated by Django 4.2.3 on 2023-08-30 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0027_alter_project_options"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="projectmember",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="projectmember",
            name="project",
        ),
        migrations.RemoveField(
            model_name="projectmember",
            name="user",
        ),
        migrations.DeleteModel(
            name="HistoricalProjectMember",
        ),
        migrations.DeleteModel(
            name="ProjectMember",
        ),
    ]
