# Generated by Django 4.2.22 on 2025-09-29 16:05

import apps.commons.mixins
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccessRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(blank=True, max_length=255)),
                ("given_name", models.CharField(blank=True, max_length=255)),
                ("family_name", models.CharField(blank=True, max_length=255)),
                ("job", models.CharField(blank=True, max_length=255)),
                ("message", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("message_en", models.TextField(blank=True, null=True)),
                ("message_fr", models.TextField(blank=True, null=True)),
                ("message_de", models.TextField(blank=True, null=True)),
                ("message_nl", models.TextField(blank=True, null=True)),
                ("message_et", models.TextField(blank=True, null=True)),
                ("message_ca", models.TextField(blank=True, null=True)),
                (
                    "message_detected_language",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("message_es", models.TextField(blank=True, null=True)),
            ],
            options={
                "permissions": (
                    ("manage_accessrequest", "Can manage access requests"),
                ),
            },
            bases=(apps.commons.mixins.OrganizationRelated, models.Model),
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.UUIDField(default=uuid.uuid4)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("expire_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "description_en",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "description_fr",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "description_de",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "description_nl",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "description_et",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "description_ca",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "description_detected_language",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "description_es",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(
                apps.commons.mixins.HasOwner,
                apps.commons.mixins.OrganizationRelated,
                models.Model,
            ),
        ),
    ]
