# Generated by Django 4.0.10 on 2023-03-27 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='group',
            new_name='people_group',
        ),
    ]
