# Generated by Django 4.2.22 on 2025-09-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invitations", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessrequest",
            name="message_ca",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accessrequest",
            name="message_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accessrequest",
            name="message_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accessrequest",
            name="message_et",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accessrequest",
            name="message_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="accessrequest",
            name="message_nl",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invitation",
            name="description_ca",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="invitation",
            name="description_de",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="invitation",
            name="description_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="invitation",
            name="description_et",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="invitation",
            name="description_fr",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="invitation",
            name="description_nl",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
