# Generated by Django 4.0.10 on 2023-03-27 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_peoplegroup_sdgs'),
        ('invitations', '0002_rename_group_invitation_people_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='people_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.peoplegroup'),
        ),
    ]
