# Generated by Django 6.0.8 on 2026-10-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='redirect_uri',
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
