# Generated by Django 4.2.22 on 2025-09-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "invitations",
            "0003_accessrequest_message_ca_accessrequest_message_de_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="accessrequest",
            name="message_detected_language",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="invitation",
            name="description_detected_language",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
