# Generated by Django 4.2.22 on 2025-09-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invitations", "0004_accessrequest_message_detected_language_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accessrequest",
            name="message_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invitation",
            name="description_es",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
