# Generated by Django 4.2.22 on 2025-10-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invitations", "0005_accessrequest_message_es_invitation_description_es"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invitation",
            name="description_ca",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="description_de",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="description_en",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="description_es",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="description_et",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="description_fr",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="description_nl",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
    ]
