# Generated by Django 4.2.7 on 2024-01-05 17:16

import apps.accounts.utils
import apps.commons.mixins
import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProjectUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "people_id",
                    models.UUIDField(
                        help_text="id of user in people", null=True, unique=True
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="id of user in their organization",
                        max_length=255,
                    ),
                ),
                ("email", models.CharField(max_length=255, unique=True)),
                ("given_name", models.CharField(blank=True, max_length=255)),
                ("family_name", models.CharField(blank=True, max_length=255)),
                ("slug", models.SlugField(unique=True)),
                (
                    "language",
                    models.CharField(
                        choices=[("fr", "French"), ("en", "English")],
                        default="en",
                        max_length=2,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "onboarding_status",
                    models.JSONField(
                        default=apps.accounts.utils.default_onboarding_status
                    ),
                ),
                (
                    "birthdate",
                    models.DateField(
                        blank=True,
                        max_length=255,
                        null=True,
                        validators=[
                            django.core.validators.MaxValueValidator(
                                limit_value=datetime.date.today
                            )
                        ],
                    ),
                ),
                ("pronouns", models.CharField(blank=True, max_length=32)),
                ("personal_description", models.TextField(blank=True)),
                ("short_description", models.TextField(blank=True)),
                ("professional_description", models.TextField(blank=True)),
                ("location", models.TextField(blank=True)),
                ("job", models.CharField(blank=True, max_length=255)),
                (
                    "sdgs",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveSmallIntegerField(
                            choices=[
                                (1, "No poverty"),
                                (2, "Zero hunger"),
                                (3, "Good health and well-being"),
                                (4, "Quality education"),
                                (5, "Gender equality"),
                                (6, "Clean water and sanitation"),
                                (7, "Affordable and clean energy"),
                                (8, "Decent work and economic growth"),
                                (9, "Industry, innovation and infrastructure"),
                                (10, "Reduces inequalities"),
                                (11, "Sustainable cities and communities"),
                                (12, "Responsible consumption & production"),
                                (13, "Climate action"),
                                (14, "Life below water"),
                                (15, "Life on land"),
                                (16, "Peace, justice and strong institutions"),
                                (17, "Partnerships for the goals"),
                            ],
                            unique=True,
                        ),
                        default=list,
                        null=True,
                        size=17,
                    ),
                ),
                ("facebook", models.URLField(blank=True)),
                ("mobile_phone", models.CharField(blank=True, max_length=255)),
                ("linkedin", models.URLField(blank=True)),
                ("medium", models.URLField(blank=True)),
                ("website", models.CharField(blank=True, max_length=255)),
                ("personal_email", models.EmailField(blank=True, max_length=254)),
                ("skype", models.CharField(blank=True, max_length=255)),
                ("landline_phone", models.CharField(blank=True, max_length=255)),
                ("twitter", models.URLField(blank=True)),
                ("people_data", models.JSONField(default=dict)),
                ("type", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            bases=(
                models.Model,
                apps.commons.mixins.HasMultipleIDs,
                apps.commons.mixins.HasOwner,
                apps.commons.mixins.OrganizationRelated,
            ),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="PeopleGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("permissions_up_to_date", models.BooleanField(default=False)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("short_description", models.TextField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("type", models.CharField(blank=True, max_length=50)),
                (
                    "sdgs",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveSmallIntegerField(
                            choices=[
                                (1, "No poverty"),
                                (2, "Zero hunger"),
                                (3, "Good health and well-being"),
                                (4, "Quality education"),
                                (5, "Gender equality"),
                                (6, "Clean water and sanitation"),
                                (7, "Affordable and clean energy"),
                                (8, "Decent work and economic growth"),
                                (9, "Industry, innovation and infrastructure"),
                                (10, "Reduces inequalities"),
                                (11, "Sustainable cities and communities"),
                                (12, "Responsible consumption & production"),
                                (13, "Climate action"),
                                (14, "Life below water"),
                                (15, "Life on land"),
                                (16, "Peace, justice and strong institutions"),
                                (17, "Partnerships for the goals"),
                            ],
                            unique=True,
                        ),
                        default=list,
                        null=True,
                        size=17,
                    ),
                ),
                (
                    "publication_status",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("private", "Private"),
                            ("org", "Org"),
                        ],
                        default="org",
                        max_length=10,
                        verbose_name="visibility",
                    ),
                ),
                ("is_root", models.BooleanField(default=False)),
                ("people_data", models.JSONField(default=dict)),
                ("people_id", models.CharField(max_length=255)),
                ("order", models.IntegerField(null=True)),
            ],
            bases=(
                apps.commons.mixins.HasMultipleIDs,
                models.Model,
                apps.commons.mixins.OrganizationRelated,
            ),
        ),
        migrations.CreateModel(
            name="PrivacySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "publication_status",
                    models.CharField(
                        choices=[
                            ("hide", "Hide"),
                            ("org", "Organization"),
                            ("pub", "Public"),
                        ],
                        default="pub",
                        max_length=4,
                    ),
                ),
                (
                    "profile_picture",
                    models.CharField(
                        choices=[
                            ("hide", "Hide"),
                            ("org", "Organization"),
                            ("pub", "Public"),
                        ],
                        default="org",
                        max_length=4,
                    ),
                ),
                (
                    "skills",
                    models.CharField(
                        choices=[
                            ("hide", "Hide"),
                            ("org", "Organization"),
                            ("pub", "Public"),
                        ],
                        default="pub",
                        max_length=4,
                    ),
                ),
                (
                    "mobile_phone",
                    models.CharField(
                        choices=[
                            ("hide", "Hide"),
                            ("org", "Organization"),
                            ("pub", "Public"),
                        ],
                        default="org",
                        max_length=4,
                    ),
                ),
                (
                    "personal_email",
                    models.CharField(
                        choices=[
                            ("hide", "Hide"),
                            ("org", "Organization"),
                            ("pub", "Public"),
                        ],
                        default="org",
                        max_length=4,
                    ),
                ),
                (
                    "socials",
                    models.CharField(
                        choices=[
                            ("hide", "Hide"),
                            ("org", "Organization"),
                            ("pub", "Public"),
                        ],
                        default="org",
                        max_length=4,
                    ),
                ),
            ],
            bases=(models.Model, apps.commons.mixins.HasOwner),
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("skill", "Skill"), ("hobby", "Hobby")],
                        default="skill",
                        max_length=8,
                    ),
                ),
                ("level", models.SmallIntegerField()),
                ("level_to_reach", models.SmallIntegerField()),
                ("category", models.CharField(blank=True, default="", max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=(models.Model, apps.commons.mixins.HasOwner),
        ),
    ]
