# Generated by Django 3.2.12 on 2022-04-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('keycloak_id', models.UUIDField(help_text='id of user in keycloak', unique=True)),
                ('people_id', models.UUIDField(help_text='id of user in people', null=True, unique=True)),
                ('email', models.CharField(max_length=255)),
                ('given_name', models.CharField(blank=True, max_length=255)),
                ('family_name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
