# Generated by Django 4.2.7 on 2024-01-05 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("misc", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="wikipedia_tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="misc.wikipediatag"
            ),
        ),
        migrations.AddField(
            model_name="privacysettings",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="privacy_settings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
