# Generated by Django 4.0.6 on 2022-07-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_skill_projectuser_birthdate_projectuser_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuser',
            name='pronouns',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
