# Generated by Django 4.2.10 on 2024-03-11 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="peoplegroup",
            name="type",
        ),
    ]
