# Generated by Django 4.2.7 on 2024-02-07 10:10

from django.db import migrations, models
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectuser",
            name="generated_summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="projectuser",
            name="summary_embedding",
            field=pgvector.django.VectorField(dimensions=1024, null=True),
        ),
    ]
