# Generated by Django 4.2.7 on 2024-02-12 13:53

from django.db import migrations, models
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectuser",
            name="embedding",
            field=pgvector.django.VectorField(dimensions=1024, null=True),
        ),
        migrations.AddField(
            model_name="projectuser",
            name="embedding_summary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="projectuser",
            name="last_embedding_update",
            field=models.DateTimeField(null=True),
        ),
    ]
