# Generated by Django 5.2.11 on 2026-02-12 09:28

import apps.commons.mixins
import django.db.models.deletion
import services.translator.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_peoplegroup_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="PeopleGroupLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("team", "Team"),
                            ("impact", "Impact"),
                            ("address", "Address"),
                        ],
                        default="team",
                        max_length=10,
                    ),
                ),
                (
                    "title_detected_language",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("title_en", models.CharField(blank=True, max_length=1020, null=True)),
                ("title_fr", models.CharField(blank=True, max_length=1020, null=True)),
                ("title_de", models.CharField(blank=True, max_length=1020, null=True)),
                ("title_nl", models.CharField(blank=True, max_length=1020, null=True)),
                ("title_et", models.CharField(blank=True, max_length=1020, null=True)),
                ("title_ca", models.CharField(blank=True, max_length=1020, null=True)),
                ("title_es", models.CharField(blank=True, max_length=1020, null=True)),
                (
                    "description_detected_language",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("description_en", models.TextField(blank=True, null=True)),
                ("description_fr", models.TextField(blank=True, null=True)),
                ("description_de", models.TextField(blank=True, null=True)),
                ("description_nl", models.TextField(blank=True, null=True)),
                ("description_et", models.TextField(blank=True, null=True)),
                ("description_ca", models.TextField(blank=True, null=True)),
                ("description_es", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=(
                services.translator.mixins.HasAutoTranslatedFields,
                apps.commons.mixins.DuplicableModel,
                models.Model,
            ),
        ),
        migrations.AddField(
            model_name="peoplegroup",
            name="location",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="people_group",
                to="accounts.peoplegrouplocation",
            ),
        ),
    ]
