# Generated by Django 5.2.10 on 2026-02-02 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_peoplegrouplocation_peoplegroup_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="peoplegroup",
            name="location",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="people_group",
                to="accounts.peoplegrouplocation",
            ),
        ),
    ]
