# Generated by Django 4.0.5 on 2022-06-20 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('accounts', '0004_auto_20220410_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='model',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_groups', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='model',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_permissions', to='contenttypes.contenttype'),
        ),
    ]
