# Generated by Django 6.0.5 on 2026-09-07 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_peoplegrouplocation_type"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="projectuser",
            managers=[],
        ),
    ]
