# Generated by Django 4.0.7 on 2022-09-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_group_model_alter_permission_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('keycloak_id', models.UUIDField(help_text='id of user in keycloak', unique=True)),
                ('client_id', models.CharField(max_length=255, unique=True)),
                ('groups', models.ManyToManyField(related_name='service_accounts', to='accounts.group')),
                ('permissions', models.ManyToManyField(related_name='service_accounts', to='accounts.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
