# Generated by Django 4.2.14 on 2024-07-26 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_projectuser_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="can_mentor",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="skill",
            name="needs_mentor",
            field=models.BooleanField(default=False),
        ),
    ]
