# Generated by Django 4.0.7 on 2022-10-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_serviceaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_id', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('type', models.CharField(blank=True, max_length=50)),
                ('order', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='skill',
            name='type',
        ),
        migrations.AddField(
            model_name='projectuser',
            name='people_data',
            field=models.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='projectuser',
            name='people_groups',
            field=models.ManyToManyField(to='accounts.peoplegroup'),
        ),
    ]
