# Generated by Django 4.2.14 on 2024-09-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_skill_can_mentor_skill_needs_mentor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="comment",
            field=models.TextField(blank=True, default=""),
        ),
    ]
