# Generated by Django 4.0.7 on 2022-10-14 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_peoplegroup_remove_skill_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peoplegroup',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.peoplegroup'),
        ),
    ]
