# Generated by Django 4.0.7 on 2022-10-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_peoplegroup_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectuser',
            name='people_data',
            field=models.JSONField(default=dict),
        ),
    ]
