# Generated by Django 4.2.15 on 2024-09-30 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_skill_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skill",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="old_skills",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
