# Generated by Django 4.2.16 on 2024-12-10 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_skill_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="privacysettings",
            old_name="personal_email",
            new_name="email",
        ),
    ]
