# Generated by Django 4.0.7 on 2022-10-17 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0003_tag'),
        ('accounts', '0009_alter_projectuser_people_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectuser',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='title',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='wikipedia_qid',
        ),
        migrations.AddField(
            model_name='skill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skill',
            name='wikipedia_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.wikipediatag'),
            preserve_default=False,
        ),
    ]
