# Generated by Django 4.2.16 on 2024-12-12 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_peoplegroup_created_at_peoplegroup_updated_at"),
        ("accounts", "0010_rename_personal_email_privacysettings_email"),
    ]

    operations = []
