# Generated by Django 4.2.17 on 2025-01-21 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_merge_20241212_1531"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Skill",
        ),
    ]
