# Generated by Django 4.0.7 on 2022-10-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_skill_unique user wikipedia_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectuser',
            name='people_groups',
            field=models.ManyToManyField(related_name='users', to='accounts.peoplegroup'),
        ),
    ]
