# Generated by Django 4.0.7 on 2022-12-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_projectuser_people_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuser',
            name='language',
            field=models.CharField(choices=[('fr', 'French'), ('en', 'English')], default='fr', max_length=2),
        ),
    ]
