# Generated by Django 4.2.17 on 2025-01-21 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_delete_skill"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="peoplegroup",
            name="order",
        ),
        migrations.RemoveField(
            model_name="peoplegroup",
            name="people_data",
        ),
        migrations.RemoveField(
            model_name="peoplegroup",
            name="people_id",
        ),
        migrations.RemoveField(
            model_name="projectuser",
            name="people_data",
        ),
        migrations.RemoveField(
            model_name="projectuser",
            name="type",
        ),
    ]
