# Generated by Django 4.0.8 on 2022-12-19 10:19

import apps.commons.db.abc
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_projectuser_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(choices=[('HIDE', 'Hide'), ('ORG', 'Organization'), ('PUB', 'Public')], default='HIDE', max_length=4)),
                ('profile_picture', models.CharField(choices=[('HIDE', 'Hide'), ('ORG', 'Organization'), ('PUB', 'Public')], default='HIDE', max_length=4)),
                ('profile', models.CharField(choices=[('HIDE', 'Hide'), ('ORG', 'Organization'), ('PUB', 'Public')], default='HIDE', max_length=4)),
                ('personal_email', models.CharField(choices=[('HIDE', 'Hide'), ('ORG', 'Organization'), ('PUB', 'Public')], default='HIDE', max_length=4)),
                ('academic_skills', models.CharField(choices=[('HIDE', 'Hide'), ('ORG', 'Organization'), ('PUB', 'Public')], default='HIDE', max_length=4)),
                ('other_skills', models.CharField(choices=[('HIDE', 'Hide'), ('ORG', 'Organization'), ('PUB', 'Public')], default='HIDE', max_length=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, apps.commons.db.abc.HasOwner),
        ),
    ]
