# Generated by Django 4.0.7 on 2022-12-16 12:26
from django.db import migrations, models


def set_language_from_organization(apps, schema_editor):
    ProjectUser = apps.get_model("accounts", "ProjectUser")  # noqa
    Organization = apps.get_model("organizations", "Organization")  # noqa
    ContentType = apps.get_model("contenttypes", "ContentType")  # noqa

    ct = ContentType.objects.get_for_model(Organization)
    for user in ProjectUser.objects.all():
        organization_groups = user.groups.filter(model=ct)
        if organization_groups.exists():
            group = organization_groups.first()
            organization = Organization.objects.get(pk=group.object_pk)
            user.language = organization.language
            user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_projectuser_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectuser',
            name='language',
            field=models.CharField(choices=[('fr', 'French'), ('en', 'English')], default='en', max_length=2),
        ),
        migrations.RunPython(set_language_from_organization, migrations.RunPython.noop)
    ]
