# Generated by Django 4.2.18 on 2025-02-28 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("accounts", "0014_peoplegroup_outdated_slugs_and_more"),
    ]
    state_operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("base", "Base"),
                            ("project", "Project"),
                            ("people_group", "People Group"),
                            ("organization", "Organization"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("superadmin", "Superadmin"),
                            ("default", "Default"),
                            ("reviewer", "Reviewer"),
                            ("owner", "Owner"),
                            ("reviewer_group", "Reviewer Group"),
                            ("owner_group", "Owner Group"),
                            ("member_group", "Member Group"),
                            ("leader", "Leader"),
                            ("manager", "Manager"),
                            ("member", "Member"),
                            ("admin", "Admin"),
                            ("facilitator", "Facilitator"),
                            ("user", "User"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="auth.group",
                    ),
                ),
                (
                    "projectuser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterModelTable(
            name="role",
            table="accounts_projectuser_groups",
        ),
        migrations.AlterField(
            model_name="projectuser",
            name="groups",
            field=models.ManyToManyField(
                related_name="users", through="accounts.Role", to="auth.group"
            ),
        ),
    ]
    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations),
        migrations.AddField(
            model_name="Role",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("base", "Base"),
                    ("project", "Project"),
                    ("people_group", "People Group"),
                    ("organization", "Organization"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="Role",
            name="name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("superadmin", "Superadmin"),
                    ("default", "Default"),
                    ("reviewer", "Reviewer"),
                    ("owner", "Owner"),
                    ("reviewer_group", "Reviewer Group"),
                    ("owner_group", "Owner Group"),
                    ("member_group", "Member Group"),
                    ("leader", "Leader"),
                    ("manager", "Manager"),
                    ("member", "Member"),
                    ("admin", "Admin"),
                    ("facilitator", "Facilitator"),
                    ("user", "User"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterModelTable(
            name="Role",
            table=None,
        ),
        migrations.RenameField(
            model_name="role",
            old_name="projectuser",
            new_name="user",
        ),
    ]
