# Generated by Django 4.0.8 on 2022-12-19 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_projectuser_language'),
        ('accounts', '0014_privacysettings'),
    ]

    operations = [
    ]
