# Generated by Django 4.2.20 on 2025-04-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_alter_projectuser_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectuser",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("fr", "Français"), ("de", "Deutsch")],
                default="en",
                max_length=2,
            ),
        ),
    ]
