# Generated by Django 4.0.8 on 2022-12-20 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_merge_20221219_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacysettings',
            name='academic_skills',
            field=models.CharField(choices=[('hide', 'Hide'), ('org', 'Organization'), ('pub', 'Public')], default='hide', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='privacysettings',
            name='other_skills',
            field=models.CharField(choices=[('hide', 'Hide'), ('org', 'Organization'), ('pub', 'Public')], default='hide', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='privacysettings',
            name='personal_email',
            field=models.CharField(choices=[('hide', 'Hide'), ('org', 'Organization'), ('pub', 'Public')], default='hide', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='privacysettings',
            name='phone_number',
            field=models.CharField(choices=[('hide', 'Hide'), ('org', 'Organization'), ('pub', 'Public')], default='hide', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='privacysettings',
            name='profile',
            field=models.CharField(choices=[('hide', 'Hide'), ('org', 'Organization'), ('pub', 'Public')], default='hide', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='privacysettings',
            name='profile_picture',
            field=models.CharField(choices=[('hide', 'Hide'), ('org', 'Organization'), ('pub', 'Public')], default='hide', max_length=4, null=True),
        ),
    ]
