# Generated by Django 4.2.20 on 2025-04-29 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0022_alter_organization_language_and_more"),
        ("accounts", "0016_alter_projectuser_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="peoplegroup",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="people_groups",
                to="organizations.organization",
            ),
        ),
    ]
