# Generated by Django 4.0.8 on 2022-12-23 16:18

import apps.commons.db.abc
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_privacysettings_academic_skills_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectuser',
            name='socials',
        ),
        migrations.CreateModel(
            name='Socials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True)),
                ('gsm', models.CharField(blank=True, max_length=255)),
                ('linkedin', models.URLField(blank=True)),
                ('medium', models.URLField(blank=True)),
                ('pwww', models.CharField(blank=True, max_length=255)),
                ('secondmail', models.EmailField(blank=True, max_length=254)),
                ('skype', models.CharField(blank=True, max_length=255)),
                ('tel', models.CharField(blank=True, max_length=255)),
                ('twitter', models.URLField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(models.Model, apps.commons.db.abc.HasOwner),
        ),
    ]
