# Generated by Django 4.2.20 on 2025-04-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_alter_peoplegroup_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="peoplegroup",
            name="publication_status",
            field=models.CharField(
                choices=[("public", "Public"), ("private", "Private"), ("org", "Org")],
                default="org",
                max_length=10,
            ),
        ),
    ]
