# Generated by Django 4.0.8 on 2022-12-29 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0023_remove_organization_members_and_more'),
        ('accounts', '0017_remove_projectuser_socials_socials'),
    ]

    operations = [
        migrations.AddField(
            model_name='peoplegroup',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization'),
        ),
    ]
