# Generated by Django 4.2.20 on 2025-06-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_alter_peoplegroup_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectuser",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
