# Generated by Django 4.0.8 on 2023-01-10 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_peoplegroup_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privacysettings',
            name='other_skills',
        ),
        migrations.RemoveField(
            model_name='privacysettings',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='projectuser',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='privacysettings',
            name='facebook',
            field=models.CharField(choices=[('hide', 'Hide'), ('org', 'Organization'), ('pub', 'Public')], default='hide', max_length=4),
        ),
        migrations.AddField(
            model_name='privacysettings',
            name='landline_phone',
            field=models.CharField(choices=[('hide', 'Hide'), ('org', 'Organization'), ('pub', 'Public')], default='hide', max_length=4),
        ),
        migrations.AddField(
            model_name='privacysettings',
            name='linkedin',
            field=models.CharField(choices=[('hide', 'Hide'), ('org', 'Organization'), ('pub', 'Public')], default='hide', max_length=4),
        ),
        migrations.AddField(
            model_name='privacysettings',
            name='medium',
            field=models.CharField(choices=[('hide', 'Hide'), ('org', 'Organization'), ('pub', 'Public')], default='hide', max_length=4),
        ),
        migrations.AddField(
            model_name='privacysettings',
            name='mobile_phone',
            field=models.CharField(choices=[('hide', 'Hide'), ('org', 'Organization'), ('pub', 'Public')], default='hide', max_length=4),
        ),
        migrations.AddField(
            model_name='privacysettings',
            name='personal_skills',
            field=models.CharField(choices=[('hide', 'Hide'), ('org', 'Organization'), ('pub', 'Public')], default='hide', max_length=4),
        ),
        migrations.AddField(
            model_name='privacysettings',
            name='skype',
            field=models.CharField(choices=[('hide', 'Hide'), ('org', 'Organization'), ('pub', 'Public')], default='hide', max_length=4),
        ),
        migrations.AddField(
            model_name='privacysettings',
            name='twitter',
            field=models.CharField(choices=[('hide', 'Hide'), ('org', 'Organization'), ('pub', 'Public')], default='hide', max_length=4),
        ),
        migrations.AddField(
            model_name='privacysettings',
            name='website',
            field=models.CharField(choices=[('hide', 'Hide'), ('org', 'Organization'), ('pub', 'Public')], default='hide', max_length=4),
        ),
        migrations.AddField(
            model_name='projectuser',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='projectuser',
            name='landline_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='projectuser',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='projectuser',
            name='medium',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='projectuser',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='projectuser',
            name='skype',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='projectuser',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='projectuser',
            name='website',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='skill',
            name='type',
            field=models.CharField(choices=[('academic', 'Academic'), ('personal', 'Personal')], default='academic', max_length=8),
        ),
        migrations.AlterField(
            model_name='privacysettings',
            name='academic_skills',
            field=models.CharField(choices=[('hide', 'Hide'), ('org', 'Organization'), ('pub', 'Public')], default='hide', max_length=4),
        ),
        migrations.AlterField(
            model_name='privacysettings',
            name='personal_email',
            field=models.CharField(choices=[('hide', 'Hide'), ('org', 'Organization'), ('pub', 'Public')], default='hide', max_length=4),
        ),
        migrations.AlterField(
            model_name='privacysettings',
            name='profile',
            field=models.CharField(choices=[('hide', 'Hide'), ('org', 'Organization'), ('pub', 'Public')], default='hide', max_length=4),
        ),
        migrations.AlterField(
            model_name='privacysettings',
            name='profile_picture',
            field=models.CharField(choices=[('hide', 'Hide'), ('org', 'Organization'), ('pub', 'Public')], default='hide', max_length=4),
        ),
        migrations.AlterField(
            model_name='projectuser',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='skill',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Socials',
        ),
    ]
