# Generated by Django 4.2.20 on 2025-06-13 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0018_alter_projectuser_language"),
        ("accounts", "0018_projectuser_description"),
    ]

    operations = []
