# Generated by Django 4.2.22 on 2025-07-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_merge_20250613_1133"),
    ]

    operations = [
        migrations.AddField(
            model_name="peoplegroup",
            name="description_ca",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="peoplegroup",
            name="description_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="peoplegroup",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="peoplegroup",
            name="description_et",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="peoplegroup",
            name="description_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="peoplegroup",
            name="description_nl",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="peoplegroup",
            name="name_ca",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="peoplegroup",
            name="name_de",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="peoplegroup",
            name="name_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="peoplegroup",
            name="name_et",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="peoplegroup",
            name="name_fr",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="peoplegroup",
            name="name_nl",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="peoplegroup",
            name="short_description_ca",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="peoplegroup",
            name="short_description_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="peoplegroup",
            name="short_description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="peoplegroup",
            name="short_description_et",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="peoplegroup",
            name="short_description_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="peoplegroup",
            name="short_description_nl",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectuser",
            name="description_ca",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectuser",
            name="description_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectuser",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectuser",
            name="description_et",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectuser",
            name="description_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectuser",
            name="description_nl",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectuser",
            name="job_ca",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="projectuser",
            name="job_de",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="projectuser",
            name="job_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="projectuser",
            name="job_et",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="projectuser",
            name="job_fr",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="projectuser",
            name="job_nl",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="projectuser",
            name="short_description_ca",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectuser",
            name="short_description_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectuser",
            name="short_description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectuser",
            name="short_description_et",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectuser",
            name="short_description_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectuser",
            name="short_description_nl",
            field=models.TextField(blank=True, null=True),
        ),
    ]
