# Generated by Django 4.0.8 on 2023-01-10 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_auto_20220523_1643'),
        ('accounts', '0019_remove_privacysettings_other_skills_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectuser',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='projectuser',
            name='profile_picture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='files.image'),
        ),
    ]
