# Generated by Django 4.2.22 on 2025-09-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_peoplegroup_description_ca_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="peoplegroup",
            name="description_detected_language",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="peoplegroup",
            name="name_detected_language",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="peoplegroup",
            name="short_description_detected_language",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="projectuser",
            name="description_detected_language",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="projectuser",
            name="job_detected_language",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="projectuser",
            name="short_description_detected_language",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
