# Generated by Django 4.0.8 on 2023-01-12 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_projectuser_profile_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectuser',
            old_name='position',
            new_name='job',
        ),
    ]
