# Generated by Django 4.2.22 on 2025-09-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0021_peoplegroup_description_detected_language_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="peoplegroup",
            name="description_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="peoplegroup",
            name="name_es",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="peoplegroup",
            name="short_description_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectuser",
            name="description_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectuser",
            name="job_es",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="projectuser",
            name="short_description_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="projectuser",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("fr", "Français"),
                    ("de", "Deutsch"),
                    ("nl", "Dutch"),
                    ("et", "Estonian"),
                    ("ca", "Catalan"),
                    ("es", "Español"),
                ],
                default="en",
                max_length=2,
            ),
        ),
    ]
