# Generated by Django 4.0.8 on 2023-01-13 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def id_to_keycloak_id(apps, schema_editor):
    PrivacySettings = apps.get_model("accounts", "PrivacySettings")  # noqa
    for setting in PrivacySettings.objects.all():
        setting._user = setting.user
        setting.save()

def keycloak_id_to_id(apps, schema_editor):
    PrivacySettings = apps.get_model("accounts", "PrivacySettings")  # noqa
    for setting in PrivacySettings.objects.all():
        setting.user = setting._user
        setting.save()

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_rename_position_projectuser_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacysettings',
            name='_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_settings', to=settings.AUTH_USER_MODEL, to_field='keycloak_id', null=True),
        ),
        migrations.AlterField(
            model_name='privacysettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, null=True),
        ),
        migrations.RunPython(id_to_keycloak_id, keycloak_id_to_id),
        migrations.RemoveField(model_name='privacysettings', name='user'),
        migrations.RenameField(model_name='privacysettings', old_name='_user', new_name='user'),
        migrations.AlterField(
            model_name='privacysettings',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_settings', to=settings.AUTH_USER_MODEL, to_field='keycloak_id'),
        ),
    ]
