# Generated by Django 4.0.8 on 2023-01-26 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_privacysettings_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectuser',
            name='is_superuser',
        ),
    ]
