# Generated by Django 4.2.22 on 2025-09-30 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0022_peoplegroup_description_es_peoplegroup_name_es_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectuser",
            name="signed_terms_and_conditions",
            field=models.JSONField(default=dict),
        ),
    ]
