# Generated by Django 4.2.22 on 2025-10-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_projectuser_signed_terms_and_conditions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="peoplegroup",
            name="name_ca",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="peoplegroup",
            name="name_de",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="peoplegroup",
            name="name_en",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="peoplegroup",
            name="name_es",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="peoplegroup",
            name="name_et",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="peoplegroup",
            name="name_fr",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="peoplegroup",
            name="name_nl",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="projectuser",
            name="job_ca",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="projectuser",
            name="job_de",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="projectuser",
            name="job_en",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="projectuser",
            name="job_es",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="projectuser",
            name="job_et",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="projectuser",
            name="job_fr",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="projectuser",
            name="job_nl",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
    ]
