# Generated by Django 4.0.8 on 2023-01-27 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_remove_projectuser_is_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailedProjectUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.projectuser',),
        ),
    ]
