# Generated by Django 4.0.10 on 2023-03-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_detailedprojectuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='permissions_up_to_date',
            field=models.BooleanField(default=False),
        ),
    ]
