# Generated by Django 4.0.10 on 2023-03-06 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_alter_historicallinkedproject_reason_and_more'),
        ('files', '0006_auto_20220523_1643'),
        ('accounts', '0025_group_permissions_up_to_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectuser',
            name='people_groups',
        ),
        migrations.AddField(
            model_name='peoplegroup',
            name='featured_projects',
            field=models.ManyToManyField(related_name='people_groups', to='projects.project'),
        ),
        migrations.AddField(
            model_name='peoplegroup',
            name='groups',
            field=models.ManyToManyField(related_name='people_groups', to='accounts.group'),
        ),
        migrations.AddField(
            model_name='peoplegroup',
            name='header_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people_group_header', to='files.image'),
        ),
        migrations.AddField(
            model_name='peoplegroup',
            name='logo_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people_group_logo', to='files.image'),
        ),
        migrations.AddField(
            model_name='peoplegroup',
            name='people_data',
            field=models.JSONField(default=dict),
        ),
    ]
