# Generated by Django 4.0.10 on 2023-03-10 15:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_remove_projectuser_people_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='peoplegroup',
            name='sdgs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveSmallIntegerField(choices=[(1, 'No poverty'), (2, 'Zero hunger'), (3, 'Good health and well-being'), (4, 'Quality education'), (5, 'Gender equality'), (6, 'Clean water and sanitation'), (7, 'Affordable and clean energy'), (8, 'Decent work and economic growth'), (9, 'Industry, innovation and infrastructure'), (10, 'Reduces inequalities'), (11, 'Sustainable cities and communities'), (12, 'Responsible consumption & production'), (13, 'Climate action'), (14, 'Life below water'), (15, 'Life on land'), (16, 'Peace, justice and strong institutions'), (17, 'Partnerships for the goals')], unique=True), default=list, null=True, size=17),
        ),
    ]
