# Generated by Django 4.0.10 on 2023-04-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_peoplegroup_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectuser',
            name='type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
