# Generated by Django 4.0.10 on 2023-05-03 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_projectuser_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='peoplegroup',
            name='publication_status',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('org', 'Org')], default='public', max_length=10, verbose_name='visibility'),
        ),
    ]
