# Generated by Django 4.2.1 on 2023-06-08 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0032_alter_skill_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="privacysettings",
            old_name="personal_skills",
            new_name="hobbies",
        ),
        migrations.RenameField(
            model_name="privacysettings",
            old_name="academic_skills",
            new_name="skills",
        ),
    ]
