# Generated by Django 4.2.1 on 2023-06-08 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0031_peoplegroup_is_root_and_more"),
        ("accounts", "0033_rename_personal_skills_privacysettings_hobbies"),
    ]

    operations = []
