# Generated by Django 4.2.1 on 2023-06-13 09:18

from django.db import migrations, models


def update_publication_statuses(apps, schema_editor):
    PeopleGroup = apps.get_model("accounts", "PeopleGroup")
    db_alias = schema_editor.connection.alias
    PeopleGroup.objects.using(db_alias).all().update(publication_status="org")


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0034_merge_20230608_0909"),
    ]

    operations = [
        migrations.AlterField(
            model_name="peoplegroup",
            name="publication_status",
            field=models.CharField(
                choices=[("public", "Public"), ("private", "Private"), ("org", "Org")],
                default="org",
                max_length=10,
                verbose_name="visibility",
            ),
        ),
        migrations.RunPython(update_publication_statuses, migrations.RunPython.noop),
    ]
