# Generated by Django 4.2.1 on 2023-06-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0035_alter_peoplegroup_publication_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="privacysettings",
            name="publication_status",
            field=models.CharField(
                choices=[("hide", "Hide"), ("org", "Organization"), ("pub", "Public")],
                default="org",
                max_length=4,
            ),
        ),
    ]
