# Generated by Django 4.2.3 on 2023-07-18 12:48

from django.db import migrations, models


def set_default_privacy_settings(apps, schema_editor):
    PrivacySettings = apps.get_model("accounts", "PrivacySettings")  # noqa
    PrivacySettings.objects.all().update(
        publication_status="pub",
        profile_picture="pub",
        profile="pub",
        skills="pub",
        hobbies="pub",
        mobile_phone="hide",
        personal_email="hide",
        facebook="org",
        linkedin="org",
        medium="org",
        website="org",
        skype="org",
        landline_phone="org",
        twitter="org",
    )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0036_privacysettings_publication_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="privacysettings",
            name="facebook",
            field=models.CharField(
                choices=[("hide", "Hide"), ("org", "Organization"), ("pub", "Public")],
                default="org",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="privacysettings",
            name="hobbies",
            field=models.CharField(
                choices=[("hide", "Hide"), ("org", "Organization"), ("pub", "Public")],
                default="pub",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="privacysettings",
            name="landline_phone",
            field=models.CharField(
                choices=[("hide", "Hide"), ("org", "Organization"), ("pub", "Public")],
                default="org",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="privacysettings",
            name="linkedin",
            field=models.CharField(
                choices=[("hide", "Hide"), ("org", "Organization"), ("pub", "Public")],
                default="org",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="privacysettings",
            name="medium",
            field=models.CharField(
                choices=[("hide", "Hide"), ("org", "Organization"), ("pub", "Public")],
                default="org",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="privacysettings",
            name="profile",
            field=models.CharField(
                choices=[("hide", "Hide"), ("org", "Organization"), ("pub", "Public")],
                default="pub",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="privacysettings",
            name="profile_picture",
            field=models.CharField(
                choices=[("hide", "Hide"), ("org", "Organization"), ("pub", "Public")],
                default="pub",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="privacysettings",
            name="publication_status",
            field=models.CharField(
                choices=[("hide", "Hide"), ("org", "Organization"), ("pub", "Public")],
                default="pub",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="privacysettings",
            name="skills",
            field=models.CharField(
                choices=[("hide", "Hide"), ("org", "Organization"), ("pub", "Public")],
                default="pub",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="privacysettings",
            name="skype",
            field=models.CharField(
                choices=[("hide", "Hide"), ("org", "Organization"), ("pub", "Public")],
                default="org",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="privacysettings",
            name="twitter",
            field=models.CharField(
                choices=[("hide", "Hide"), ("org", "Organization"), ("pub", "Public")],
                default="org",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="privacysettings",
            name="website",
            field=models.CharField(
                choices=[("hide", "Hide"), ("org", "Organization"), ("pub", "Public")],
                default="org",
                max_length=4,
            ),
        ),
        migrations.RunPython(set_default_privacy_settings)
    ]
