# Generated by Django 4.2.3 on 2023-07-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0037_alter_privacysettings_facebook_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="privacysettings",
            old_name="facebook",
            new_name="socials",
        ),
        migrations.RemoveField(
            model_name="privacysettings",
            name="hobbies",
        ),
        migrations.RemoveField(
            model_name="privacysettings",
            name="landline_phone",
        ),
        migrations.RemoveField(
            model_name="privacysettings",
            name="linkedin",
        ),
        migrations.RemoveField(
            model_name="privacysettings",
            name="medium",
        ),
        migrations.RemoveField(
            model_name="privacysettings",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="privacysettings",
            name="skype",
        ),
        migrations.RemoveField(
            model_name="privacysettings",
            name="twitter",
        ),
        migrations.RemoveField(
            model_name="privacysettings",
            name="website",
        ),
        migrations.AlterField(
            model_name="privacysettings",
            name="profile_picture",
            field=models.CharField(
                choices=[("hide", "Hide"), ("org", "Organization"), ("pub", "Public")],
                default="org",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="privacysettings",
            name="skills",
            field=models.CharField(
                choices=[("hide", "Hide"), ("org", "Organization"), ("pub", "Public")],
                default="hide",
                max_length=4,
            ),
        ),
    ]
