# Generated by Django 4.2.3 on 2023-08-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0039_alter_privacysettings_mobile_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="peoplegroup",
            name="short_description",
            field=models.TextField(blank=True),
        ),
    ]
