# Generated by Django 4.2.3 on 2023-07-31 13:20

import django.contrib.postgres.fields
from django.db import migrations, models


def save_old_groups(apps, schema_editor):
    ProjectUser = apps.get_model("accounts", "ProjectUser")  # noqa
    for user in ProjectUser.objects.all():
        user.groups_backup = [
            {
                "name": group.name,
                "model__app_label": group.model.app_label if group.model else None,
                "model__model": group.model.model if group.model else None,
                "object_pk": group.object_pk,
            }
            for group in user.groups.all()
        ]
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0039_alter_privacysettings_mobile_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectuser",
            name="groups_backup",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.JSONField(), default=list, size=None
            ),
        ),
        migrations.RunPython(save_old_groups, migrations.RunPython.noop),
    ]
