# Generated by Django 4.2.3 on 2023-09-01 10:10

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0040_peoplegroup_short_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectuser",
            name="birthdate",
            field=models.DateField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(
                        limit_value=datetime.date.today
                    )
                ],
            ),
        ),
    ]
