# Generated by Django 4.2.3 on 2023-09-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0041_alter_projectuser_birthdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectuser",
            name="location",
            field=models.TextField(blank=True),
        ),
    ]
