# Generated by Django 4.2.3 on 2023-07-31 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0041_remove_projectuser_permissions_delete_serviceaccount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="permissions",
        ),
    ]
