# Generated by Django 4.2.3 on 2023-09-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0042_alter_projectuser_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectuser",
            name="external_id",
            field=models.CharField(
                blank=True, help_text="id of user in their organization", max_length=255
            ),
        ),
    ]
