# Generated by Django 4.2.3 on 2023-07-31 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0042_remove_group_permissions"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Permission",
        ),
    ]
