# Generated by Django 4.2.3 on 2023-08-01 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0022_remove_project_groups"),
        ("organizations", "0025_remove_organization_groups"),
        ("accounts", "0043_delete_permission"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="peoplegroup",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="projectuser",
            name="groups",
        ),
        migrations.DeleteModel(
            name="Group",
        ),
    ]
