# Generated by Django 4.2.3 on 2023-08-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0044_remove_peoplegroup_groups_remove_projectuser_groups_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="peoplegroup",
            name="groups",
            field=models.ManyToManyField(
                related_name="people_groups", to="auth.group"
            ),
        ),
        migrations.AddField(
            model_name="projectuser",
            name="groups",
            field=models.ManyToManyField(related_name="users", to="auth.group"),
        ),
    ]
