# Generated by Django 4.2.3 on 2023-08-04 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0046_alter_projectuser_managers_projectuser_is_active_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectuser",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
    ]
