# Generated by Django 4.2.3 on 2023-08-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0047_alter_projectuser_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="peoplegroup",
            name="permissions_up_to_date",
            field=models.BooleanField(default=False),
        ),
    ]
