# Generated by Django 4.2.3 on 2023-08-09 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0048_peoplegroup_permissions_up_to_date"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DetailedProjectUser",
        ),
    ]
