# Generated by Django 4.2.3 on 2023-08-10 09:28

from django.db import migrations


def reassign_users_roles(apps, schema_editor):
    ProjectUser = apps.get_model("accounts", "ProjectUser")  # noqa
    Group = apps.get_model("auth", "Group")
    for user in ProjectUser.objects.all():
        for group_backup in user.groups_backup:
            if not group_backup["model__model"]:
                name = group_backup["name"]
            else:
                name = f"{group_backup['model__model']}:#{group_backup['object_pk']}:{group_backup['name']}"
            group, _ = Group.objects.get_or_create(name=name)
            user.groups.add(group)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0049_delete_detailedprojectuser"),
    ]

    operations = [
        migrations.RunPython(reassign_users_roles, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="projectuser",
            name="groups_backup",
        ),
    ]
