# Generated by Django 4.2.3 on 2023-09-12 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0043_projectuser_external_id"),
        ("accounts", "0050_remove_projectuser_groups_backup"),
    ]

    operations = []
