# Generated by Django 4.2.3 on 2023-09-22 14:59

from django.db import migrations, models
from django.utils.text import slugify


def generate_slug_for_existing_groups(apps, schema_editor):
    PeopleGroup = apps.get_model("accounts", "PeopleGroup")
    db_alias = schema_editor.connection.alias
    people_groups = PeopleGroup.objects.using(db_alias).filter(slug__isnull=True)
    for index, people_group in enumerate(people_groups):
        name = people_group.name
        if name == "":
            name = people_group.type or "group"
        raw_slug = slugify(name[0:46])
        slug = raw_slug
        same_slug_count = 0
        while PeopleGroup.objects.filter(slug=slug).exists():
            same_slug_count += 1
            slug = f"{raw_slug}-{same_slug_count}"
        PeopleGroup.objects.filter(pk=people_group.pk).update(slug=slug)
        print(f"{index} / {len(people_groups)}")


def generate_slug_for_existing_users(apps, schema_editor):
    ProjectUser = apps.get_model("accounts", "ProjectUser")
    db_alias = schema_editor.connection.alias
    users = ProjectUser.objects.using(db_alias).filter(slug__isnull=True)
    for index, user in enumerate(users):
        full_name = f"{user.given_name.capitalize()} {user.family_name.capitalize()}".strip()
        if full_name == "":
            full_name = user.email.split("@")[0] or "user"
        raw_slug = slugify(full_name[0:46])
        slug = raw_slug
        same_slug_count = 0
        while ProjectUser.objects.filter(slug=slug).exists():
            same_slug_count += 1
            slug = f"{raw_slug}-{same_slug_count}"
        ProjectUser.objects.filter(pk=user.pk).update(slug=slug)
        print(f"{index} / {len(users)}")


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0051_merge_20230912_0748"),
    ]

    operations = [
        migrations.AddField(
            model_name="peoplegroup",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name="projectuser",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.RunPython(generate_slug_for_existing_groups, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='peoplegroup',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.RunPython(generate_slug_for_existing_users, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='projectuser',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
