# Generated by Django 4.2.3 on 2023-10-13 15:42

from django.db import migrations, models


def set_existing_users_show_message_to_false(apps, schema_editor):
    ProjectUser = apps.get_model("accounts", "ProjectUser")  # noqa
    ProjectUser.objects.filter(last_login__isnull=False).update(show_welcome=False)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0052_peoplegroup_slug_projectuser_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectuser",
            name="show_welcome",
            field=models.BooleanField(default=True),
        ),
        migrations.RunPython(set_existing_users_show_message_to_false, migrations.RunPython.noop)
    ]
