# Generated by Django 4.2.7 on 2023-12-05 14:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0053_projectuser_show_welcome"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectuser",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
