# Generated by Django 4.2.7 on 2023-12-06 13:11

from django.db import migrations, models


def migrate_show_welcome(apps, schema_editor):
    ProjectUser = apps.get_model("accounts", "ProjectUser")
    for user in ProjectUser.objects.all():
        user.onboarding_status = {
            "show_welcome": user.show_welcome,
        }
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0054_projectuser_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectuser",
            name="onboarding_status",
            field=models.JSONField(default=dict),
        ),
        migrations.RunPython(migrate_show_welcome, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="projectuser",
            name="show_welcome",
        ),
    ]
