# Generated by Django 4.2.7 on 2023-12-11 15:28

import apps.accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0055_remove_projectuser_show_welcome_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectuser",
            name="onboarding_status",
            field=models.JSONField(
                default=apps.accounts.utils.default_onboarding_status
            ),
        ),
    ]
