# Generated by Django 4.2.7 on 2023-12-06 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0055_remove_projectuser_show_welcome_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectuser",
            name="email",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
