# Generated by Django 4.2.7 on 2023-12-06 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def migrate_privacy_settings(apps, schema_editor):
    PrivacySettings = apps.get_model("accounts", "PrivacySettings")
    for privacy_settings in PrivacySettings.objects.all():
        privacy_settings._user = privacy_settings.user
        privacy_settings.save()


def migrate_privacy_settings_reverse(apps, schema_editor):
    PrivacySettings = apps.get_model("accounts", "PrivacySettings")
    for privacy_settings in PrivacySettings.objects.all():
        privacy_settings.user = privacy_settings._user
        privacy_settings.save()

class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0056_alter_projectuser_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="privacysettings",
            name="_user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_privacy_settings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(migrate_privacy_settings, migrate_privacy_settings_reverse),
        migrations.RemoveField(
            model_name="privacysettings",
            name="user",
        ),
        migrations.RenameField(
            model_name="privacysettings",
            old_name="_user",
            new_name="user",
        ),
        migrations.AlterField(
            model_name="privacysettings",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="privacy_settings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
