# Generated by Django 4.2.7 on 2023-12-06 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0057_privacysettings__user"),
        ("keycloak", "0001_initial"),
        ("feedbacks", "0008_comment__author_follow__follower_and_more"),
        ("files", "0012_image__owner"),
        ("notifications", "0027_notificationsettings__user"),
        ("google", "0004_googleaccount__user"),
        ("projects", "0028_alter_projectmember_unique_together_and_more"),

    ]

    operations = [
        migrations.RemoveField(
            model_name="projectuser",
            name="keycloak_id",
        ),
    ]
