# Generated by Django 4.2.7 on 2023-12-06 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0057_privacysettings__user"),
        ("keycloak", "0001_initial")
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectuser",
            name="keycloak_id",
        ),
    ]
