# Generated by Django 4.2.7 on 2023-12-12 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0056_alter_projectuser_onboarding_status"),
        ("accounts", "0058_remove_projectuser_keycloak_id"),
    ]

    operations = []
