FROM quay.io/keycloak/keycloak:24.0.2

COPY keycloak/realm-export.json /opt/keycloak/data/import/realm-export.json

HEALTHCHECK --interval=10s --timeout=5s --start-period=15s --retries=10 CMD ["curl", "http://127.0.0.1:8001/realms/lp/.well-known/openid-configuration"]
CMD ["start-dev", "--import-realm"]
