services:
  postgres:
    image: pgvector/pgvector:pg14
    user: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_EXTENSIONS=pg_trgm, unaccent
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: quay.io/minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    entrypoint:
      - /usr/bin/bash
      - -c
    command:
      # Create the bucket projects before starting minio
      - mkdir -p /data/projects && minio server --console-address :9001 /data
    volumes:
      - s3:/data

  redis:
    image: redis:6.2-bullseye
    command:
      # Enable persistence
      - redis-server
      - --save
      - "60"
      - "1"
      - --loglevel
      - warning
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  mjml:
    image: danihodovic/mjml-server
    ports:
      - 15500:15500

  projects:
    container_name: projects
    build:
      context: .
      args:
        EXPORT_FLAG: --dev
    env_file:
      - .env
    user: root
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      - postgres
      - keycloak
    environment:
      DJANGO_SETTINGS_MODULE: projects.settings.local
    volumes:
      - .:/app

  celery:
    build: .
    env_file:
      - .env
    command: celery -A projects worker -B -l info
    restart: always
    depends_on:
      - projects
      - redis
    environment:
      DJANGO_SETTINGS_MODULE: projects.settings.local

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025

  keycloak:
    build:
      context: .
      dockerfile: Dockerfile.keycloak
    ports:
      - 8001:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    healthcheck:
      test: ["CMD", "curl", "-LIsSfo", "/dev/null", "http://127.0.0.1:8080/realms/lp/.well-known/openid-configuration"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  postgres-data:
  s3:
  redis:
