# Generated by Django 4.2.7 on 2023-12-06 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from keycloak import KeycloakGetError

from services.keycloak.interface import KeycloakService


def create_keycloak_accounts(apps, schema_editor):
    ProjectUser = apps.get_model("accounts", "ProjectUser")
    KeycloakAccount = apps.get_model("keycloak", "KeycloakAccount")
    for user in ProjectUser.objects.all():
        try:
            remote_keycloak_account = KeycloakService.get_user(user.keycloak_id)
        except KeycloakGetError:
            continue
        KeycloakAccount.objects.update_or_create(
            user=user,
            keycloak_id=remote_keycloak_account["id"],
            defaults={
                "username": remote_keycloak_account["username"],
                "email": remote_keycloak_account.get("email", ""),
            },
        )
            


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KeycloakAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "keycloak_id",
                    models.UUIDField(help_text="id of user in keycloak", unique=True),
                ),
                ("username", models.CharField(max_length=255, unique=True)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keycloak_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RunPython(create_keycloak_accounts, migrations.RunPython.noop),
    ]
