# Generated by Django 4.2.7 on 2023-12-06 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from keycloak import KeycloakGetError

from services.keycloak.interface import KeycloakService


def create_keycloak_accounts(apps, schema_editor):
    ProjectUser = apps.get_model("accounts", "ProjectUser")
    KeycloakAccount = apps.get_model("keycloak", "KeycloakAccount")
    keycloak_users = KeycloakService.get_users()
    keycloak_users = {user["id"]: user for user in keycloak_users}
    for user in ProjectUser.objects.all():
        if user.keycloak_id in keycloak_users.keys():
            keycloak_user = keycloak_users[user.keycloak_id]
            KeycloakAccount.objects.update_or_create(
                user=user,
                keycloak_id=keycloak_user["id"],
                defaults={
                    "username": keycloak_user["username"],
                    "email": keycloak_user.get("email", "")
                },
            )
            


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KeycloakAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "keycloak_id",
                    models.UUIDField(help_text="id of user in keycloak", unique=True),
                ),
                ("username", models.CharField(max_length=255, unique=True)),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keycloak_account",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RunPython(create_keycloak_accounts, migrations.RunPython.noop),
    ]
