# Generated by Django 4.2.10 on 2024-03-11 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0002_initial"),
        ("keycloak", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdentityProvider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alias", models.CharField(max_length=255, unique=True)),
                ("enabled", models.BooleanField(default=False)),
                (
                    "logo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="identity_provider_logo",
                        to="files.image",
                    ),
                ),
            ],
        ),
    ]
