# Generated by Django 4.2.22 on 2025-09-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedbacks", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="content_ca",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="content_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="content_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="content_et",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="content_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="content_nl",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalcomment",
            name="content_ca",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalcomment",
            name="content_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalcomment",
            name="content_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalcomment",
            name="content_et",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalcomment",
            name="content_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalcomment",
            name="content_nl",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="description_ca",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="description_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="description_et",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="description_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="description_nl",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="title_ca",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="title_de",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="title_en",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="title_et",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="title_fr",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="title_nl",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
