# Generated by Django 4.2.22 on 2025-09-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedbacks", "0003_comment_content_ca_comment_content_de_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="content_detected_language",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="historicalcomment",
            name="content_detected_language",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="description_detected_language",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="title_detected_language",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
