# Generated by Django 4.0.5 on 2022-06-24 15:37

from django.db import migrations
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_projectmember_user'),
        ('feedbacks', '0004_alter_comment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='project',
            field=simple_history.models.HistoricForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='historicalcomment',
            name='project',
            field=simple_history.models.HistoricForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='projects.project'),
        ),
    ]
