# Generated by Django 4.2.22 on 2025-10-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedbacks", "0005_comment_content_es_historicalcomment_content_es_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="title_ca",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="title_de",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="title_en",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="title_es",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="title_et",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="title_fr",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="title_nl",
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
