# Generated by Django 4.0.5 on 2022-06-28 09:53
from bs4 import BeautifulSoup
from django.db import migrations, models


def update_comment_images_storage(apps, schema_editor):
    comments = apps.get_model("feedbacks", "Comment")
    images = apps.get_model("files", "Image")
    db_alias = schema_editor.connection.alias
    for comment in comments.objects.using(db_alias).all():
        project = comment.project
        text = comment.content
        soup = BeautifulSoup(text, features="html.parser")
        images_tags = soup.findAll("img")
        for image_tag in images_tags:
            image_url = image_tag["src"]
            if image_url.startswith("/v1"):
                image_id = (
                    image_url.split("/")[-1]
                    if image_url[-1] != "/"
                    else image_url.split("/")[-2]
                )
                image = images.objects.get(id=image_id)
                comment.images.add(image)
                project.images.remove(image)
                text = text.replace(
                    f"/v1/project/{project.id}/image/{image.id}",
                    f"/v1/project/{project.id}/comment-image/{image.id}"
                )
        comments.objects.using(db_alias).filter(id=comment.id).update(content=text)


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_update_images_urls'),
        ('feedbacks', '0005_alter_comment_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='images',
            field=models.ManyToManyField(related_name='comments', to='files.image'),
        ),
        migrations.RunPython(update_comment_images_storage, migrations.RunPython.noop),
    ]
