# Generated by Django 4.2.22 on 2025-09-29 16:05

import apps.commons.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("title", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("na", "Not applicable"),
                            ("participant", "Participant"),
                            ("job", "Job"),
                            ("traineeship", "Traineeship"),
                        ],
                        default="na",
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("closed", "Closed")],
                        default="open",
                        max_length=12,
                    ),
                ),
                ("deadline", models.DateField(null=True)),
                ("is_remunerated", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title_en", models.CharField(blank=True, max_length=100, null=True)),
                ("title_fr", models.CharField(blank=True, max_length=100, null=True)),
                ("title_de", models.CharField(blank=True, max_length=100, null=True)),
                ("title_nl", models.CharField(blank=True, max_length=100, null=True)),
                ("title_et", models.CharField(blank=True, max_length=100, null=True)),
                ("title_ca", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "title_detected_language",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("title_es", models.CharField(blank=True, max_length=100, null=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                ("description_fr", models.TextField(blank=True, null=True)),
                ("description_de", models.TextField(blank=True, null=True)),
                ("description_nl", models.TextField(blank=True, null=True)),
                ("description_et", models.TextField(blank=True, null=True)),
                ("description_ca", models.TextField(blank=True, null=True)),
                (
                    "description_detected_language",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("description_es", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=(
                apps.commons.mixins.ProjectRelated,
                apps.commons.mixins.DuplicableModel,
                models.Model,
            ),
        ),
    ]
