# Generated by Django 4.2.7 on 2024-01-05 17:16

import apps.commons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("title", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("na", "Not applicable"),
                            ("participant", "Participant"),
                            ("job", "Job"),
                            ("traineeship", "Traineeship"),
                        ],
                        default="na",
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("open", "Open"), ("closed", "Closed")],
                        default="open",
                        max_length=12,
                    ),
                ),
                ("deadline", models.DateField(null=True)),
                ("is_remunerated", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            bases=(
                models.Model,
                apps.commons.models.ProjectRelated,
                apps.commons.models.OrganizationRelated,
            ),
        ),
    ]
