# Generated by Django 4.0.8 on 2023-01-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_announcement_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='is_remunerated',
            field=models.BooleanField(default=False),
        ),
    ]
