# Generated by Django 4.2.22 on 2025-07-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="description_ca",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="announcement",
            name="description_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="announcement",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="announcement",
            name="description_et",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="announcement",
            name="description_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="announcement",
            name="description_nl",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="announcement",
            name="title_ca",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="announcement",
            name="title_de",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="announcement",
            name="title_en",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="announcement",
            name="title_et",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="announcement",
            name="title_fr",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="announcement",
            name="title_nl",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
