# Generated by Django 4.2.22 on 2025-09-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0004_announcement_description_detected_language_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="description_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="announcement",
            name="title_es",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
