# Generated by Django 4.2.7 on 2024-01-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(blank=True, default="", max_length=255)),
                (
                    "subject_en",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "subject_fr",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("content", models.TextField(blank=True, default="")),
                ("content_en", models.TextField(blank=True, default="", null=True)),
                ("content_fr", models.TextField(blank=True, default="", null=True)),
                (
                    "send_to",
                    models.CharField(
                        choices=[("primary", "Primary"), ("personal", "Personal")],
                        default="primary",
                        max_length=8,
                    ),
                ),
                (
                    "template",
                    models.CharField(
                        choices=[
                            ("email_with_name", "With Name"),
                            ("email_without_name", "Without Name"),
                        ],
                        default="email_with_name",
                        max_length=18,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
