# Generated by Django 4.2.3 on 2023-08-06 20:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("files", "0010_alter_image_left_alter_image_natural_ratio_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(blank=True, default="", max_length=255)),
                (
                    "subject_en",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "subject_fr",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("content", models.TextField(blank=True, default="")),
                ("content_en", models.TextField(blank=True, default="", null=True)),
                ("content_fr", models.TextField(blank=True, default="", null=True)),
                (
                    "send_to",
                    models.CharField(
                        choices=[("primary", "Primary"), ("personal", "Personal")],
                        default="primary",
                        max_length=8,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "images",
                    models.ManyToManyField(
                        blank=True, related_name="emails", to="files.image"
                    ),
                ),
                (
                    "recipients",
                    models.ManyToManyField(
                        blank=True, related_name="+", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "sent_to",
                    models.ManyToManyField(
                        blank=True, related_name="+", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
