# Generated by Django 4.2.3 on 2023-08-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emailing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="template",
            field=models.CharField(
                choices=[
                    ("email_with_name", "With Name"),
                    ("email_without_name", "Without Name"),
                ],
                default="email_with_name",
                max_length=18,
            ),
        ),
    ]
