# Generated by Django 4.2.22 on 2025-09-29 16:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("emailing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("files", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="images",
            field=models.ManyToManyField(
                blank=True, related_name="emails", to="files.image"
            ),
        ),
        migrations.AddField(
            model_name="email",
            name="recipients",
            field=models.ManyToManyField(
                blank=True, related_name="+", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="email",
            name="sent_to",
            field=models.ManyToManyField(
                blank=True, related_name="+", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
