# Generated by Django 4.2.20 on 2025-04-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emailing", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="content_de",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="email",
            name="subject_de",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
