# Generated by Django 4.2.20 on 2025-06-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emailing", "0003_email_content_de_email_subject_de"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="content_ca",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="email",
            name="content_et",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="email",
            name="content_nl",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="email",
            name="subject_ca",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="email",
            name="subject_et",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="email",
            name="subject_nl",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
