# Generated by Django 4.2.22 on 2025-09-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "emailing",
            "0004_email_content_ca_email_content_et_email_content_nl_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="content_es",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="email",
            name="subject_es",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
