# Generated by Django 3.2.13 on 2022-05-06 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_remove_organization_main_org_logo_background_color'),
        ('projects', '0004_rename_tag_historicalproject_tags_wikipediatag'),
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='WikipediaTag',
        ),
    ]
