# Generated by Django 4.2.7 on 2024-01-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("misc", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wikipediatag",
            name="description",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="wikipediatag",
            name="description_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="wikipediatag",
            name="description_fr",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
