# Generated by Django 4.2.17 on 2025-01-21 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0010_remove_project_organization_tags_and_more"),
        ("accounts", "0012_delete_skill"),
        ("organizations", "0018_remove_organization_wikipedia_tags_and_more"),
        ("misc", "0003_wikipediatag_description_wikipediatag_description_en_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="organization",
        ),
        migrations.DeleteModel(
            name="WikipediaTag",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
