# Generated by Django 4.0.8 on 2023-02-15 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0024_template_language'),
        ('projects', '0019_alter_historicallinkedproject_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MixpanelEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mixpanel_id', models.CharField(max_length=255, unique=True)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mixpanel_events', to='projects.project')),
            ],
        ),
    ]
