# Generated by Django 4.2.25 on 2025-11-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MixpanelEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("mixpanel_id", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
