# Generated by Django 4.2.25 on 2025-11-18 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        ("mixpanel", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mixpanelevent",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.organization",
            ),
        ),
    ]
