# Generated by Django 4.0.8 on 2023-02-15 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mixpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mixpanelevent',
            options={'ordering': ['-date']},
        ),
    ]
