# Generated by Django 4.2.22 on 2025-09-29 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("mixpanel", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mixpanelevent",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mixpanel_events",
                to="projects.project",
            ),
        ),
    ]
