# Generated by Django 4.2.22 on 2025-09-29 16:05

import apps.commons.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("announcements", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("content", models.TextField(blank=True, default="")),
                ("event_date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("visible_by_all", models.BooleanField(default=False)),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="title"
                    ),
                ),
                (
                    "title_fr",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="title"
                    ),
                ),
                (
                    "title_de",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="title"
                    ),
                ),
                (
                    "title_nl",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="title"
                    ),
                ),
                (
                    "title_et",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="title"
                    ),
                ),
                (
                    "title_ca",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="title"
                    ),
                ),
                (
                    "title_detected_language",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "title_es",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="title"
                    ),
                ),
                ("content_en", models.TextField(blank=True, default="", null=True)),
                ("content_fr", models.TextField(blank=True, default="", null=True)),
                ("content_de", models.TextField(blank=True, default="", null=True)),
                ("content_nl", models.TextField(blank=True, default="", null=True)),
                ("content_et", models.TextField(blank=True, default="", null=True)),
                ("content_ca", models.TextField(blank=True, default="", null=True)),
                (
                    "content_detected_language",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("content_es", models.TextField(blank=True, default="", null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=(apps.commons.mixins.OrganizationRelated, models.Model),
        ),
        migrations.CreateModel(
            name="Instruction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("content", models.TextField(blank=True, default="")),
                ("publication_date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("fr", "Français"),
                            ("de", "Deutsch"),
                            ("nl", "Dutch"),
                            ("et", "Estonian"),
                            ("ca", "Catalan"),
                            ("es", "Español"),
                        ],
                        default="en",
                        max_length=2,
                    ),
                ),
                ("has_to_be_notified", models.BooleanField(default=False)),
                ("notified", models.BooleanField(default=False)),
                ("visible_by_all", models.BooleanField(default=False)),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="title"
                    ),
                ),
                (
                    "title_fr",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="title"
                    ),
                ),
                (
                    "title_de",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="title"
                    ),
                ),
                (
                    "title_nl",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="title"
                    ),
                ),
                (
                    "title_et",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="title"
                    ),
                ),
                (
                    "title_ca",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="title"
                    ),
                ),
                (
                    "title_detected_language",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "title_es",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="title"
                    ),
                ),
                ("content_en", models.TextField(blank=True, default="", null=True)),
                ("content_fr", models.TextField(blank=True, default="", null=True)),
                ("content_de", models.TextField(blank=True, default="", null=True)),
                ("content_nl", models.TextField(blank=True, default="", null=True)),
                ("content_et", models.TextField(blank=True, default="", null=True)),
                ("content_ca", models.TextField(blank=True, default="", null=True)),
                (
                    "content_detected_language",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("content_es", models.TextField(blank=True, default="", null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=(
                apps.commons.mixins.OrganizationRelated,
                apps.commons.mixins.HasOwner,
                models.Model,
            ),
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("content", models.TextField(blank=True, default="")),
                ("publication_date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("fr", "Français"),
                            ("de", "Deutsch"),
                            ("nl", "Dutch"),
                            ("et", "Estonian"),
                            ("ca", "Catalan"),
                            ("es", "Español"),
                        ],
                        default="en",
                        max_length=2,
                    ),
                ),
                ("visible_by_all", models.BooleanField(default=False)),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="title"
                    ),
                ),
                (
                    "title_fr",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="title"
                    ),
                ),
                (
                    "title_de",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="title"
                    ),
                ),
                (
                    "title_nl",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="title"
                    ),
                ),
                (
                    "title_et",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="title"
                    ),
                ),
                (
                    "title_ca",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="title"
                    ),
                ),
                (
                    "title_detected_language",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "title_es",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="title"
                    ),
                ),
                ("content_en", models.TextField(blank=True, default="", null=True)),
                ("content_fr", models.TextField(blank=True, default="", null=True)),
                ("content_de", models.TextField(blank=True, default="", null=True)),
                ("content_nl", models.TextField(blank=True, default="", null=True)),
                ("content_et", models.TextField(blank=True, default="", null=True)),
                ("content_ca", models.TextField(blank=True, default="", null=True)),
                (
                    "content_detected_language",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("content_es", models.TextField(blank=True, default="", null=True)),
            ],
            options={
                "abstract": False,
            },
            bases=(apps.commons.mixins.OrganizationRelated, models.Model),
        ),
        migrations.CreateModel(
            name="Newsfeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("project", "Project"),
                            ("announcement", "Announcement"),
                            ("news", "News"),
                        ],
                        default="project",
                        max_length=50,
                    ),
                ),
                (
                    "announcement",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="newsfeed_announcement",
                        to="announcements.announcement",
                    ),
                ),
                (
                    "news",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="newsfeed_news",
                        to="newsfeed.news",
                    ),
                ),
            ],
        ),
    ]
