# Generated by Django 4.2.10 on 2024-03-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("announcements", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Newsfeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "announcements",
                    models.ManyToManyField(
                        related_name="newsfeed", to="announcements.announcement"
                    ),
                ),
                (
                    "projects",
                    models.ManyToManyField(
                        related_name="newsfeed", to="projects.project"
                    ),
                ),
            ],
        ),
    ]
