# Generated by Django 4.2.10 on 2024-03-14 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("announcements", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Newsfeed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("project", "Project"),
                            ("announcement", "Announcement"),
                        ],
                        default="project",
                        max_length=50,
                    ),
                ),
                (
                    "announcement",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="newsfeed_announcement",
                        to="announcements.announcement",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="newsfeed_project",
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
