# Generated by Django 4.2.11 on 2024-03-27 16:28

import apps.commons.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0002_initial"),
        ("accounts", "0004_remove_peoplegroup_type"),
        ("organizations", "0004_alter_organization_options"),
        ("newsfeed", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("content", models.TextField(blank=True, default="")),
                ("publication_date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "language",
                    models.CharField(
                        choices=[("fr", "French"), ("en", "English")],
                        default="en",
                        max_length=2,
                    ),
                ),
                (
                    "header_image",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="news_header",
                        to="files.image",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news",
                        to="organizations.organization",
                    ),
                ),
                (
                    "people_groups",
                    models.ManyToManyField(
                        related_name="news", to="accounts.peoplegroup"
                    ),
                ),
            ],
            bases=(models.Model, apps.commons.models.OrganizationRelated),
        ),
    ]
