# Generated by Django 4.2.25 on 2025-11-18 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("files", "0003_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0002_initial"),
        ("accounts", "0001_initial"),
        ("newsfeed", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsfeed",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="newsfeed_project",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="header_image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="news_header",
                to="files.image",
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="images",
            field=models.ManyToManyField(related_name="news", to="files.image"),
        ),
        migrations.AddField(
            model_name="news",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="news",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="people_groups",
            field=models.ManyToManyField(
                related_name="news", to="accounts.peoplegroup"
            ),
        ),
        migrations.AddField(
            model_name="instruction",
            name="images",
            field=models.ManyToManyField(related_name="instructions", to="files.image"),
        ),
        migrations.AddField(
            model_name="instruction",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="instructions",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="instruction",
            name="owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="owned_instructions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="instruction",
            name="people_groups",
            field=models.ManyToManyField(
                blank=True, related_name="instructions", to="accounts.peoplegroup"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="images",
            field=models.ManyToManyField(related_name="events", to="files.image"),
        ),
        migrations.AddField(
            model_name="event",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="people_groups",
            field=models.ManyToManyField(
                related_name="events", to="accounts.peoplegroup"
            ),
        ),
    ]
