# Generated by Django 4.2.10 on 2024-03-07 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        ("announcements", "0002_initial"),
        ("newsfeed", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newsfeed",
            name="announcements",
        ),
        migrations.RemoveField(
            model_name="newsfeed",
            name="projects",
        ),
        migrations.AddField(
            model_name="newsfeed",
            name="announcement",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="newsfeed_announcement",
                to="announcements.announcement",
            ),
        ),
        migrations.AddField(
            model_name="newsfeed",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="newsfeed_project",
                to="projects.project",
            ),
        ),
        migrations.AddField(
            model_name="newsfeed",
            name="type",
            field=models.CharField(
                choices=[("project", "Project"), ("announcement", "Announcement")],
                default="project",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="newsfeed",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
