# Generated by Django 4.2.11 on 2024-04-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsfeed", "0002_instruction"),
    ]

    operations = [
        migrations.AddField(
            model_name="instruction",
            name="notified",
            field=models.BooleanField(default=False),
        ),
    ]
