# Generated by Django 4.2.10 on 2024-04-08 09:03

import apps.commons.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0005_alter_organization_options"),
        ("accounts", "0004_remove_peoplegroup_type"),
        ("newsfeed", "0002_news"),
    ]

    operations = [
        migrations.CreateModel(
            name="Instruction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("content", models.TextField(blank=True, default="")),
                ("publication_date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "language",
                    models.CharField(
                        choices=[("fr", "French"), ("en", "English")],
                        default="en",
                        max_length=2,
                    ),
                ),
                ("has_to_be_notified", models.BooleanField(default=False)),
                ("notified", models.BooleanField(default=False)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instructions",
                        to="organizations.organization",
                    ),
                ),
                (
                    "people_groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="instructions",
                        to="accounts.peoplegroup",
                    ),
                ),
            ],
            bases=(models.Model, apps.commons.models.OrganizationRelated),
        ),
    ]
