# Generated by Django 4.2.11 on 2024-04-04 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_peoplegroup_type"),
        ("newsfeed", "0003_instruction_notified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instruction",
            name="people_groups",
            field=models.ManyToManyField(
                blank=True, related_name="instructions", to="accounts.peoplegroup"
            ),
        ),
    ]
