# Generated by Django 4.2.11 on 2024-04-18 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("newsfeed", "0004_instruction"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsfeed",
            name="news",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="newsfeed_news",
                to="newsfeed.news",
            ),
        ),
        migrations.AlterField(
            model_name="newsfeed",
            name="type",
            field=models.CharField(
                choices=[
                    ("project", "Project"),
                    ("announcement", "Announcement"),
                    ("news", "News"),
                ],
                default="project",
                max_length=50,
            ),
        ),
    ]
