# Generated by Django 4.2.11 on 2024-04-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsfeed", "0005_newsfeed_news_alter_newsfeed_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="visible_by_all",
            field=models.BooleanField(default=False),
        ),
    ]
