# Generated by Django 4.2.11 on 2024-04-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsfeed", "0006_news_visible_by_all"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="visible_by_all",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="instruction",
            name="visible_by_all",
            field=models.BooleanField(default=False),
        ),
    ]
