# Generated by Django 4.2.14 on 2024-08-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0002_initial"),
        ("newsfeed", "0007_event_visible_by_all_instruction_visible_by_all"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="images",
            field=models.ManyToManyField(related_name="events", to="files.image"),
        ),
        migrations.AddField(
            model_name="instruction",
            name="images",
            field=models.ManyToManyField(related_name="instructions", to="files.image"),
        ),
        migrations.AddField(
            model_name="news",
            name="images",
            field=models.ManyToManyField(related_name="news", to="files.image"),
        ),
    ]
