# Generated by Django 4.2.20 on 2025-04-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsfeed", "0008_event_images_instruction_images_news_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instruction",
            name="language",
            field=models.CharField(
                choices=[("fr", "French"), ("en", "English"), ("de", "German")],
                default="en",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="language",
            field=models.CharField(
                choices=[("fr", "French"), ("en", "English"), ("de", "German")],
                default="en",
                max_length=2,
            ),
        ),
    ]
