# Generated by Django 4.2.20 on 2025-04-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsfeed", "0009_alter_instruction_language_alter_news_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instruction",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("fr", "Français"), ("de", "Deutsch")],
                default="en",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("fr", "Français"), ("de", "Deutsch")],
                default="en",
                max_length=2,
            ),
        ),
    ]
