# Generated by Django 4.2.22 on 2025-07-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsfeed", "0011_alter_instruction_language_alter_news_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="content_ca",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="content_de",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="content_en",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="content_et",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="content_fr",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="content_nl",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="title_ca",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="title"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="title_de",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="title"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="title_en",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="title"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="title_et",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="title"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="title_fr",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="title"
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="title_nl",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="title"
            ),
        ),
        migrations.AddField(
            model_name="instruction",
            name="content_ca",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="instruction",
            name="content_de",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="instruction",
            name="content_en",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="instruction",
            name="content_et",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="instruction",
            name="content_fr",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="instruction",
            name="content_nl",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="instruction",
            name="title_ca",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="title"
            ),
        ),
        migrations.AddField(
            model_name="instruction",
            name="title_de",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="title"
            ),
        ),
        migrations.AddField(
            model_name="instruction",
            name="title_en",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="title"
            ),
        ),
        migrations.AddField(
            model_name="instruction",
            name="title_et",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="title"
            ),
        ),
        migrations.AddField(
            model_name="instruction",
            name="title_fr",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="title"
            ),
        ),
        migrations.AddField(
            model_name="instruction",
            name="title_nl",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="title"
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="content_ca",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="content_de",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="content_en",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="content_et",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="content_fr",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="content_nl",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="title_ca",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="title"
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="title_de",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="title"
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="title_en",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="title"
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="title_et",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="title"
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="title_fr",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="title"
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="title_nl",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="title"
            ),
        ),
    ]
