# Generated by Django 4.2.22 on 2025-09-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "newsfeed",
            "0012_event_content_ca_event_content_de_event_content_en_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="content_detected_language",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="title_detected_language",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="instruction",
            name="content_detected_language",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="instruction",
            name="title_detected_language",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="content_detected_language",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="title_detected_language",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
