# Generated by Django 4.2.22 on 2025-09-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsfeed", "0013_event_content_detected_language_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="content_es",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="title_es",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="title"
            ),
        ),
        migrations.AddField(
            model_name="instruction",
            name="content_es",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="instruction",
            name="title_es",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="title"
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="content_es",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="news",
            name="title_es",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="title"
            ),
        ),
        migrations.AlterField(
            model_name="instruction",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("fr", "Français"),
                    ("de", "Deutsch"),
                    ("nl", "Dutch"),
                    ("et", "Estonian"),
                    ("ca", "Catalan"),
                    ("es", "Español"),
                ],
                default="en",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("fr", "Français"),
                    ("de", "Deutsch"),
                    ("nl", "Dutch"),
                    ("et", "Estonian"),
                    ("ca", "Catalan"),
                    ("es", "Español"),
                ],
                default="en",
                max_length=2,
            ),
        ),
    ]
