# Generated by Django 4.2.22 on 2025-10-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsfeed", "0014_event_content_es_event_title_es_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="title_ca",
            field=models.CharField(
                blank=True, max_length=1020, null=True, verbose_name="title"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="title_de",
            field=models.CharField(
                blank=True, max_length=1020, null=True, verbose_name="title"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="title_en",
            field=models.CharField(
                blank=True, max_length=1020, null=True, verbose_name="title"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="title_es",
            field=models.CharField(
                blank=True, max_length=1020, null=True, verbose_name="title"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="title_et",
            field=models.CharField(
                blank=True, max_length=1020, null=True, verbose_name="title"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="title_fr",
            field=models.CharField(
                blank=True, max_length=1020, null=True, verbose_name="title"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="title_nl",
            field=models.CharField(
                blank=True, max_length=1020, null=True, verbose_name="title"
            ),
        ),
        migrations.AlterField(
            model_name="instruction",
            name="title_ca",
            field=models.CharField(
                blank=True, max_length=1020, null=True, verbose_name="title"
            ),
        ),
        migrations.AlterField(
            model_name="instruction",
            name="title_de",
            field=models.CharField(
                blank=True, max_length=1020, null=True, verbose_name="title"
            ),
        ),
        migrations.AlterField(
            model_name="instruction",
            name="title_en",
            field=models.CharField(
                blank=True, max_length=1020, null=True, verbose_name="title"
            ),
        ),
        migrations.AlterField(
            model_name="instruction",
            name="title_es",
            field=models.CharField(
                blank=True, max_length=1020, null=True, verbose_name="title"
            ),
        ),
        migrations.AlterField(
            model_name="instruction",
            name="title_et",
            field=models.CharField(
                blank=True, max_length=1020, null=True, verbose_name="title"
            ),
        ),
        migrations.AlterField(
            model_name="instruction",
            name="title_fr",
            field=models.CharField(
                blank=True, max_length=1020, null=True, verbose_name="title"
            ),
        ),
        migrations.AlterField(
            model_name="instruction",
            name="title_nl",
            field=models.CharField(
                blank=True, max_length=1020, null=True, verbose_name="title"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="title_ca",
            field=models.CharField(
                blank=True, max_length=1020, null=True, verbose_name="title"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="title_de",
            field=models.CharField(
                blank=True, max_length=1020, null=True, verbose_name="title"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="title_en",
            field=models.CharField(
                blank=True, max_length=1020, null=True, verbose_name="title"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="title_es",
            field=models.CharField(
                blank=True, max_length=1020, null=True, verbose_name="title"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="title_et",
            field=models.CharField(
                blank=True, max_length=1020, null=True, verbose_name="title"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="title_fr",
            field=models.CharField(
                blank=True, max_length=1020, null=True, verbose_name="title"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="title_nl",
            field=models.CharField(
                blank=True, max_length=1020, null=True, verbose_name="title"
            ),
        ),
    ]
