# Generated by Django 4.2.14 on 2024-09-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchobject",
            name="last_update",
            field=models.DateTimeField(null=True),
        ),
    ]
