# Generated by Django 4.2.22 on 2025-07-01 12:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0017_alter_blogentry_options"),
        ("accounts", "0019_merge_20250613_1133"),
        ("search", "0002_searchobject_last_update"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="searchobject",
            unique_together={("type", "user", "project", "people_group")},
        ),
    ]
