corsAllowedDomains:
- e2e.projects.k8s.lp-i.dev
- e2e-meta.projects.k8s.lp-i.dev
- lpi-dev.cloud-iam.com # keycloak login page

config:
  nonSensitive:
    AZURE_ACCOUNT_NAME: criparisdevlabprojects
    POSTGRES_DB: dev_projects_e2e
    KEYCLOAK_REALM: e2e

workflow:
  lifecycle:
    enabled: true
    config:
      nonSensitive:
        ORIGIN_POSTGRES_DB: dev_projects

hostname: api-e2e.projects.k8s.lp-i.dev

backend:
  replicaCount: 1

instance: e2e

redis:
  autoSync: false
  valueFiles:
  - values.yaml
  - projects-api/values.yaml
  - projects-api/dev-lab/values.yaml
  argocdAppName: projects-backend-e2e-redis
  helmReleaseName: projects-backend-e2e-redis
