corsAllowedDomains:
- e2e.projects.k8s.lp-i.dev
- e2e-meta.projects.k8s.lp-i.dev
- lpi-dev.cloud-iam.com # keycloak login page

config:
  nonSensitive:
    AZURE_ACCOUNT_NAME: criparisdevlabprojects
    POSTGRES_DB: dev_projects_e2e
    KEYCLOAK_REALM: e2e
    KEYCLOAK_CLIENT_ID=projects-backend
    KEYCLOAK_CLIENT_SECRET=qVZxuldH9J7ggJXNGo0rSwpKI9jzv16y
    KEYCLOAK_PUBLIC_KEY=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoqKT4wfb7HoHnKD5W7E+mqLn8c+HwPooc7yS5BDOUqxIaHV41OkylEAodz9WDC3tu8Ik2KLS1Uv/cY2fJ3Z44Czc/dWC5dviPrbUuWgH41t9HiivzOlBlkc8PvZHP/DEGQCmAutzAyB6UnkUJRBJ7wKR8U6rMvp6YlD4YxsFC9bR0xEkZ0FbhAqj+FXQVyp9ghPt9P22QFoTu+SntZSe297AYPFmpvyfsAO/RIWBYpY++xAAqqz17eSXyRgHtQAkECS53UhHOV5JoayfSIbAY2dZpvbPOxRaLOmGnlAiYxxFPmkgyafKbUZ/2H7vn7sFYB+cTgg1IFN1KL8OK7NJ5wIDAQAB

workflow:
  lifecycle:
    enabled: true
    config:
      nonSensitive:
        ORIGIN_POSTGRES_DB: dev_projects

hostname: api-e2e.projects.k8s.lp-i.dev

backend:
  replicaCount: 1

instance: e2e

redis:
  autoSync: false
  valueFiles:
  - values.yaml
  - projects-api/values.yaml
  - projects-api/dev-lab/values.yaml
  argocdAppName: projects-backend-e2e-redis
  helmReleaseName: projects-backend-e2e-redis
