# Generated by Django 5.2.10 on 2026-01-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commons", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupdata",
            name="role",
            field=models.CharField(
                choices=[
                    ("superadmins", "Superadmins"),
                    ("default", "Default"),
                    ("reviewers", "Reviewers"),
                    ("owners", "Owners"),
                    ("reviewer_groups", "Reviewer Groups"),
                    ("owner_groups", "Owner Groups"),
                    ("member_groups", "Member Groups"),
                    ("leaders", "Leaders"),
                    ("managers", "Managers"),
                    ("members", "Members"),
                    ("admins", "Admins"),
                    ("facilitators", "Facilitators"),
                    ("users", "Users"),
                    ("viewers", "Viewers"),
                ],
                max_length=255,
            ),
        ),
    ]
