# Generated by Django 4.2.18 on 2025-02-28 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("commons", "0002_pgvector"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.CharField(max_length=255, null=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("superadmins", "Superadmins"),
                            ("default", "Default"),
                            ("reviewers", "Reviewers"),
                            ("owners", "Owners"),
                            ("reviewer_groups", "Reviewer Groups"),
                            ("owner_groups", "Owner Groups"),
                            ("member_groups", "Member Groups"),
                            ("leaders", "Leaders"),
                            ("managers", "Managers"),
                            ("members", "Members"),
                            ("admins", "Admins"),
                            ("facilitators", "Facilitators"),
                            ("users", "Users"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data",
                        to="auth.group",
                    ),
                ),
            ],
        ),
    ]
