# Generated by Django 4.2.25 on 2025-10-08 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("commons", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupdata",
            name="group",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data",
                to="auth.group",
            ),
        ),
    ]
