corsAllowedDomains:
- projects.k8s.lp-i.xyz
- id.lp-i.xyz # keycloak login page

config:
  nonSensitive:
    DJANGO_SETTINGS_MODULE: projects.settings.staging
    AZURE_ACCOUNT_NAME: criparisdevlabprojects
    AZURE_CONTAINER: staging-projects
    POSTGRES_DB: staging_projects
    POSTGRES_HOST: dev-lab-projects-backend.postgres.database.azure.com
    EMAIL_HOST_USER: projects@mg.lp-i.xyz
    ALGOLIA_APP_ID: 0NMNSXPWQS
    KEYCLOAK_SERVER_URL: https://id.lp-i.xyz/auth/
    KEYCLOAK_PUBLIC_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqFiz3sDRg81xWLM/CZD0sV7m89CzQO4cKd2k++/QDim7ttDI7U/ZgQc2qLni6wrmK0wZqxURy4VEI2xemqoU2Y8ju+ZL4A6jirmt9lIhlq3FTWHd6U98qi8QpcQJy3CxoLD3aXCELU6LnzuLpr5KKA+bDXrjVTb90udT0MU/RWBrZ8jiZSIgs9uhIYHbejItwMvVE+iBmsDObN1gvRi57obpWR+nLc+F6xifuQjPQgU7ibR1lIY/wp8Gr+oxfM5ERMgrjjjSAQa+4TL4qkSWRsTrAGdNUyCWDq0Vii3EgvGr1+W9FycmL+7x7wO+vBbUSFMaNuSXnT5+xiTEk1f10QIDAQAB
    MJML_HTTPSERVER_URL: http://mjml-server.stag-test-mjml/v1/render
    ENVIRONMENT: staging

projectsNamespace: stag-test-projects

hostname: api.projects.k8s.lp-i.xyz

backend:
  replicaCount: 1


redis:
  autoSync: false
  valueFiles:
  - values.yaml
  - projects-api/values.yaml
  - projects-api/stag-test/values.yaml
  argocdAppName: stag-test-projects-api-redis
  helmReleaseName: projects-api-redis-stag-test
