corsAllowedDomains:
- projets.app
- learningplanetinstitute.org
- projects.directory
- learning-planet.org
- profschercheurs.org
- keycloak.k8s.lp-i.org # keycloak login page (in-cluster test)
- id.learningplanetinstitute.org # keycloak login page
- edusynergy.provest-cove.eu
- dice.bioconvs.org

config:
  nonSensitive:
    DJANGO_SETTINGS_MODULE: projects.settings.production
    AZURE_ACCOUNT_NAME: criparisprodprodprojects
    AZURE_TRANSLATOR_REGION: francecentral
    AZURE_TRANSLATOR_ENDPOINT: https://projects-translation-prod.cognitiveservices.azure.com
    POSTGRES_HOST: prod-prod-projects-backend.postgres.database.azure.com
    EMAIL_HOST_USER: projects@learningplanetinstitute.org
    EMAIL_BACKEND: django.core.mail.backends.smtp.EmailBackend
    EMAIL_HOST: smtp.eu.mailgun.org
    EMAIL_PORT: "465"
    EMAIL_USE_SSL: "True"
    KEYCLOAK_SERVER_URL: https://id.learningplanetinstitute.org/
    ENVIRONMENT: production
    EMAIL_CONTACT_SENDER: contact.projects@learningplanetinstitute.org
    EMAIL_REPORT_SENDER: contact.projects@learningplanetinstitute.org
    EMAIL_CONTACT_RECIPIENTS: helpdesk@oto-technology.fr
    EMAIL_REPORT_RECIPIENTS: helpdesk@oto-technology.fr

hostname: api.projects.lp-i.org

backend:
  replicaCount: 9

workflow:
  backups:
    storageContainerName: projects-backups
    enabled: true # Todo: Enable me after testing
    backup:
      cron:
        enabled: true
    checkPresence:
      cron:
        enabled: true

redis:
  valueFiles:
  - values.yaml
  - projects-api/values.yaml
  - projects-api/prod-prod/values.yaml
  cascadeDelete: false
