corsAllowedDomains:
- projects.k8s.lp-i.dev
- lpi-dev.cloud-iam.com # keycloak login page
- keycloak-test.k8s.lp-i.dev # keycloak login page (in-cluster test)
- keycloak.k8s.lp-i.dev # keycloak login page (in-cluster)
- localhost:8080

config:
  nonSensitive:
    DJANGO_SETTINGS_MODULE: projects.settings.develop
    AZURE_ACCOUNT_NAME: criparisdevlabprojects
    AZURE_TRANSLATOR_REGION: francecentral
    AZURE_TRANSLATOR_ENDPOINT: https://projects-translation.cognitiveservices.azure.com
    POSTGRES_HOST: dev-lab-projects-backend.postgres.database.azure.com
    KEYCLOAK_SERVER_URL: https://keycloak.k8s.lp-i.dev/
    KEYCLOAK_PUBLIC_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoqKT4wfb7HoHnKD5W7E+mqLn8c+HwPooc7yS5BDOUqxIaHV41OkylEAodz9WDC3tu8Ik2KLS1Uv/cY2fJ3Z44Czc/dWC5dviPrbUuWgH41t9HiivzOlBlkc8PvZHP/DEGQCmAutzAyB6UnkUJRBJ7wKR8U6rMvp6YlD4YxsFC9bR0xEkZ0FbhAqj+FXQVyp9ghPt9P22QFoTu+SntZSe297AYPFmpvyfsAO/RIWBYpY++xAAqqz17eSXyRgHtQAkECS53UhHOV5JoayfSIbAY2dZpvbPOxRaLOmGnlAiYxxFPmkgyafKbUZ/2H7vn7sFYB+cTgg1IFN1KL8OK7NJ5wIDAQAB
    POSTGRES_DB: dev_projects
    ENVIRONMENT: dev
    DEBUG: "False"
    FORCE_CLEAN_DB_CACHE: "True"
    FORCE_GARBAGE_COLLECT: "True"

workflow:
  lifecycle:
    enabled: true
    config:
      nonSensitive:
        ORIGIN_POSTGRES_DB: dev_projects
  backups:
    storageContainerName: projects-backups-test

hostname: api.projects.k8s.lp-i.dev

backend:
  horizontalScaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 2

redis:
  autoSync: false
  valueFiles:
  - values.yaml
  - projects-api/values.yaml
  - projects-api/dev-lab/values.yaml
  values:
    redis:
      commonLabels:
        sablier.enable: '{{.Values.sablier.enabled}}'
        sablier.group: '{{.Values.sablier.groupName}}'

sablier:
  enabled: true

ingressMiddlewares:
- traefik-ip-allow-list-with-office@kubernetescrd
- sablier-projects-common-sablier@kubernetescrd
