environment:
  nonSensitive:
    DJANGO_SETTINGS_MODULE: projects.settings.staging
    ALLOWED_HOSTS: api.projects.k8s.lp-i.xyz,projects-backend,projects.k8s.lp-i.xyz,cri.projects.k8s.lp-i.xyz,profschercheurs.projects.k8s.lp-i.xyz,new-design-system.k8s.lp-i.xyz,www.new-design-system.k8s.lp-i.xyz,cri.new-design-system.k8s.lp-i.xyz,www.cri.new-design-system.k8s.lp-i.xyz,profschercheurs.new-design-system.k8s.lp-i.xyz,www.profschercheurs.new-design-system.k8s.lp-i.xyz,api.projects.k8s.lp-i.xyz,projects.k8s.lp-i.xyz,cri.projects.k8s.lp-i.xyz,profschercheurs.projects.k8s.lp-i.xyz,monespace.profschercheurs.org,www.monespace.profschercheurs.org
    AZURE_ACCOUNT_NAME: criparisdevlabprojects
    AZURE_CUSTOM_DOMAIN: assets.projects.k8s.lp-i.xyz
    AZURE_CONTAINER: staging-projects
    POSTGRES_DB: staging_projects
    POSTGRES_HOST: dev-lab-projects-backend.postgres.database.azure.com
    EMAIL_HOST_USER: projects@mg.lp-i.xyz
    PUBLIC_URL: api.projects.k8s.lp-i.xyz
    ALGOLIA_APP_ID: 0NMNSXPWQS
    KEYCLOAK_SERVER_URL: https://id.lp-i.xyz/auth/
    KEYCLOAK_PUBLIC_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqFiz3sDRg81xWLM/CZD0sV7m89CzQO4cKd2k++/QDim7ttDI7U/ZgQc2qLni6wrmK0wZqxURy4VEI2xemqoU2Y8ju+ZL4A6jirmt9lIhlq3FTWHd6U98qi8QpcQJy3CxoLD3aXCELU6LnzuLpr5KKA+bDXrjVTb90udT0MU/RWBrZ8jiZSIgs9uhIYHbejItwMvVE+iBmsDObN1gvRi57obpWR+nLc+F6xifuQjPQgU7ibR1lIY/wp8Gr+oxfM5ERMgrjjjSAQa+4TL4qkSWRsTrAGdNUyCWDq0Vii3EgvGr1+W9FycmL+7x7wO+vBbUSFMaNuSXnT5+xiTEk1f10QIDAQAB
    CELERY_BROKER_URL: redis://projects-api-redis-stag-test-master:6379/0
    CELERY_RESULT_BACKEND: redis://projects-api-redis-stag-test-master:6379/0
    CACHE_REDIS_URL: redis://projects-api-redis-stag-test-master:6379/1
    MJML_HTTPSERVER_URL: http://mjml-server.stag-test-mjml/v1/render
    WIKIPEDIA_GATEWAY_URL: http://wikipedia-gateway.stag-test-wikipedia-gateway
    ENVIRONMENT: staging

projectsNamespace: stag-test-projects

hostname: api.projects.k8s.lp-i.xyz

backend:
  replicaCount: 1

redisAllowedLabel: projects-api-redis-stag-test-client # Required for network policy

redis:
  autoSync: true
  valueFiles:
  - values.yaml
  - projects-api/values.yaml
  - projects-api/stag-test/values.yaml
  - secrets://projects-api/stag-test/secrets.yaml
  argocdAppName: stag-test-projects-api-redis
  argocdProject: stag-test
  helmReleaseName: projects-api-redis-stag-test
