corsAllowedDomains:
- projects.k8s.lp-i.xyz
- id.lp-i.xyz # keycloak login page

config:
  nonSensitive:
    DJANGO_SETTINGS_MODULE: projects.settings.staging
    AZURE_ACCOUNT_NAME: criparisdevlabprojects
    AZURE_CONTAINER: staging-projects
    POSTGRES_DB: staging_projects
    POSTGRES_HOST: dev-lab-projects-backend.postgres.database.azure.com
    EMAIL_HOST_USER: projects@mg.lp-i.xyz
    KEYCLOAK_SERVER_URL: https://keycloak.k8s.lp-i.dev/
    KEYCLOAK_PUBLIC_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhmgO2vMFDfpb1fgHrrzUqKdIqkPWhCCopZQmcqdSTEA/hvcjYatzeT1fFHWJGHQ8LbuSF+JZgzMX76yBVsrHq3we4chJ/l0sg8Kv0PXTbDeVsPOsEQewQrJDN/HW+Zk2WbSAfyRkS6q7UI1gBOFyNx8qDP9L9878dFsjh0duL2lCp2HGeOgZ41sdPc3SSwmaF9uxpmViEcDSGHYzhtXZLSh2t5FEviznRanxnQG/LuXr5lluqN2AQGrXuycAOnH2Jsdnqht+5pAu2BkcYjeYmwteA8eq9xCaPapiG8ulYgQR9hUeWqwT4EpFM8tbVoZI7XqbrEdi4PX/zl1DIjHf5QIDAQAB
    KEYCLOAK_REALM: lp-staging
    MJML_HTTPSERVER_URL: http://mjml-server.stag-test-mjml/v1/render
    ENVIRONMENT: staging

hostname: api.projects.k8s.lp-i.xyz

backend:
  replicaCount: 1


redis:
  autoSync: false
  valueFiles:
  - values.yaml
  - projects-api/values.yaml
  - projects-api/stag-test/values.yaml
  argocdAppName: stag-test-projects-api-redis
  helmReleaseName: projects-api-redis-stag-test
