corsAllowedDomains:
- projects.k8s.lp-i.dev

config:
  nonSensitive:
    DJANGO_SETTINGS_MODULE: projects.settings.develop
    AZURE_ACCOUNT_NAME: criparisdevlabprojects
    AZURE_CUSTOM_DOMAIN: assets.projects.k8s.lp-i.dev
    POSTGRES_HOST: dev-lab-projects-backend.postgres.database.azure.com
    ALGOLIA_APP_ID: YCCI8BEZKN
    KEYCLOAK_SERVER_URL: https://id.lp-i.dev/auth/
    KEYCLOAK_PUBLIC_KEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoqKT4wfb7HoHnKD5W7E+mqLn8c+HwPooc7yS5BDOUqxIaHV41OkylEAodz9WDC3tu8Ik2KLS1Uv/cY2fJ3Z44Czc/dWC5dviPrbUuWgH41t9HiivzOlBlkc8PvZHP/DEGQCmAutzAyB6UnkUJRBJ7wKR8U6rMvp6YlD4YxsFC9bR0xEkZ0FbhAqj+FXQVyp9ghPt9P22QFoTu+SntZSe297AYPFmpvyfsAO/RIWBYpY++xAAqqz17eSXyRgHtQAkECS53UhHOV5JoayfSIbAY2dZpvbPOxRaLOmGnlAiYxxFPmkgyafKbUZ/2H7vn7sFYB+cTgg1IFN1KL8OK7NJ5wIDAQAB
    POSTGRES_DB: dev_projects
    ENVIRONMENT: dev

workflow:
  lifecycle:
    enabled: true
    config:
      nonSensitive:
        ORIGIN_POSTGRES_DB: dev_projects
  backups:
    storageContainerName: projects-backups-test

celery:
  metrics:
      enabled: true
      portNumber: 9808
      image:
        repository: danihodovic
        path: celery-exporter
        tag: "0.10.2"
      brokerUrlIsSecret: true
hostname: api.projects.k8s.lp-i.dev

backend:
  replicaCount: 1

redis:
  # autoSync: true
  autoSync: false
  valueFiles:
  - values.yaml
  - projects-api/values.yaml
  - projects-api/dev-lab/values.yaml
  - secrets://projects-api/dev-lab/secrets.yaml
