# Generated by Django 4.2.15 on 2024-09-19 09:23

import apps.commons.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("misc", "0003_wikipediatag_description_wikipediatag_description_en_and_more"),
        ("esco", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("skill", "Skill"), ("hobby", "Hobby")],
                        default="skill",
                        max_length=8,
                    ),
                ),
                ("esco_skill_distance", models.FloatField()),
                ("esco_occupation_distance", models.FloatField()),
                ("level", models.SmallIntegerField()),
                ("level_to_reach", models.SmallIntegerField()),
                ("category", models.CharField(blank=True, default="", max_length=255)),
                ("can_mentor", models.BooleanField(default=False)),
                ("needs_mentor", models.BooleanField(default=False)),
                ("comment", models.TextField(blank=True, default="")),
                (
                    "esco_occupation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills_v2",
                        to="esco.escooccupation",
                    ),
                ),
                (
                    "esco_skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills_v2",
                        to="esco.escoskill",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills_v2",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wikipedia_tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills_v2",
                        to="misc.wikipediatag",
                    ),
                ),
            ],
            bases=(models.Model, apps.commons.models.HasOwner),
        ),
    ]
