# Generated by Django 4.2.16 on 2024-11-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tagclassification",
            name="description",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="tagclassification",
            name="title",
            field=models.CharField(max_length=50),
        ),
    ]
