# Generated by Django 4.2.16 on 2024-12-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0002_alter_tagclassification_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="type",
            field=models.CharField(
                choices=[
                    ("Wikipedia", "Wikipedia"),
                    ("ESCO", "Esco"),
                    ("Custom", "Custom"),
                ],
                default="Custom",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="tagclassification",
            name="type",
            field=models.CharField(
                choices=[
                    ("Wikipedia", "Wikipedia"),
                    ("ESCO", "Esco"),
                    ("Custom", "Custom"),
                ],
                default="Custom",
                max_length=255,
            ),
        ),
    ]
