# Generated by Django 4.2.17 on 2025-01-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0005_mentoring_created_at_mentoring_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="alternative_titles",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="alternative_titles_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="alternative_titles_fr",
            field=models.TextField(blank=True, null=True),
        ),
    ]
