# Generated by Django 4.2.20 on 2025-04-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0008_tagclassification_outdated_slugs"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="alternative_titles_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="description_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="title_de",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
