# Generated by Django 4.2.20 on 2025-06-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0009_tag_alternative_titles_de_tag_description_de_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="alternative_titles_ca",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="alternative_titles_et",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="alternative_titles_nl",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="description_ca",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="description_et",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="description_nl",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="title_ca",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="title_et",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="title_nl",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
