# Generated by Django 4.2.22 on 2025-07-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0010_tag_alternative_titles_ca_tag_alternative_titles_et_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentoringmessage",
            name="content_ca",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mentoringmessage",
            name="content_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mentoringmessage",
            name="content_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mentoringmessage",
            name="content_et",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mentoringmessage",
            name="content_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mentoringmessage",
            name="content_nl",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tagclassification",
            name="description_ca",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="tagclassification",
            name="description_de",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="tagclassification",
            name="description_en",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="tagclassification",
            name="description_et",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="tagclassification",
            name="description_fr",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="tagclassification",
            name="description_nl",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="tagclassification",
            name="title_ca",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="tagclassification",
            name="title_de",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="tagclassification",
            name="title_en",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="tagclassification",
            name="title_et",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="tagclassification",
            name="title_fr",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="tagclassification",
            name="title_nl",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
