# Generated by Django 4.2.22 on 2025-09-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0012_mentoringmessage_content_ca_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentoringmessage",
            name="content_detected_language",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="tagclassification",
            name="description_detected_language",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="tagclassification",
            name="title_detected_language",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
