# Generated by Django 4.2.22 on 2025-09-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0013_mentoringmessage_content_detected_language_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mentoringmessage",
            name="content_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="alternative_titles_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="description_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="title_es",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="tagclassification",
            name="description_es",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="tagclassification",
            name="title_es",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
