# Generated by Django 4.2.1 on 2023-06-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PostDeployProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("finished", "Finished"),
                            ("failed", "Failed"),
                        ],
                        default="finished",
                        max_length=10,
                    ),
                ),
                ("last_run", models.DateTimeField(default=None, null=True)),
                ("error", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Post deploy process",
                "verbose_name_plural": "Post deploy processes",
                "ordering": ["-status", "-last_run"],
            },
        ),
    ]
