# Generated by Django 4.2.7 on 2024-01-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PostDeployProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_name", models.CharField(max_length=100, unique=True)),
                ("priority", models.IntegerField(default=99)),
                ("task_id", models.CharField(blank=True, default="", max_length=100)),
            ],
            options={
                "verbose_name": "Post deploy process",
                "verbose_name_plural": "Post deploy processes",
                "ordering": ["priority"],
            },
        ),
    ]
