# Generated by Django 4.2.16 on 2024-11-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deploys", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="postdeployprocess",
            name="_status",
            field=models.CharField(
                choices=[
                    ("SUCCESS", "Success"),
                    ("FAILURE", "Failure"),
                    ("PENDING", "Pending"),
                    ("", "None"),
                ],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="postdeployprocess",
            name="last_run",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="postdeployprocess",
            name="last_run_version",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
