# Generated by Django 4.2.1 on 2023-06-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deploys", "0002_alter_postdeployprocess_error"),
    ]

    operations = [
        migrations.AddField(
            model_name="postdeployprocess",
            name="priority",
            field=models.IntegerField(default=99),
        ),
    ]
