# Generated by Django 4.2.3 on 2023-09-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deploys", "0003_postdeployprocess_priority"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="postdeployprocess",
            options={
                "ordering": ["priority"],
                "verbose_name": "Post deploy process",
                "verbose_name_plural": "Post deploy processes",
            },
        ),
        migrations.RemoveField(
            model_name="postdeployprocess",
            name="error",
        ),
        migrations.RemoveField(
            model_name="postdeployprocess",
            name="last_run",
        ),
        migrations.RemoveField(
            model_name="postdeployprocess",
            name="status",
        ),
        migrations.AddField(
            model_name="postdeployprocess",
            name="task_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
