# Generated by Django 4.2.14 on 2024-09-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EscoUpdateError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_type", models.CharField(max_length=255)),
                ("item_id", models.CharField(max_length=255)),
                ("error", models.CharField(max_length=255)),
                ("traceback", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="EscoSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uri", models.URLField(max_length=2048, unique=True)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("title_en", models.CharField(blank=True, max_length=255, null=True)),
                ("title_fr", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                ("description_fr", models.TextField(blank=True, null=True)),
                (
                    "essential_skills",
                    models.ManyToManyField(
                        blank=True,
                        related_name="essential_for_skills",
                        to="esco.escoskill",
                    ),
                ),
                (
                    "optional_skills",
                    models.ManyToManyField(
                        blank=True,
                        related_name="optional_for_skills",
                        to="esco.escoskill",
                    ),
                ),
                ("parents", models.ManyToManyField(blank=True, to="esco.escoskill")),
            ],
        ),
        migrations.CreateModel(
            name="EscoOccupation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uri", models.URLField(max_length=2048, unique=True)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("title_en", models.CharField(blank=True, max_length=255, null=True)),
                ("title_fr", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                ("description_fr", models.TextField(blank=True, null=True)),
                (
                    "essential_skills",
                    models.ManyToManyField(
                        blank=True,
                        related_name="essential_for_occupations",
                        to="esco.escoskill",
                    ),
                ),
                (
                    "optional_skills",
                    models.ManyToManyField(
                        blank=True,
                        related_name="optional_for_occupations",
                        to="esco.escoskill",
                    ),
                ),
                (
                    "parents",
                    models.ManyToManyField(blank=True, to="esco.escooccupation"),
                ),
            ],
        ),
    ]
