# Generated by Django 4.2.22 on 2025-10-06 10:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Identifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "harvester",
                    models.CharField(
                        choices=[
                            ("hal", "Hal"),
                            ("scanr", "Scanr"),
                            ("openalex", "Openalex"),
                            ("idref", "Idref"),
                            ("scopus", "Scopus"),
                            ("orcid", "Orcid"),
                            ("local", "Local"),
                        ],
                        max_length=50,
                    ),
                ),
                ("value", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Researcher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "crisalid_uid",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "identifiers",
                    models.ManyToManyField(
                        related_name="researchers", to="crisalid.identifier"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="researcher",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "crisalid_uid",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                ("title", models.TextField()),
                ("publication_date", models.DateField(null=True)),
                (
                    "publication_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Audiovisual Document", "Audiovisual Document"),
                            ("Blog Post", "Blog Post"),
                            ("Book", "Book"),
                            ("Book Review", "Book Review"),
                            ("Chapter", "Chapter"),
                            ("Conference Output", "Conference Output"),
                            ("Conference Paper", "Conference Paper"),
                            ("Conference Poster", "Conference Poster"),
                            ("Data Management Plan", "Data Management Plan"),
                            ("Data Paper", "Data Paper"),
                            ("Dataset", "Dataset"),
                            ("Reference Book", "Dictionary"),
                            ("Document", "Document"),
                            ("Editorial", "Editorial"),
                            ("Erratum", "Erratum"),
                            ("Grant", "Grant"),
                            ("Image", "Image"),
                            ("Lecture", "Lecture"),
                            ("Letter", "Letter"),
                            ("Manual", "Manual"),
                            ("Map", "Map"),
                            ("Master Thesis", "Master Thesis"),
                            ("Metadata Document", "Metadata Document"),
                            ("Note", "Note"),
                            ("Other", "Other"),
                            ("Patent", "Patent"),
                            ("Peer review", "Peer Review"),
                            ("Preprint", "Preprint"),
                            ("Proceedings", "Proceedings"),
                            ("Report", "Report"),
                            ("Research Report", "Research Report"),
                            ("Review Paper", "Review"),
                            ("Review Article", "Review Article"),
                            ("Software", "Software"),
                            ("Standard", "Standard"),
                            ("Still Image", "Still Image"),
                            ("Technical Report", "Technical Report"),
                            ("Thesis", "Thesis"),
                            ("Working Paper", "Working Paper"),
                            ("Unknown", "Unknown"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "authors",
                    models.ManyToManyField(
                        related_name="publications", to="crisalid.researcher"
                    ),
                ),
                (
                    "identifiers",
                    models.ManyToManyField(
                        related_name="publications", to="crisalid.identifier"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="identifier",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("harvester"),
                django.db.models.functions.text.Lower("value"),
                name="unique_harvester",
            ),
        ),
        migrations.AddConstraint(
            model_name="researcher",
            constraint=models.UniqueConstraint(
                models.F("crisalid_uid"), name="crisalid_researcher_unique_crisalid_uid"
            ),
        ),
        migrations.AddConstraint(
            model_name="publication",
            constraint=models.UniqueConstraint(
                models.F("crisalid_uid"),
                name="crisalid_publication_unique_crisalid_uid",
            ),
        ),
    ]
