# Generated by Django 4.2.22 on 2025-06-23 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CrisalidId",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_type",
                    models.CharField(
                        choices=[("ORCID", "Orcid"), ("CRISALID", "Crisalid")],
                        max_length=50,
                    ),
                ),
                ("value", models.CharField(max_length=255)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "unique_together": {("content_type", "id_type", "value")},
            },
        ),
        migrations.CreateModel(
            name="ResearchDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("THESIS", "Thesis"),
                            ("BOOK", "Book"),
                            ("REPORT", "Report"),
                            ("ARTICLE", "Article"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("link", models.URLField(blank=True, null=True)),
                ("publication_date", models.DateField(blank=True, null=True)),
                (
                    "crisalid_ids",
                    models.ManyToManyField(blank=True, to="crisalid.crisalidid"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ResearchEmployment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "crisalid_ids",
                    models.ManyToManyField(blank=True, to="crisalid.crisalidid"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Researcher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "crisalid_ids",
                    models.ManyToManyField(blank=True, to="crisalid.crisalidid"),
                ),
                (
                    "documents",
                    models.ManyToManyField(
                        blank=True,
                        related_name="authors",
                        to="crisalid.researchdocument",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ResearchInstitution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "crisalid_ids",
                    models.ManyToManyField(blank=True, to="crisalid.crisalidid"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ResearchTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "crisalid_ids",
                    models.ManyToManyField(blank=True, to="crisalid.crisalidid"),
                ),
                (
                    "institutions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="teams",
                        to="crisalid.researchinstitution",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ResearchMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "crisalid_ids",
                    models.ManyToManyField(blank=True, to="crisalid.crisalidid"),
                ),
                (
                    "researcher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crisalid.researcher",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="crisalid.researchteam",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="researcher",
            name="employments",
            field=models.ManyToManyField(
                blank=True,
                related_name="researchers",
                through="crisalid.ResearchEmployment",
                to="crisalid.researchinstitution",
            ),
        ),
        migrations.AddField(
            model_name="researcher",
            name="memberships",
            field=models.ManyToManyField(
                blank=True,
                related_name="researchers",
                through="crisalid.ResearchMembership",
                to="crisalid.researchteam",
            ),
        ),
        migrations.AddField(
            model_name="researcher",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="researchers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="researchemployment",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="crisalid.researchinstitution",
            ),
        ),
        migrations.AddField(
            model_name="researchemployment",
            name="researcher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="crisalid.researcher"
            ),
        ),
    ]
