# Generated by Django 4.2.22 on 2025-09-30 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("crisalid", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crisalid_id", models.UUIDField(blank=True, null=True)),
                ("title", models.CharField(max_length=255)),
                ("publication_date", models.DateField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DocumentSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("Audiovisual Document", "Audiovisual Document"),
                            ("Blog Post", "Blog Post"),
                            ("Book", "Book"),
                            ("Book Review", "Book Review"),
                            ("Chapter", "Chapter"),
                            ("Conference Output", "Conference Output"),
                            ("Conference Paper", "Conference Paper"),
                            ("Conference Poster", "Conference Poster"),
                            ("Data Management Plan", "Data Management Plan"),
                            ("Data Paper", "Data Paper"),
                            ("Dataset", "Dataset"),
                            ("Reference Book", "Dictionary"),
                            ("Document", "Document"),
                            ("Editorial", "Editorial"),
                            ("Erratum", "Erratum"),
                            ("Grant", "Grant"),
                            ("Image", "Image"),
                            ("Lecture", "Lecture"),
                            ("Letter", "Letter"),
                            ("Manual", "Manual"),
                            ("Map", "Map"),
                            ("Master Thesis", "Master Thesis"),
                            ("Metadata Document", "Metadata Document"),
                            ("Note", "Note"),
                            ("Other", "Other"),
                            ("Patent", "Patent"),
                            ("Peer review", "Peer Review"),
                            ("Preprint", "Preprint"),
                            ("Proceedings", "Proceedings"),
                            ("Report", "Report"),
                            ("Research Report", "Research Report"),
                            ("Review Paper", "Review"),
                            ("Review Article", "Review Article"),
                            ("Software", "Software"),
                            ("Standard", "Standard"),
                            ("Still Image", "Still Image"),
                            ("Technical Report", "Technical Report"),
                            ("Thesis", "Thesis"),
                            ("Working Paper", "Working Paper"),
                            ("Unknown", "Unknown"),
                        ],
                        max_length=50,
                    ),
                ),
                ("value", models.TextField()),
                (
                    "harvester",
                    models.CharField(
                        choices=[
                            ("HAL", "Hal"),
                            ("ScanR", "Scanr"),
                            ("OpenAlex", "Openalex"),
                            ("Idref", "Idref"),
                            ("Scopus", "Scopus"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="harvesters",
                        to="crisalid.document",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResearchIdentifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crisalid_id", models.UUIDField(blank=True, null=True)),
                (
                    "id_type",
                    models.CharField(
                        choices=[("orcid", "Orcid"), ("open_halex", "Open Alex")],
                        max_length=50,
                    ),
                ),
                ("value", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="researchdocument",
            name="crisalid_ids",
        ),
        migrations.RemoveField(
            model_name="researchemployment",
            name="crisalid_ids",
        ),
        migrations.RemoveField(
            model_name="researchemployment",
            name="institution",
        ),
        migrations.RemoveField(
            model_name="researchemployment",
            name="researcher",
        ),
        migrations.RemoveField(
            model_name="researchinstitution",
            name="crisalid_ids",
        ),
        migrations.RemoveField(
            model_name="researchmembership",
            name="crisalid_ids",
        ),
        migrations.RemoveField(
            model_name="researchmembership",
            name="researcher",
        ),
        migrations.RemoveField(
            model_name="researchmembership",
            name="team",
        ),
        migrations.RemoveField(
            model_name="researchteam",
            name="crisalid_ids",
        ),
        migrations.RemoveField(
            model_name="researchteam",
            name="institutions",
        ),
        migrations.RemoveField(
            model_name="researcher",
            name="crisalid_ids",
        ),
        migrations.RemoveField(
            model_name="researcher",
            name="documents",
        ),
        migrations.RemoveField(
            model_name="researcher",
            name="employments",
        ),
        migrations.RemoveField(
            model_name="researcher",
            name="memberships",
        ),
        migrations.AddField(
            model_name="researcher",
            name="crisalid_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="researcher",
            name="display_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="researcher",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="researcher",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="CrisalidId",
        ),
        migrations.DeleteModel(
            name="ResearchDocument",
        ),
        migrations.DeleteModel(
            name="ResearchEmployment",
        ),
        migrations.DeleteModel(
            name="ResearchInstitution",
        ),
        migrations.DeleteModel(
            name="ResearchMembership",
        ),
        migrations.DeleteModel(
            name="ResearchTeam",
        ),
        migrations.AddField(
            model_name="researchidentifier",
            name="researcher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="identifiers",
                to="crisalid.researcher",
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="authors",
            field=models.ManyToManyField(
                related_name="documents", to="crisalid.researcher"
            ),
        ),
        migrations.AddConstraint(
            model_name="researchidentifier",
            constraint=models.UniqueConstraint(
                models.F("id_type"),
                models.F("researcher"),
                name="unique_researcher_harvester",
            ),
        ),
        migrations.AddConstraint(
            model_name="documentsource",
            constraint=models.UniqueConstraint(
                models.F("harvester"),
                models.F("document"),
                models.F("document_type"),
                name="unique_document_harvester",
            ),
        ),
    ]
