# Generated by Django 4.2.25 on 2025-11-27 10:37

import apps.commons.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_initial"),
        ("crisalid", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrisalidConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "crisalidbus_host",
                    models.URLField(help_text="crisalidbus/rabimqt host"),
                ),
                (
                    "crisalidbus_username",
                    models.CharField(
                        help_text="crisalidbus/rabimqt username", max_length=255
                    ),
                ),
                (
                    "crisalidbus_password",
                    models.CharField(
                        help_text="crisalidbus/rabimqt password", max_length=255
                    ),
                ),
                ("apollo_host", models.URLField(help_text="apollo/graphql host")),
                (
                    "apollo_token",
                    models.CharField(help_text="apollo token", max_length=255),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=False, help_text="config is enabled/disabled"
                    ),
                ),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crisalid",
                        to="organizations.organization",
                    ),
                ),
            ],
            bases=(apps.commons.mixins.OrganizationRelated, models.Model),
        ),
    ]
