# Generated by Django 4.2.25 on 2025-11-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crisalid", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="description_ca",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="description_de",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="description_detected_language",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="description_en",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="description_es",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="description_et",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="description_fr",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="description_nl",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="title_ca",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="title_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="title_detected_language",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="title_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="title_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="title_et",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="title_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="document",
            name="title_nl",
            field=models.TextField(blank=True, null=True),
        ),
    ]
