# Generated by Django 4.2.25 on 2025-12-02 11:52

import apps.commons.mixins
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


def prepare_display_name(apps, schema_editor):
    """split display name to given_name/familly_name"""
    Researcher = apps.get_model("crisalid", "Researcher")
    db_alias = schema_editor.connection.alias

    to_update = []
    for research in Researcher.objects.using(db_alias).all():
        given_name, family_name = "", ""
        splitter = research.display_name.split(" ", 1)
        if len(splitter) >= 1:
            given_name = splitter[0]
        if len(splitter) >= 2:
            family_name = " ".join(splitter[1:])

        research.given_name = given_name
        research.family_name = family_name
        to_update.append(research)

    Researcher.objects.using(db_alias).bulk_update(
        to_update, fields=("given_name", "family_name")
    )


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_initial"),
        ("crisalid", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrisalidConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "crisalidbus_url",
                    models.CharField(
                        help_text="crisalidbus/rabimqt host:port", max_length=255
                    ),
                ),
                (
                    "crisalidbus_username",
                    models.CharField(
                        help_text="crisalidbus/rabimqt username", max_length=255
                    ),
                ),
                (
                    "crisalidbus_password",
                    models.CharField(
                        help_text="crisalidbus/rabimqt password", max_length=255
                    ),
                ),
                (
                    "apollo_url",
                    models.CharField(
                        help_text="apollo/graphql host:port/graphql", max_length=255
                    ),
                ),
                (
                    "apollo_token",
                    models.CharField(help_text="apollo token", max_length=255),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=False, help_text="config is enabled/disabled"
                    ),
                ),
            ],
            bases=(apps.commons.mixins.OrganizationRelated, models.Model),
        ),
        migrations.RemoveConstraint(
            model_name="document",
            name="crisalid_document_unique_crisalid_uid",
        ),
        migrations.RemoveConstraint(
            model_name="identifier",
            name="unique_harvester",
        ),
        migrations.RemoveConstraint(
            model_name="researcher",
            name="crisalid_researcher_unique_crisalid_uid",
        ),
        migrations.RemoveField(
            model_name="document",
            name="crisalid_uid",
        ),
        migrations.RemoveField(
            model_name="researcher",
            name="crisalid_uid",
        ),
        migrations.AddField(
            model_name="document",
            name="updated",
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
        migrations.AddField(
            model_name="researcher",
            name="family_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="researcher",
            name="given_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(prepare_display_name),
        migrations.RemoveField(
            model_name="researcher",
            name="display_name",
        ),
        migrations.AddField(
            model_name="researcher",
            name="updated",
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
        migrations.AddConstraint(
            model_name="identifier",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("harvester"),
                django.db.models.functions.text.Lower("value"),
                condition=models.Q(("harvester", "local"), _negated=True),
                name="unique_harvester",
            ),
        ),
        migrations.AddField(
            model_name="crisalidconfig",
            name="organization",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crisalid",
                to="organizations.organization",
            ),
        ),
    ]
