# Generated by Django 4.2.25 on 2025-12-09 09:41

import apps.commons.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_initial"),
        ("crisalid", "0002_crisalidconfig_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="identifier",
            name="harvester",
            field=models.CharField(
                choices=[
                    ("hal", "Hal"),
                    ("scanr", "Scanr"),
                    ("openalex", "Openalex"),
                    ("idref", "Idref"),
                    ("scopus", "Scopus"),
                    ("orcid", "Orcid"),
                    ("local", "Local"),
                    ("eppn", "Eppn"),
                    ("doi", "Doi"),
                    ("pmid", "Pmid"),
                    ("nns", "Nns"),
                    ("rnsr", "Rnsr"),
                ],
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="Structure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("updated", models.DateTimeField(auto_created=True, auto_now=True)),
                ("acronym", models.TextField(blank=True, null=True)),
                ("name", models.TextField()),
                (
                    "identifiers",
                    models.ManyToManyField(
                        related_name="structures", to="crisalid.identifier"
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="structures",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(apps.commons.mixins.OrganizationRelated, models.Model),
        ),
        migrations.AddField(
            model_name="researcher",
            name="employments",
            field=models.ManyToManyField(
                related_name="employments", to="crisalid.structure"
            ),
        ),
        migrations.AddField(
            model_name="researcher",
            name="memberships",
            field=models.ManyToManyField(
                related_name="memberships", to="crisalid.structure"
            ),
        ),
    ]
