# Generated by Django 4.2.25 on 2025-11-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crisalid", "0002_crisalidconfig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crisalidconfig",
            name="apollo_host",
            field=models.URLField(help_text="apollo/graphql host:port"),
        ),
        migrations.AlterField(
            model_name="crisalidconfig",
            name="crisalidbus_host",
            field=models.URLField(help_text="crisalidbus/rabimqt host:port"),
        ),
    ]
