# Generated by Django 5.2.10 on 2026-02-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crisalid", "0002_crisalidconfig_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={
                "ordering": (
                    models.OrderBy(
                        models.F("publication_date"), descending=True, nulls_last=True
                    ),
                )
            },
        ),
    ]
