# Generated by Django 4.2.22 on 2025-09-30 14:47

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ("crisalid", "0002_document_documentsource_researchidentifier_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Identifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "harvester",
                    models.CharField(
                        choices=[
                            ("hal", "Hal"),
                            ("scanr", "Scanr"),
                            ("openalex", "Openalex"),
                            ("idref", "Idref"),
                            ("scopus", "Scopus"),
                            ("orcid", "Orcid"),
                            ("local", "Local"),
                        ],
                        max_length=50,
                    ),
                ),
                ("value", models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name="ResearchIdentifier",
        ),
        migrations.AddConstraint(
            model_name="identifier",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("harvester"),
                django.db.models.functions.text.Lower("value"),
                name="unique_harvester",
            ),
        ),
        migrations.AddField(
            model_name="researcher",
            name="identifiers",
            field=models.ManyToManyField(
                related_name="researchers", to="crisalid.identifier"
            ),
        ),
        migrations.AlterField(
            model_name="documentsource",
            name="harvester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="docuements",
                to="crisalid.identifier",
            ),
        ),
    ]
