# Generated by Django 5.2.10 on 2026-01-21 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_peoplegroup_tags"),
        ("crisalid", "0003_alter_identifier_harvester_structure_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="structure",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="structure",
                to="accounts.peoplegroup",
            ),
        ),
    ]
