# Generated by Django 4.2.25 on 2025-11-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crisalid", "0003_alter_crisalidconfig_apollo_host_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="crisalidconfig",
            name="apollo_host",
        ),
        migrations.RemoveField(
            model_name="crisalidconfig",
            name="crisalidbus_host",
        ),
        migrations.AddField(
            model_name="crisalidconfig",
            name="apollo_url",
            field=models.CharField(
                default="", help_text="apollo/graphql host:port", max_length=255
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="crisalidconfig",
            name="crisalidbus_url",
            field=models.CharField(
                default="", help_text="crisalidbus/rabimqt host:port", max_length=255
            ),
            preserve_default=False,
        ),
    ]
