# Generated by Django 4.2.22 on 2025-09-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crisalid", "0004_remove_documentsource_unique_document_harvester_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentsource",
            name="crisalid_uid",
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
