# Generated by Django 4.2.25 on 2025-11-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crisalid", "0004_remove_crisalidconfig_apollo_host_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="document",
            name="crisalid_document_unique_crisalid_uid",
        ),
        migrations.RemoveConstraint(
            model_name="researcher",
            name="crisalid_researcher_unique_crisalid_uid",
        ),
        migrations.RemoveField(
            model_name="document",
            name="crisalid_uid",
        ),
        migrations.RemoveField(
            model_name="researcher",
            name="crisalid_uid",
        ),
        migrations.RemoveField(
            model_name="researcher",
            name="display_name",
        ),
        migrations.AddField(
            model_name="document",
            name="updated",
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
        migrations.AddField(
            model_name="researcher",
            name="family_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="researcher",
            name="given_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="researcher",
            name="updated",
            field=models.DateTimeField(auto_created=True, auto_now=True),
        ),
    ]
