# Generated by Django 4.2.22 on 2025-09-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crisalid", "0005_documentsource_crisalid_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="publication_date",
            field=models.DateField(null=True),
        ),
    ]
