# Generated by Django 4.2.22 on 2025-09-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crisalid", "0006_alter_document_publication_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="crisalid_uid",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="documentsource",
            name="crisalid_uid",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="researcher",
            name="crisalid_uid",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
