# Generated by Django 4.2.22 on 2025-09-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crisalid", "0007_alter_document_crisalid_uid_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="document",
            constraint=models.UniqueConstraint(
                models.F("crisalid_uid"), name="crisalid_document_unique_crisalid_uid"
            ),
        ),
        migrations.AddConstraint(
            model_name="researcher",
            constraint=models.UniqueConstraint(
                models.F("crisalid_uid"), name="crisalid_researcher_unique_crisalid_uid"
            ),
        ),
    ]
