# Generated by Django 4.2.22 on 2025-09-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crisalid", "0008_document_crisalid_document_unique_crisalid_uid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="ddd",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="documentsource",
            name="ddd",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="researcher",
            name="ddd",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
