# Generated by Django 4.2.22 on 2025-10-01 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crisalid", "0009_document_ddd_documentsource_ddd_researcher_ddd"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="title",
            field=models.TextField(),
        ),
    ]
