# Generated by Django 4.2.22 on 2025-10-01 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crisalid", "0010_alter_document_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="document",
            name="ddd",
        ),
        migrations.RemoveField(
            model_name="documentsource",
            name="ddd",
        ),
        migrations.RemoveField(
            model_name="researcher",
            name="ddd",
        ),
    ]
