# Generated by Django 4.2.22 on 2025-10-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crisalid", "0011_remove_document_ddd_remove_documentsource_ddd_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="crisalid_uid",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="documentsource",
            name="crisalid_uid",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
        migrations.AlterField(
            model_name="researcher",
            name="crisalid_uid",
            field=models.CharField(
                blank=True, db_index=True, max_length=255, null=True
            ),
        ),
    ]
