# Generated by Django 4.2.22 on 2025-10-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crisalid", "0012_alter_document_crisalid_uid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Audiovisual Document", "Audiovisual Document"),
                    ("Blog Post", "Blog Post"),
                    ("Book", "Book"),
                    ("Book Review", "Book Review"),
                    ("Chapter", "Chapter"),
                    ("Conference Output", "Conference Output"),
                    ("Conference Paper", "Conference Paper"),
                    ("Conference Poster", "Conference Poster"),
                    ("Data Management Plan", "Data Management Plan"),
                    ("Data Paper", "Data Paper"),
                    ("Dataset", "Dataset"),
                    ("Reference Book", "Dictionary"),
                    ("Document", "Document"),
                    ("Editorial", "Editorial"),
                    ("Erratum", "Erratum"),
                    ("Grant", "Grant"),
                    ("Image", "Image"),
                    ("Lecture", "Lecture"),
                    ("Letter", "Letter"),
                    ("Manual", "Manual"),
                    ("Map", "Map"),
                    ("Master Thesis", "Master Thesis"),
                    ("Metadata Document", "Metadata Document"),
                    ("Note", "Note"),
                    ("Other", "Other"),
                    ("Patent", "Patent"),
                    ("Peer review", "Peer Review"),
                    ("Preprint", "Preprint"),
                    ("Proceedings", "Proceedings"),
                    ("Report", "Report"),
                    ("Research Report", "Research Report"),
                    ("Review Paper", "Review"),
                    ("Review Article", "Review Article"),
                    ("Software", "Software"),
                    ("Standard", "Standard"),
                    ("Still Image", "Still Image"),
                    ("Technical Report", "Technical Report"),
                    ("Thesis", "Thesis"),
                    ("Working Paper", "Working Paper"),
                    ("Unknown", "Unknown"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="identifiers",
            field=models.ManyToManyField(
                related_name="documents", to="crisalid.identifier"
            ),
        ),
        migrations.DeleteModel(
            name="DocumentSource",
        ),
    ]
