# Generated by Django 4.2.25 on 2025-11-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comments", models.IntegerField(default=0)),
                ("replies", models.IntegerField(default=0)),
                ("follows", models.IntegerField(default=0)),
                ("links", models.IntegerField(default=0)),
                ("files", models.IntegerField(default=0)),
                ("blog_entries", models.IntegerField(default=0)),
                ("goals", models.IntegerField(default=0)),
                ("versions", models.IntegerField(default=0)),
                ("description_length", models.IntegerField(default=0)),
                ("last_update", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
