# Generated by Django 3.2.12 on 2022-04-11 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.IntegerField(default=0)),
                ('replies', models.IntegerField(default=0)),
                ('follows', models.IntegerField(default=0)),
                ('links', models.IntegerField(default=0)),
                ('files', models.IntegerField(default=0)),
                ('blog_entries', models.IntegerField(default=0)),
                ('goals', models.IntegerField(default=0)),
                ('versions', models.IntegerField(default=0)),
                ('description_length', models.IntegerField(default=0)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stat', to='projects.project')),
            ],
        ),
    ]
