# Generated by Django 4.2.7 on 2024-02-13 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pgvector.django


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("summary", models.TextField(blank=True)),
                ("embedding", pgvector.django.VectorField(dimensions=1024, null=True)),
                ("is_visible", models.BooleanField(default=False)),
                ("prompt_hashcode", models.CharField(default="", max_length=64)),
                ("queued_for_update", models.BooleanField(default=False)),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("summary", models.TextField(blank=True)),
                ("embedding", pgvector.django.VectorField(dimensions=1024, null=True)),
                ("is_visible", models.BooleanField(default=False)),
                ("prompt_hashcode", models.CharField(default="", max_length=64)),
                ("queued_for_update", models.BooleanField(default=False)),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
