# Generated by Django 4.2.10 on 2024-02-16 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mistral", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectembedding",
            name="queued_for_update",
        ),
        migrations.RemoveField(
            model_name="userembedding",
            name="queued_for_update",
        ),
    ]
