# Generated by Django 4.2.22 on 2025-09-29 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("skills", "0001_initial"),
        ("mistral", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tagembedding",
            name="item",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="embedding",
                to="skills.tag",
            ),
        ),
    ]
