# Generated by Django 4.2.11 on 2024-05-28 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mistral", "0002_remove_projectembedding_queued_for_update_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProjectsEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("summary", models.TextField(blank=True)),
                ("embedding", pgvector.django.VectorField(dimensions=1024, null=True)),
                ("is_visible", models.BooleanField(default=False)),
                ("prompt_hashcode", models.CharField(default="", max_length=64)),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects_embedding",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
