# Generated by Django 4.2.11 on 2024-05-29 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ("mistral", "0003_userprojectsembedding"),
    ]

    operations = [
        migrations.RenameModel("UserEmbedding", "UserProfileEmbedding"),
        migrations.AlterField(
            model_name="userprofileembedding",
            name="item",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile_embedding",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="UserEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("embedding", pgvector.django.VectorField(dimensions=1024, null=True)),
                ("is_visible", models.BooleanField(default=False)),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="userprojectsembedding",
            name="prompt_hashcode",
        ),
        migrations.RemoveField(
            model_name="userprojectsembedding",
            name="summary",
        ),
    ]
