# Generated by Django 4.2.14 on 2024-08-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mistral", "0004_auto_20240529_1207"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmbeddingError",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_type", models.CharField(max_length=255)),
                ("item_id", models.CharField(max_length=255)),
                ("error", models.CharField(max_length=255)),
                ("traceback", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
