# Generated by Django 5.2.10 on 2026-01-21 08:13

import django.db.models.deletion
import pgvector.django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_peoplegroup_tags"),
        ("mistral", "0004_documentembedding"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("embedding", pgvector.django.VectorField(dimensions=1024, null=True)),
                ("is_visible", models.BooleanField(default=False)),
                ("summary", models.TextField(blank=True)),
                ("prompt_hashcode", models.CharField(default="", max_length=64)),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding",
                        to="accounts.peoplegroup",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
