# Generated by Django 4.2.15 on 2024-09-18 21:24

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ("esco", "0001_initial"),
        ("misc", "0003_wikipediatag_description_wikipediatag_description_en_and_more"),
        ("mistral", "0005_embeddingerror"),
    ]

    operations = [
        migrations.CreateModel(
            name="WikipediaTagEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("embedding", pgvector.django.VectorField(dimensions=1024, null=True)),
                ("is_visible", models.BooleanField(default=False)),
                ("summary", models.TextField(blank=True)),
                ("prompt_hashcode", models.CharField(default="", max_length=64)),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding",
                        to="misc.wikipediatag",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EscoSkillEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("embedding", pgvector.django.VectorField(dimensions=1024, null=True)),
                ("is_visible", models.BooleanField(default=False)),
                ("summary", models.TextField(blank=True)),
                ("prompt_hashcode", models.CharField(default="", max_length=64)),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding",
                        to="esco.escoskill",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EscoOccupationEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("embedding", pgvector.django.VectorField(dimensions=1024, null=True)),
                ("is_visible", models.BooleanField(default=False)),
                ("summary", models.TextField(blank=True)),
                ("prompt_hashcode", models.CharField(default="", max_length=64)),
                (
                    "item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding",
                        to="esco.escooccupation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
