# Generated by Django 3.2.12 on 2022-04-05 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('deadline_at', models.DateField(null=True)),
                ('status', models.CharField(choices=[('na', 'None'), ('ongoing', 'Ongoing'), ('complete', 'Complete'), ('cancel', 'Cancel')], default='na', max_length=24)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='projects.project')),
            ],
        ),
    ]
