# Generated by Django 4.2.15 on 2024-10-03 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_alter_projectmessage_project"),
        ("goals", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="old_goals",
                to="projects.project",
            ),
        ),
    ]
