# Generated by Django 4.2.17 on 2025-01-21 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0003_alter_goal_project"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Goal",
        ),
    ]
