# Generated by Django 4.2.22 on 2025-09-29 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("skills", "0001_initial"),
        ("files", "0002_initial"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectcategory",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                db_table="organizations_projectcategory_skills_tags",
                related_name="project_categories",
                to="skills.tag",
            ),
        ),
        migrations.AddField(
            model_name="projectcategory",
            name="template",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="project_category",
                to="organizations.template",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="banner_image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="organization_banner",
                to="files.image",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="default_projects_tag_classification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_organizations_projects",
                to="skills.tagclassification",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="default_projects_tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="default_organizations_projects",
                to="skills.tag",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="default_skills_tag_classification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_organizations_skills",
                to="skills.tagclassification",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="default_skills_tags",
            field=models.ManyToManyField(
                blank=True, related_name="default_organizations_skills", to="skills.tag"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="enabled_projects_tag_classifications",
            field=models.ManyToManyField(
                blank=True,
                related_name="enabled_organizations_projects",
                to="skills.tagclassification",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="enabled_skills_tag_classifications",
            field=models.ManyToManyField(
                blank=True,
                related_name="enabled_organizations_skills",
                to="skills.tagclassification",
            ),
        ),
    ]
