# Generated by Django 4.2.10 on 2024-02-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="access_request_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
