# Generated by Django 3.2.12 on 2022-04-15 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprojectcategory',
            name='description',
            field=models.TextField(blank=True, help_text='description of the category'),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='background_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_category', to='files.image'),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='description',
            field=models.TextField(blank=True, help_text='description of the category'),
        ),
    ]
