# Generated by Django 3.2.12 on 2022-04-26 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_image_owner'),
        ('organizations', '0002_auto_20220415_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='faq',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization', to='organizations.faq'),
        ),
        migrations.AlterField(
            model_name='organizationdirectory',
            name='logo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization_directory_logo', to='files.image'),
        ),
    ]
