# Generated by Django 4.2.25 on 2025-11-18 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("files", "0003_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0002_initial"),
        ("keycloak", "0001_initial"),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="featured_projects",
            field=models.ManyToManyField(
                blank=True, related_name="org_featured_projects", to="projects.project"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="groups",
            field=models.ManyToManyField(related_name="organizations", to="auth.group"),
        ),
        migrations.AddField(
            model_name="organization",
            name="identity_providers",
            field=models.ManyToManyField(
                blank=True, related_name="organizations", to="keycloak.identityprovider"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="images",
            field=models.ManyToManyField(
                blank=True, related_name="organizations", to="files.image"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="logo_image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="organization_logo",
                to="files.image",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="historicalprojectcategory",
            name="background_image",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="files.image",
            ),
        ),
        migrations.AddField(
            model_name="historicalprojectcategory",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalprojectcategory",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="historicalprojectcategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="organizations.projectcategory",
            ),
        ),
        migrations.AddConstraint(
            model_name="termsandconditions",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("is_default",),
                name="unique_default_terms_and_conditions",
            ),
        ),
    ]
