# Generated by Django 4.2.10 on 2024-03-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("keycloak", "0002_identityprovider"),
        ("organizations", "0002_alter_organization_access_request_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="identity_providers",
            field=models.ManyToManyField(
                blank=True, related_name="organizations", to="keycloak.identityprovider"
            ),
        ),
    ]
