# Generated by Django 3.2.13 on 2022-05-04 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_auto_20220426_1333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcategory',
            options={'ordering': ['organization__code', 'order_index']},
        ),
    ]
