# Generated by Django 4.2.27 on 2025-12-10 13:22

import apps.commons.mixins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("organizations", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryFollow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follows",
                        to="organizations.projectcategory",
                    ),
                ),
                (
                    "follower",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_follows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
            bases=(
                apps.commons.mixins.HasOwner,
                apps.commons.mixins.OrganizationRelated,
                models.Model,
            ),
        ),
        migrations.AddConstraint(
            model_name="categoryfollow",
            constraint=models.UniqueConstraint(
                fields=("category", "follower"), name="unique_category_follow"
            ),
        ),
    ]
