# Generated by Django 3.2.13 on 2022-05-05 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_projectcategory_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='main_org_logo_background_color',
        ),
    ]
