# Generated by Django 6.0.5 on 2026-08-13 13:22

import apps.commons.mixins
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0004_categoryfollow_categoryfollow_unique_category_follow"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateTab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(auto_created=True, default=uuid.uuid4)),
                (
                    "title",
                    models.TextField(blank=True, default="", max_length=255, null=True),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("text", "Text"), ("blog", "Blog")],
                        default="text",
                        max_length=32,
                    ),
                ),
                ("icon", models.CharField(blank=True, max_length=255, null=True)),
                ("show_preview", models.BooleanField(default=True)),
                (
                    "title_item",
                    models.TextField(blank=True, default="", max_length=255, null=True),
                ),
                ("content_item", models.TextField(blank=True, null=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tabs",
                        to="organizations.template",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("uuid",), name="unique_template_tab"
                    )
                ],
            },
            bases=(apps.commons.mixins.OrganizationRelated, models.Model),
        ),
    ]
