# Generated by Django 6.0.5 on 2026-08-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0005_templatetab"),
    ]

    operations = [
        migrations.AddField(
            model_name="templatetab",
            name="content_item",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="templatetab",
            name="title_item",
            field=models.TextField(blank=True, default="", max_length=255, null=True),
        ),
    ]
