# Generated by Django 6.0.8 on 2026-09-17 08:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_template_enable_tab_templatetab'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='template',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
