# Generated by Django 3.2.13 on 2022-05-06 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_remove_organization_main_org_logo_background_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='tags',
            new_name='wikipedia_tags',
        ),
        migrations.RenameField(
            model_name='projectcategory',
            old_name='tags',
            new_name='wikipedia_tags',
        ),
    ]
