# Generated by Django 6.0.5 on 2026-08-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0006_templatetab_content_item_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="templatetab",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="templatetab",
            name="title",
            field=models.TextField(blank=True, default="", max_length=255, null=True),
        ),
    ]
