# Generated by Django 6.0.8 on 2026-10-05 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_template_created_at_template_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='templatetab',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='templatetab',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='templatetab',
            name='show_tab',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='templatetab',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('blog', 'Blog'), ('members', 'Members'), ('groups', 'Groups'), ('linked_projects', 'Linked Projects'), ('locations', 'Locations'), ('comments', 'Comments'), ('goals', 'Goals'), ('resources', 'Resources'), ('blogs', 'Blogs'), ('announcements', 'Announcements'), ('messages', 'Messages'), ('reviews', 'Reviews'), ('description', 'Description')], default='text', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='templatetab',
            constraint=models.UniqueConstraint(condition=models.Q(('type__in', ('blog', 'text')), _negated=True), fields=('template', 'type'), name='unique_tab_type_bridge'),
        ),
    ]
