# Generated by Django 6.0.8 on 2026-09-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_template_created_at_template_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatetab',
            name='show_tab',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='templatetab',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('blog', 'Blog'), ('members', 'Members'), ('groups', 'Groups'), ('linked_projects', 'Linked Projects'), ('locations', 'Locations'), ('comments', 'Comments'), ('goals', 'Goals'), ('files', 'Files'), ('links', 'Links'), ('announcements', 'Announcements'), ('messages', 'Messages')], default='text', max_length=32),
        ),
    ]
