# Generated by Django 3.2.13 on 2022-05-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_auto_20220506_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='blogentry_title_placeholder',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
