# Generated by Django 6.0.5 on 2026-08-12 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0007_templatetab_content_templatetab_title"),
    ]

    operations = [
        migrations.RenameField(
            model_name="templatetab",
            old_name="content",
            new_name="description",
        ),
    ]
