# Generated by Django 6.0.8 on 2026-09-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_templatetab_show_tab_alter_templatetab_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='templatetab',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='templatetab',
            name='order',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
