# Generated by Django 3.2.13 on 2022-05-09 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_projectcategory_organization_tags'),
        ('organizations', '0007_template_blogentry_title_placeholder'),
    ]

    operations = [
    ]
