# Generated by Django 4.2.11 on 2024-04-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0007_organization_featured_projects"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="chat_button_text",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="organization",
            name="chat_url",
            field=models.URLField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="organization",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
