# Generated by Django 3.2.13 on 2022-05-12 18:40

import apps.organizations.models
from django.db import migrations, models
import django.db.models.deletion


def init_templates(applications, schema_editor):
    category_model = applications.get_model("organizations", "ProjectCategory")
    template_model = applications.get_model("organizations", "Template")
    for category in category_model.objects.filter(template=None):
        template = template_model.objects.create()
        category.template = template
        category.save()


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_merge_20220509_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprojectcategory',
            name='only_reviewer_can_publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectcategory',
            name='only_reviewer_can_publish',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(init_templates, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='historicalprojectcategory',
            name='template',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.template'),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='template',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='project_category', to='organizations.template'),
        ),
        migrations.AlterField(
            model_name='template',
            name='blogentry_placeholder',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='template',
            name='blogentry_title_placeholder',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='template',
            name='description_placeholder',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='template',
            name='goal_placeholder',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='template',
            name='title_placeholder',
            field=models.CharField(default='', max_length=255),
        ),
    ]
