# Generated by Django 4.2.11 on 2024-04-19 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "organizations",
            "0008_organization_chat_button_text_organization_chat_url_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalprojectcategory",
            name="is_root",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicalprojectcategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="organizations.projectcategory",
            ),
        ),
        migrations.AddField(
            model_name="projectcategory",
            name="is_root",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="projectcategory",
            name="parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="organizations.projectcategory",
            ),
        ),
        migrations.AlterField(
            model_name="projectcategory",
            name="template",
            field=models.OneToOneField(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="project_category",
                to="organizations.template",
            ),
        ),
    ]
