# Generated by Django 6.0.5 on 2026-08-12 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0008_rename_content_templatetab_description"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="templatetab",
            constraint=models.UniqueConstraint(
                fields=("uuid",), name="unique_template_tab"
            ),
        ),
    ]
