# Generated by Django 3.2.13 on 2022-05-13 08:54
import uuid

from django.conf import settings
from django.core.files import File
from django.db import migrations, models
import django.db.models.deletion

from apps.misc.models import Language


def get_image_file(path: str) -> File:
    return File(open(path, 'rb'))


def logo_upload_to(instance, filename) -> str:
    return f'organization/logo/{uuid.uuid4()}#{instance.name}'


def upload_image_from_assets(path, apps, upload_to):
    """Return an Image instance."""
    model = apps.get_model("files", "Image")
    file = get_image_file(path)
    image = model(name=f"{uuid.uuid4()}.png", file=file)
    image._upload_to = upload_to
    image.save()
    return image


def create_org_directory(apps, schema_editor):
    directory = apps.get_model("organizations", "OrganizationDirectory")
    logo = upload_image_from_assets(f'{settings.BASE_DIR}/assets/default_logo.png', apps, logo_upload_to)
    organization_directory, _ = directory.objects.update_or_create(
        pk=1,
        defaults=dict(
            name="Default Directory",
            description="default organization directory",
            language=Language.default().value.lower(),
            logo=logo,
        ))
    db_alias = schema_editor.connection.alias
    organization = apps.get_model("organizations", "Organization")
    organization.objects.using(db_alias).all().update(organization_directory=organization_directory)


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_auto_20220512_1840'),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop, create_org_directory),
        migrations.RemoveField(
            model_name='organization',
            name='organization_directory',
        ),
        migrations.AddField(
            model_name='organization',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='organizations.organization'),
        ),
        migrations.DeleteModel(
            name='OrganizationDirectory',
        ),
    ]
