# Generated by Django 6.0.5 on 2026-08-12 12:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0009_templatetab_unique_template_tab"),
    ]

    operations = [
        migrations.AlterField(
            model_name="templatetab",
            name="uuid",
            field=models.UUIDField(auto_created=True, default=uuid.uuid4),
        ),
    ]
