# Generated by Django 4.2.11 on 2024-06-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0009_historicalprojectcategory_is_root_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="force_login_form_display",
            field=models.BooleanField(default=False),
        ),
    ]
