# Generated by Django 6.0.8 on 2026-09-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_alter_templatetab_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatetab',
            name='type',
            field=models.CharField(choices=[('text', 'Text'), ('blog', 'Blog'), ('members', 'Members'), ('groups', 'Groups'), ('linked_projects', 'Linked Projects'), ('locations', 'Locations'), ('comments', 'Comments'), ('goals', 'Goals'), ('resources', 'Resources'), ('blogs', 'Blogs'), ('announcements', 'Announcements'), ('private-exchange', 'Private Exchange'), ('review', 'Review'), ('description', 'Description')], default='text', max_length=32),
        ),
    ]
