# Generated by Django 4.2.14 on 2024-08-08 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0002_initial"),
        ("projects", "0002_projectscore"),
        ("misc", "0003_wikipediatag_description_wikipediatag_description_en_and_more"),
        ("organizations", "0010_organization_force_login_form_display"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="organization",
            name="featured_projects",
            field=models.ManyToManyField(
                blank=True, related_name="org_featured_projects", to="projects.project"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="images",
            field=models.ManyToManyField(
                blank=True, related_name="organizations", to="files.image"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="organizations.organization",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="website_url",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="organization",
            name="wikipedia_tags",
            field=models.ManyToManyField(blank=True, to="misc.wikipediatag"),
        ),
        migrations.AlterField(
            model_name="projectcategory",
            name="organization_tags",
            field=models.ManyToManyField(
                related_name="project_categories", to="misc.tag"
            ),
        ),
    ]
