# Generated by Django 6.0.8 on 2026-10-01 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_alter_templatetab_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatetab',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='templatetab',
            constraint=models.UniqueConstraint(condition=models.Q(('type__in', ('blog', 'text')), _negated=True), fields=('type',), name='unique_tab_type_bridge'),
        ),
    ]
