# Generated by Django 3.2.13 on 2022-05-31 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0011_default_organization_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprojectcategory',
            name='is_reviewable',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='is_reviewable',
            field=models.BooleanField(default=True),
        ),
    ]
