# Generated by Django 4.2.15 on 2024-09-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0001_initial"),
        ("organizations", "0012_alter_organization_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="organizations", to="skills.tag"
            ),
        ),
        migrations.AddField(
            model_name="projectcategory",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="project_categories", to="skills.tag"
            ),
        ),
    ]
