# Generated by Django 6.0.8 on 2026-10-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0012_alter_templatetab_order_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='templatetab',
            name='unique_tab_type_bridge',
        ),
        migrations.AddConstraint(
            model_name='templatetab',
            constraint=models.UniqueConstraint(condition=models.Q(('type__in', ('blog', 'text')), _negated=True), fields=('template', 'type'), name='unique_tab_type_bridge'),
        ),
    ]
