# Generated by Django 4.2.15 on 2024-10-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0001_initial"),
        ("organizations", "0012_alter_organization_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                db_column="coucou_tag_id",
                db_table="coucoucocucoucou_tags_skills_org_org",
                related_name="organizations",
                to="skills.tag",
            ),
        ),
        migrations.AddField(
            model_name="projectcategory",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                db_table="organizations_organization_skills_tags",
                related_name="project_categories",
                to="skills.tag",
            ),
        ),
    ]
