# Generated by Django 3.2.13 on 2022-06-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0012_auto_20220531_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='goal_placeholder',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='template',
            name='title_placeholder',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='template',
            name='blogentry_placeholder',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='template',
            name='blogentry_title_placeholder',
            field=models.TextField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='template',
            name='description_placeholder',
            field=models.TextField(blank=True, default=''),
        ),
    ]
