# Generated by Django 4.0.5 on 2022-06-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0012_auto_20220531_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_logo_visible_on_parent_dashboard',
            field=models.BooleanField(default=True),
        ),
    ]
