# Generated by Django 4.0.5 on 2022-06-07 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0013_auto_20220607_0948'),
        ('organizations', '0013_organization_is_logo_visible_on_parent_dashboard'),
    ]

    operations = [
    ]
