# Generated by Django 4.2.16 on 2024-10-24 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0001_initial"),
        ("organizations", "0013_organization_tags_projectcategory_tags"),
    ]

    operations = [
        migrations.RenameField(
            model_name="organization",
            old_name="default_tag_classification",
            new_name="default_projects_tag_classification",
        ),
        migrations.RenameField(
            model_name="organization",
            old_name="enabled_tag_classifications",
            new_name="enabled_projects_tag_classifications",
        ),
        migrations.AlterField(
            model_name="organization",
            name="default_projects_tag_classification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_organizations_projects",
                to="skills.tagclassification",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="enabled_projects_tag_classifications",
            field=models.ManyToManyField(
                blank=True,
                related_name="enabled_organizations_projects",
                to="skills.tagclassification",
            ),
        ),        
        migrations.AddField(
            model_name="organization",
            name="default_skills_tag_classification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="default_organizations_skills",
                to="skills.tagclassification",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="enabled_skills_tag_classifications",
            field=models.ManyToManyField(
                blank=True,
                related_name="enabled_organizations_skills",
                to="skills.tagclassification",
            ),
        ),
    ]
