# Generated by Django 4.0.5 on 2022-06-29 09:50

from django.db import migrations


def set_organizations_parent_to_default(apps, schema_editor):
    Organization = apps.get_model('organizations', 'Organization')
    try:
        default_organization = Organization.objects.get(code="DEFAULT")
        organizations = Organization.objects.exclude(id=default_organization.id)
        for organization in organizations:
            organization.parent = default_organization
            organization.save()
    except Organization.DoesNotExist as e:
        print(f"default_organization not found. ({e})")



class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0014_merge_20220607_1514'),
    ]

    operations = [
        migrations.RunPython(set_organizations_parent_to_default),
    ]
