# Generated by Django 4.2.16 on 2024-10-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0001_initial"),
        (
            "organizations",
            "0014_remove_organization_default_tag_classification_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="organization",
            old_name="tags",
            new_name="default_projects_tags",
        ),
        migrations.AlterField(
            model_name="organization",
            name="default_projects_tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="default_organizations_projects",
                to="skills.tag",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="default_skills_tags",
            field=models.ManyToManyField(
                blank=True, related_name="default_organizations_skills", to="skills.tag"
            ),
        ),
    ]
