# Generated by Django 4.0.5 on 2022-06-29 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0015_remove_organization_is_logo_visible_on_parent_dashboard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='main_org_logo_visibility',
            new_name='is_logo_visible_on_parent_dashboard',
        ),
    ]
