# Generated by Django 4.0.5 on 2022-06-29 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0015_auto_20220629_0950'),
        ('organizations', '0016_rename_main_org_logo_visibility_organization_is_logo_visible_on_parent_dashboard'),
    ]

    operations = [
    ]
