# Generated by Django 4.2.17 on 2025-01-21 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0017_alter_organization_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="wikipedia_tags",
        ),
        migrations.RemoveField(
            model_name="projectcategory",
            name="organization_tags",
        ),
        migrations.RemoveField(
            model_name="projectcategory",
            name="wikipedia_tags",
        ),
    ]
