# Generated by Django 4.0.7 on 2022-10-03 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0019_give_organization_rights'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='goal_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='template',
            name='goal_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
