# Generated by Django 4.2.20 on 2025-04-15 14:53

import apps.commons.enums
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0020_historicalprojectcategory_outdated_slugs_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="languages",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[("fr", "French"), ("en", "English"), ("de", "German")],
                    max_length=2,
                ),
                default=apps.commons.enums.Language.default_list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="language",
            field=models.CharField(
                choices=[("fr", "French"), ("en", "English"), ("de", "German")],
                default="en",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="language",
            field=models.CharField(
                choices=[("fr", "French"), ("en", "English"), ("de", "German")],
                default="en",
                max_length=2,
            ),
        ),
    ]
