# Generated by Django 4.0.7 on 2022-10-03 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0020_template_goal_description_template_goal_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprojectcategory',
            name='template',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='organizations.template'),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='template',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='project_category', to='organizations.template'),
        ),
    ]
