# Generated by Django 4.2.20 on 2025-04-18 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0020_historicalprojectcategory_outdated_slugs_and_more"),
        ("skills", "0008_tagclassification_outdated_slugs"),
    ]

    operations = [
        migrations.RenameField(
            model_name="template",
            old_name="description_placeholder",
            new_name="project_description",
        ),
        migrations.RenameField(
            model_name="template",
            old_name="title_placeholder",
            new_name="project_title",
        ),
        migrations.RemoveField(
            model_name="template",
            name="goal_title",
        ),
        migrations.RenameField(
            model_name="template",
            old_name="blogentry_placeholder",
            new_name="blogentry_content",
        ),
        migrations.RenameField(
            model_name="template",
            old_name="blogentry_title_placeholder",
            new_name="blogentry_title",
        ),
        migrations.RenameField(
            model_name="template",
            old_name="goal_placeholder",
            new_name="goal_title",
        ),
        migrations.AddField(
            model_name="template",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="template",
            name="name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="template",
            name="project_tags",
            field=models.ManyToManyField(
                blank=True, related_name="templates", to="skills.tag"
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="audience",
            field=models.CharField(
                blank=True,
                choices=[
                    ("primary", "Primary"),
                    ("middle", "Middle"),
                    ("high", "High"),
                    ("bachelor", "Bachelor"),
                    ("master", "Master"),
                    ("phd", "Phd"),
                    ("work", "Work"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="review_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="template",
            name="review_title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="template",
            name="share_globally",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="template",
            name="time_estimation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1-10hrs", "H1 H10"),
                    ("11-40hrs", "H11 H40"),
                    ("41-120hrs", "H41 H120"),
                    ("Over 120hrs", "H121 Plus"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="template",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="templates",
                to="organizations.organization",
            ),
        ),
        migrations.CreateModel(
            name="TemplateCategories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("always_use", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.projectcategory",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.template",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="template",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="templates",
                through="organizations.TemplateCategories",
                to="organizations.projectcategory",
            ),
        ),
    ]
