# Generated by Django 4.0.7 on 2022-12-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0021_alter_historicalprojectcategory_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='language',
            field=models.CharField(choices=[('fr', 'French'), ('en', 'English')], default='en', max_length=2),
        ),
    ]
