# Generated by Django 4.2.20 on 2025-06-12 08:28

import apps.commons.enums
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0022_alter_organization_language_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("fr", "Français"),
                    ("de", "Deutsch"),
                    ("nl", "Dutch"),
                    ("et", "Estonian"),
                    ("ca", "Catalan"),
                ],
                default="en",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="languages",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("en", "English"),
                        ("fr", "Français"),
                        ("de", "Deutsch"),
                        ("nl", "Dutch"),
                        ("et", "Estonian"),
                        ("ca", "Catalan"),
                    ],
                    max_length=2,
                ),
                default=apps.commons.enums.Language.default_list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("fr", "Français"),
                    ("de", "Deutsch"),
                    ("nl", "Dutch"),
                    ("et", "Estonian"),
                    ("ca", "Catalan"),
                ],
                default="en",
                max_length=2,
            ),
        ),
    ]
