# Generated by Django 4.0.8 on 2022-12-21 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0022_alter_organization_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='members',
        ),
        migrations.DeleteModel(
            name='OrganizationMember',
        ),
    ]
