# Generated by Django 4.0.8 on 2023-01-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0023_remove_organization_members_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='language',
            field=models.CharField(choices=[('fr', 'French'), ('en', 'English')], default='en', max_length=2),
        ),
    ]
