# Generated by Django 4.2.22 on 2025-09-08 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0024_alter_organization_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalprojectcategory",
            name="description_ca",
            field=models.TextField(
                blank=True, help_text="description of the category", null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalprojectcategory",
            name="description_de",
            field=models.TextField(
                blank=True, help_text="description of the category", null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalprojectcategory",
            name="description_en",
            field=models.TextField(
                blank=True, help_text="description of the category", null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalprojectcategory",
            name="description_et",
            field=models.TextField(
                blank=True, help_text="description of the category", null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalprojectcategory",
            name="description_fr",
            field=models.TextField(
                blank=True, help_text="description of the category", null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalprojectcategory",
            name="description_nl",
            field=models.TextField(
                blank=True, help_text="description of the category", null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalprojectcategory",
            name="name_ca",
            field=models.CharField(
                blank=True, help_text="name of the category", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalprojectcategory",
            name="name_de",
            field=models.CharField(
                blank=True, help_text="name of the category", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalprojectcategory",
            name="name_en",
            field=models.CharField(
                blank=True, help_text="name of the category", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalprojectcategory",
            name="name_et",
            field=models.CharField(
                blank=True, help_text="name of the category", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalprojectcategory",
            name="name_fr",
            field=models.CharField(
                blank=True, help_text="name of the category", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalprojectcategory",
            name="name_nl",
            field=models.CharField(
                blank=True, help_text="name of the category", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="auto_translate_content",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="organization",
            name="chat_button_text_ca",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="chat_button_text_de",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="chat_button_text_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="chat_button_text_et",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="chat_button_text_fr",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="chat_button_text_nl",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="dashboard_subtitle_ca",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="dashboard_subtitle_de",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="dashboard_subtitle_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="dashboard_subtitle_et",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="dashboard_subtitle_fr",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="dashboard_subtitle_nl",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="dashboard_title_ca",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="dashboard_title_de",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="dashboard_title_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="dashboard_title_et",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="dashboard_title_fr",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="dashboard_title_nl",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="description_ca",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="description_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="description_et",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="description_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="description_nl",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="name_ca",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="name_de",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="name_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="name_et",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="name_fr",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="name_nl",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="projectcategory",
            name="description_ca",
            field=models.TextField(
                blank=True, help_text="description of the category", null=True
            ),
        ),
        migrations.AddField(
            model_name="projectcategory",
            name="description_de",
            field=models.TextField(
                blank=True, help_text="description of the category", null=True
            ),
        ),
        migrations.AddField(
            model_name="projectcategory",
            name="description_en",
            field=models.TextField(
                blank=True, help_text="description of the category", null=True
            ),
        ),
        migrations.AddField(
            model_name="projectcategory",
            name="description_et",
            field=models.TextField(
                blank=True, help_text="description of the category", null=True
            ),
        ),
        migrations.AddField(
            model_name="projectcategory",
            name="description_fr",
            field=models.TextField(
                blank=True, help_text="description of the category", null=True
            ),
        ),
        migrations.AddField(
            model_name="projectcategory",
            name="description_nl",
            field=models.TextField(
                blank=True, help_text="description of the category", null=True
            ),
        ),
        migrations.AddField(
            model_name="projectcategory",
            name="name_ca",
            field=models.CharField(
                blank=True, help_text="name of the category", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="projectcategory",
            name="name_de",
            field=models.CharField(
                blank=True, help_text="name of the category", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="projectcategory",
            name="name_en",
            field=models.CharField(
                blank=True, help_text="name of the category", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="projectcategory",
            name="name_et",
            field=models.CharField(
                blank=True, help_text="name of the category", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="projectcategory",
            name="name_fr",
            field=models.CharField(
                blank=True, help_text="name of the category", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="projectcategory",
            name="name_nl",
            field=models.CharField(
                blank=True, help_text="name of the category", max_length=100, null=True
            ),
        ),
    ]
