# Generated by Django 4.2.22 on 2025-06-24 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0024_alter_organization_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="auto_translate_content",
            field=models.BooleanField(default=False),
        ),
    ]
