# Generated by Django 4.2.3 on 2023-08-01 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0024_template_language"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organization",
            name="groups",
        ),
    ]
