# Generated by Django 4.2.22 on 2025-09-16 13:16

import apps.commons.enums
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "organizations",
            "0026_historicalprojectcategory_description_detected_language_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalprojectcategory",
            name="description_es",
            field=models.TextField(
                blank=True, help_text="description of the category", null=True
            ),
        ),
        migrations.AddField(
            model_name="historicalprojectcategory",
            name="name_es",
            field=models.CharField(
                blank=True, help_text="name of the category", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="chat_button_text_es",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="dashboard_subtitle_es",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="dashboard_title_es",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="description_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organization",
            name="name_es",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="projectcategory",
            name="description_es",
            field=models.TextField(
                blank=True, help_text="description of the category", null=True
            ),
        ),
        migrations.AddField(
            model_name="projectcategory",
            name="name_es",
            field=models.CharField(
                blank=True, help_text="name of the category", max_length=100, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("fr", "Français"),
                    ("de", "Deutsch"),
                    ("nl", "Dutch"),
                    ("et", "Estonian"),
                    ("ca", "Catalan"),
                    ("es", "Español"),
                ],
                default="en",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="languages",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("en", "English"),
                        ("fr", "Français"),
                        ("de", "Deutsch"),
                        ("nl", "Dutch"),
                        ("et", "Estonian"),
                        ("ca", "Catalan"),
                        ("es", "Español"),
                    ],
                    max_length=2,
                ),
                default=apps.commons.enums.Language.default_list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="template",
            name="language",
            field=models.CharField(
                choices=[
                    ("en", "English"),
                    ("fr", "Français"),
                    ("de", "Deutsch"),
                    ("nl", "Dutch"),
                    ("et", "Estonian"),
                    ("ca", "Catalan"),
                    ("es", "Español"),
                ],
                default="en",
                max_length=2,
            ),
        ),
    ]
