# Generated by Django 4.2.22 on 2025-09-17 09:46

import apps.commons.mixins
from django.db import migrations, models
import django.db.models.deletion
import services.translator.mixins


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0027_historicalprojectcategory_description_es_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TermsAndConditions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                ("content", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("content_en", models.TextField(blank=True, default="", null=True)),
                ("content_fr", models.TextField(blank=True, default="", null=True)),
                ("content_de", models.TextField(blank=True, default="", null=True)),
                ("content_nl", models.TextField(blank=True, default="", null=True)),
                ("content_et", models.TextField(blank=True, default="", null=True)),
                ("content_ca", models.TextField(blank=True, default="", null=True)),
                (
                    "content_detected_language",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("content_es", models.TextField(blank=True, default="", null=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="terms_and_conditions",
                        to="organizations.organization",
                    ),
                ),
            ],
            bases=(
                services.translator.mixins.HasAutoTranslatedFields,
                apps.commons.mixins.OrganizationRelated,
                models.Model,
            ),
        ),
    ]
