# Generated by Django 4.2.22 on 2025-10-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0028_termsandconditions"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="comment",
            field=models.TextField(blank=True),
        ),
    ]
