# Generated by Django 4.2.22 on 2025-10-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0029_template_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="termsandconditions",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="termsandconditions",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("is_default",),
                name="unique_default_terms_and_conditions",
            ),
        ),
    ]
