# Generated by Django 4.2.22 on 2025-10-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0030_alter_organization_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="template",
            name="blogentry_content_ca",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="blogentry_content_de",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="blogentry_content_detected_language",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="blogentry_content_en",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="blogentry_content_es",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="blogentry_content_et",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="blogentry_content_fr",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="blogentry_content_nl",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="blogentry_title_ca",
            field=models.TextField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="blogentry_title_de",
            field=models.TextField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="blogentry_title_detected_language",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="blogentry_title_en",
            field=models.TextField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="blogentry_title_es",
            field=models.TextField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="blogentry_title_et",
            field=models.TextField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="blogentry_title_fr",
            field=models.TextField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="blogentry_title_nl",
            field=models.TextField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="comment_content_ca",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="comment_content_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="comment_content_detected_language",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="comment_content_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="comment_content_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="comment_content_et",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="comment_content_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="comment_content_nl",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="description_ca",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="description_de",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="description_detected_language",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="description_en",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="description_es",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="description_et",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="description_fr",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="description_nl",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="goal_description_ca",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="goal_description_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="goal_description_detected_language",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="goal_description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="goal_description_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="goal_description_et",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="goal_description_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="goal_description_nl",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="goal_title_ca",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="goal_title_de",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="goal_title_detected_language",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="goal_title_en",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="goal_title_es",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="goal_title_et",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="goal_title_fr",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="goal_title_nl",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="name_ca",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="name_de",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="name_detected_language",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="name_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="name_es",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="name_et",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="name_fr",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="name_nl",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="project_description_ca",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="project_description_de",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="project_description_detected_language",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="project_description_en",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="project_description_es",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="project_description_et",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="project_description_fr",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="project_description_nl",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="project_title_ca",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="project_title_de",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="project_title_detected_language",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="project_title_en",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="project_title_es",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="project_title_et",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="project_title_fr",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="project_title_nl",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="review_description_ca",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="review_description_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="review_description_detected_language",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="review_description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="review_description_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="review_description_et",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="review_description_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="review_description_nl",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="review_title_ca",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="review_title_de",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="review_title_detected_language",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="review_title_en",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="review_title_es",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="review_title_et",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="review_title_fr",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="template",
            name="review_title_nl",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
