# Generated by Django 4.2.22 on 2025-10-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0030_termsandconditions_is_default_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalprojectcategory",
            name="name_ca",
            field=models.CharField(
                blank=True, help_text="name of the category", max_length=400, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalprojectcategory",
            name="name_de",
            field=models.CharField(
                blank=True, help_text="name of the category", max_length=400, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalprojectcategory",
            name="name_en",
            field=models.CharField(
                blank=True, help_text="name of the category", max_length=400, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalprojectcategory",
            name="name_es",
            field=models.CharField(
                blank=True, help_text="name of the category", max_length=400, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalprojectcategory",
            name="name_et",
            field=models.CharField(
                blank=True, help_text="name of the category", max_length=400, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalprojectcategory",
            name="name_fr",
            field=models.CharField(
                blank=True, help_text="name of the category", max_length=400, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalprojectcategory",
            name="name_nl",
            field=models.CharField(
                blank=True, help_text="name of the category", max_length=400, null=True
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="chat_button_text_ca",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="chat_button_text_de",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="chat_button_text_en",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="chat_button_text_es",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="chat_button_text_et",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="chat_button_text_fr",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="chat_button_text_nl",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="dashboard_subtitle_ca",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="dashboard_subtitle_de",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="dashboard_subtitle_en",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="dashboard_subtitle_es",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="dashboard_subtitle_et",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="dashboard_subtitle_fr",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="dashboard_subtitle_nl",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="dashboard_title_ca",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="dashboard_title_de",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="dashboard_title_en",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="dashboard_title_es",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="dashboard_title_et",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="dashboard_title_fr",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="dashboard_title_nl",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name_ca",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name_de",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name_en",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name_es",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name_et",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name_fr",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="name_nl",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="projectcategory",
            name="name_ca",
            field=models.CharField(
                blank=True, help_text="name of the category", max_length=400, null=True
            ),
        ),
        migrations.AlterField(
            model_name="projectcategory",
            name="name_de",
            field=models.CharField(
                blank=True, help_text="name of the category", max_length=400, null=True
            ),
        ),
        migrations.AlterField(
            model_name="projectcategory",
            name="name_en",
            field=models.CharField(
                blank=True, help_text="name of the category", max_length=400, null=True
            ),
        ),
        migrations.AlterField(
            model_name="projectcategory",
            name="name_es",
            field=models.CharField(
                blank=True, help_text="name of the category", max_length=400, null=True
            ),
        ),
        migrations.AlterField(
            model_name="projectcategory",
            name="name_et",
            field=models.CharField(
                blank=True, help_text="name of the category", max_length=400, null=True
            ),
        ),
        migrations.AlterField(
            model_name="projectcategory",
            name="name_fr",
            field=models.CharField(
                blank=True, help_text="name of the category", max_length=400, null=True
            ),
        ),
        migrations.AlterField(
            model_name="projectcategory",
            name="name_nl",
            field=models.CharField(
                blank=True, help_text="name of the category", max_length=400, null=True
            ),
        ),
    ]
