# Generated by Django 4.2.7 on 2023-12-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0031_alter_organization_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="access_request_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
