# Generated by Django 4.2.25 on 2025-10-13 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0030_termsandconditions_is_default_and_more"),
        ("organizations", "0031_template_blogentry_content_ca_and_more"),
    ]

    operations = []
