# Generated by Django 4.2.7 on 2024-01-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0032_alter_organization_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="onboarding_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
