# Generated by Django 4.2.25 on 2025-10-13 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0032_merge_20251013_1200"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalprojectcategory",
            name="template",
        ),
        migrations.RemoveField(
            model_name="projectcategory",
            name="template",
        ),
    ]
