# Generated by Django 4.2.15 on 2024-10-08 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attachmentfile",
            name="attachment_type",
        ),
        migrations.RemoveField(
            model_name="attachmentlink",
            name="attachment_type",
        ),
        migrations.RemoveField(
            model_name="attachmentlink",
            name="category",
        ),
        migrations.RemoveField(
            model_name="historicalattachmentfile",
            name="attachment_type",
        ),
        migrations.RemoveField(
            model_name="historicalattachmentlink",
            name="attachment_type",
        ),
        migrations.RemoveField(
            model_name="historicalattachmentlink",
            name="category",
        ),
    ]
