# Generated by Django 4.2.20 on 2025-06-13 10:00

import apps.commons.mixins
import apps.files.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0023_alter_organization_language_and_more"),
        ("files", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationAttachmentFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attachment_type",
                    models.CharField(
                        choices=[
                            ("file", "File"),
                            ("image", "Image"),
                            ("video", "Video"),
                            ("link", "Link"),
                        ],
                        default="file",
                        max_length=10,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.files.models.organization_attachment_directory_path
                    ),
                ),
                ("mime", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("hashcode", models.CharField(default="", max_length=64)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachment_files",
                        to="organizations.organization",
                    ),
                ),
            ],
            bases=(models.Model, apps.commons.mixins.OrganizationRelated),
        ),
        migrations.DeleteModel(
            name="PeopleResource",
        ),
    ]
