# Generated by Django 4.2.22 on 2025-07-21 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0003_organizationattachmentfile_delete_peopleresource"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachmentfile",
            name="description_ca",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attachmentfile",
            name="description_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attachmentfile",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attachmentfile",
            name="description_et",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attachmentfile",
            name="description_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attachmentfile",
            name="description_nl",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attachmentfile",
            name="title_ca",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="attachmentfile",
            name="title_de",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="attachmentfile",
            name="title_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="attachmentfile",
            name="title_et",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="attachmentfile",
            name="title_fr",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="attachmentfile",
            name="title_nl",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="attachmentlink",
            name="description_ca",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attachmentlink",
            name="description_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attachmentlink",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attachmentlink",
            name="description_et",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attachmentlink",
            name="description_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attachmentlink",
            name="description_nl",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attachmentlink",
            name="title_ca",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="attachmentlink",
            name="title_de",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="attachmentlink",
            name="title_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="attachmentlink",
            name="title_et",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="attachmentlink",
            name="title_fr",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="attachmentlink",
            name="title_nl",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalattachmentfile",
            name="description_ca",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalattachmentfile",
            name="description_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalattachmentfile",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalattachmentfile",
            name="description_et",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalattachmentfile",
            name="description_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalattachmentfile",
            name="description_nl",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalattachmentfile",
            name="title_ca",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalattachmentfile",
            name="title_de",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalattachmentfile",
            name="title_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalattachmentfile",
            name="title_et",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalattachmentfile",
            name="title_fr",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalattachmentfile",
            name="title_nl",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalattachmentlink",
            name="description_ca",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalattachmentlink",
            name="description_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalattachmentlink",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalattachmentlink",
            name="description_et",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalattachmentlink",
            name="description_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalattachmentlink",
            name="description_nl",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalattachmentlink",
            name="title_ca",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalattachmentlink",
            name="title_de",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalattachmentlink",
            name="title_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalattachmentlink",
            name="title_et",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalattachmentlink",
            name="title_fr",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalattachmentlink",
            name="title_nl",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organizationattachmentfile",
            name="description_ca",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organizationattachmentfile",
            name="description_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organizationattachmentfile",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organizationattachmentfile",
            name="description_et",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organizationattachmentfile",
            name="description_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organizationattachmentfile",
            name="description_nl",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organizationattachmentfile",
            name="title_ca",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organizationattachmentfile",
            name="title_de",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organizationattachmentfile",
            name="title_en",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organizationattachmentfile",
            name="title_et",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organizationattachmentfile",
            name="title_fr",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organizationattachmentfile",
            name="title_nl",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
