# Generated by Django 4.2.25 on 2025-11-20 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.commons.mixins
import apps.files.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("files", "0003_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectUserAttachmentLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attachment_type",
                    models.CharField(
                        choices=[
                            ("file", "File"),
                            ("image", "Image"),
                            ("video", "Video"),
                            ("link", "Link"),
                        ],
                        default="link",
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("project_website", "Project Website"),
                            ("documentary_resource", "Documentary Resource"),
                            ("inspiration", "Inspiration"),
                            ("data", "Data"),
                            ("publication", "Publication"),
                            ("source_code", "Source Code"),
                            ("tool", "Tool"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "preview_image_url",
                    models.URLField(
                        help_text="attachment link preview image, mostly thumbnails",
                        max_length=2048,
                    ),
                ),
                ("site_name", models.CharField(max_length=255)),
                ("site_url", models.URLField(max_length=2048)),
                ("title", models.CharField(blank=True, max_length=255)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "description_ca",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "description_de",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "description_detected_language",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "description_es",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "description_et",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "description_fr",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "description_nl",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "title_ca",
                    models.CharField(blank=True, max_length=1020, null=True),
                ),
                (
                    "title_de",
                    models.CharField(blank=True, max_length=1020, null=True),
                ),
                (
                    "title_detected_language",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "title_en",
                    models.CharField(blank=True, max_length=1020, null=True),
                ),
                (
                    "title_es",
                    models.CharField(blank=True, max_length=1020, null=True),
                ),
                (
                    "title_et",
                    models.CharField(blank=True, max_length=1020, null=True),
                ),
                (
                    "title_fr",
                    models.CharField(blank=True, max_length=1020, null=True),
                ),
                (
                    "title_nl",
                    models.CharField(blank=True, max_length=1020, null=True),
                ),
            ],
            bases=(apps.commons.mixins.HasOwner, models.Model),
        ),
        migrations.CreateModel(
            name="ProjectUserAttachmentFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attachment_type",
                    models.CharField(
                        choices=[
                            ("file", "File"),
                            ("image", "Image"),
                            ("video", "Video"),
                            ("link", "Link"),
                        ],
                        default="file",
                        max_length=10,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.files.models.user_attachment_directory_path
                    ),
                ),
                ("mime", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("hashcode", models.CharField(default="", max_length=64)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "description_ca",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "description_de",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "description_detected_language",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "description_es",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "description_et",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "description_fr",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "description_nl",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "title_ca",
                    models.CharField(blank=True, max_length=1020, null=True),
                ),
                (
                    "title_de",
                    models.CharField(blank=True, max_length=1020, null=True),
                ),
                (
                    "title_detected_language",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "title_en",
                    models.CharField(blank=True, max_length=1020, null=True),
                ),
                (
                    "title_es",
                    models.CharField(blank=True, max_length=1020, null=True),
                ),
                (
                    "title_et",
                    models.CharField(blank=True, max_length=1020, null=True),
                ),
                (
                    "title_fr",
                    models.CharField(blank=True, max_length=1020, null=True),
                ),
                ("title_nl", models.CharField(blank=True, max_length=1020, null=True)),
            ],
            bases=(apps.commons.mixins.HasOwner, models.Model),
        ),
    ]
