# Generated by Django 5.2.10 on 2026-01-26 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0004_projectuserattachmentlink_projectuserattachmentfile_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="projectuserattachmentfile",
            options={"verbose_name": "User file", "verbose_name_plural": "User files"},
        ),
        migrations.AlterModelOptions(
            name="projectuserattachmentlink",
            options={"verbose_name": "User link", "verbose_name_plural": "User links"},
        ),
    ]
