# Generated by Django 5.2.10 on 2026-02-04 12:18

import apps.commons.mixins
import apps.files.models
import django.db.models.deletion
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_peoplegroup_location"),
        ("files", "0004_projectuserattachmentlink_projectuserattachmentfile_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={"ordering": ("-created_at",)},
        ),
        migrations.CreateModel(
            name="PeopleGroupImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "file",
                    stdimage.models.StdImageField(
                        force_min_size=False,
                        height_field="height",
                        upload_to=apps.files.models.dynamic_upload_to,
                        variations={
                            "full": (1920, 10000),
                            "large": (1024, 10000),
                            "medium": (768, 10000),
                            "small": (500, 10000),
                        },
                        width_field="width",
                    ),
                ),
                ("height", models.IntegerField(blank=True, null=True)),
                ("width", models.IntegerField(blank=True, null=True)),
                ("natural_ratio", models.FloatField(blank=True, null=True)),
                ("scale_x", models.FloatField(blank=True, null=True)),
                ("scale_y", models.FloatField(blank=True, null=True)),
                ("left", models.FloatField(blank=True, null=True)),
                ("top", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "people_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="accounts.peoplegroup",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "abstract": False,
            },
            bases=(
                models.Model,
                apps.commons.mixins.DuplicableModel,
                apps.commons.mixins.HasOwners,
            ),
        ),
    ]
