# Generated by Django 4.2.25 on 2025-11-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0004_projectuserattachmentlink_projectuserattachmentfile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalprojectuserattachmentfile",
            name="description_ca",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalprojectuserattachmentfile",
            name="description_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalprojectuserattachmentfile",
            name="description_detected_language",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="historicalprojectuserattachmentfile",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalprojectuserattachmentfile",
            name="description_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalprojectuserattachmentfile",
            name="description_et",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalprojectuserattachmentfile",
            name="description_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalprojectuserattachmentfile",
            name="description_nl",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalprojectuserattachmentfile",
            name="title_ca",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AddField(
            model_name="historicalprojectuserattachmentfile",
            name="title_de",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AddField(
            model_name="historicalprojectuserattachmentfile",
            name="title_detected_language",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="historicalprojectuserattachmentfile",
            name="title_en",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AddField(
            model_name="historicalprojectuserattachmentfile",
            name="title_es",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AddField(
            model_name="historicalprojectuserattachmentfile",
            name="title_et",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AddField(
            model_name="historicalprojectuserattachmentfile",
            name="title_fr",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AddField(
            model_name="historicalprojectuserattachmentfile",
            name="title_nl",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AddField(
            model_name="historicalprojectuserattachmentlink",
            name="description_ca",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalprojectuserattachmentlink",
            name="description_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalprojectuserattachmentlink",
            name="description_detected_language",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="historicalprojectuserattachmentlink",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalprojectuserattachmentlink",
            name="description_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalprojectuserattachmentlink",
            name="description_et",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalprojectuserattachmentlink",
            name="description_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalprojectuserattachmentlink",
            name="description_nl",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalprojectuserattachmentlink",
            name="title_ca",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AddField(
            model_name="historicalprojectuserattachmentlink",
            name="title_de",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AddField(
            model_name="historicalprojectuserattachmentlink",
            name="title_detected_language",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="historicalprojectuserattachmentlink",
            name="title_en",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AddField(
            model_name="historicalprojectuserattachmentlink",
            name="title_es",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AddField(
            model_name="historicalprojectuserattachmentlink",
            name="title_et",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AddField(
            model_name="historicalprojectuserattachmentlink",
            name="title_fr",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AddField(
            model_name="historicalprojectuserattachmentlink",
            name="title_nl",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AddField(
            model_name="projectuserattachmentfile",
            name="description_ca",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectuserattachmentfile",
            name="description_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectuserattachmentfile",
            name="description_detected_language",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="projectuserattachmentfile",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectuserattachmentfile",
            name="description_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectuserattachmentfile",
            name="description_et",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectuserattachmentfile",
            name="description_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectuserattachmentfile",
            name="description_nl",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectuserattachmentfile",
            name="title_ca",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AddField(
            model_name="projectuserattachmentfile",
            name="title_de",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AddField(
            model_name="projectuserattachmentfile",
            name="title_detected_language",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="projectuserattachmentfile",
            name="title_en",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AddField(
            model_name="projectuserattachmentfile",
            name="title_es",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AddField(
            model_name="projectuserattachmentfile",
            name="title_et",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AddField(
            model_name="projectuserattachmentfile",
            name="title_fr",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AddField(
            model_name="projectuserattachmentfile",
            name="title_nl",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AddField(
            model_name="projectuserattachmentlink",
            name="description_ca",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectuserattachmentlink",
            name="description_de",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectuserattachmentlink",
            name="description_detected_language",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="projectuserattachmentlink",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectuserattachmentlink",
            name="description_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectuserattachmentlink",
            name="description_et",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectuserattachmentlink",
            name="description_fr",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectuserattachmentlink",
            name="description_nl",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projectuserattachmentlink",
            name="title_ca",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AddField(
            model_name="projectuserattachmentlink",
            name="title_de",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AddField(
            model_name="projectuserattachmentlink",
            name="title_detected_language",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="projectuserattachmentlink",
            name="title_en",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AddField(
            model_name="projectuserattachmentlink",
            name="title_es",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AddField(
            model_name="projectuserattachmentlink",
            name="title_et",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AddField(
            model_name="projectuserattachmentlink",
            name="title_fr",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AddField(
            model_name="projectuserattachmentlink",
            name="title_nl",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
    ]
