# Generated by Django 4.2.22 on 2025-09-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0005_attachmentfile_description_detected_language_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachmentfile",
            name="description_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attachmentfile",
            name="title_es",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="attachmentlink",
            name="description_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attachmentlink",
            name="title_es",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalattachmentfile",
            name="description_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalattachmentfile",
            name="title_es",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalattachmentlink",
            name="description_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalattachmentlink",
            name="title_es",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="organizationattachmentfile",
            name="description_es",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="organizationattachmentfile",
            name="title_es",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
