# Generated by Django 3.2.13 on 2022-05-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_update_images_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachmentlink',
            name='attachment_type',
            field=models.CharField(choices=[('file', 'File'), ('image', 'Image'), ('video', 'Video'), ('link', 'Link')], default='link', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalattachmentlink',
            name='attachment_type',
            field=models.CharField(choices=[('file', 'File'), ('image', 'Image'), ('video', 'Video'), ('link', 'Link')], default='link', max_length=10),
        ),
    ]
