# Generated by Django 4.2.25 on 2025-11-20 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0005_historicalprojectuserattachmentfile_description_ca_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalprojectuserattachmentfile",
            old_name="user",
            new_name="owner",
        ),
        migrations.RenameField(
            model_name="historicalprojectuserattachmentlink",
            old_name="user",
            new_name="owner",
        ),
        migrations.RenameField(
            model_name="projectuserattachmentfile",
            old_name="user",
            new_name="owner",
        ),
        migrations.RenameField(
            model_name="projectuserattachmentlink",
            old_name="user",
            new_name="owner",
        ),
    ]
