# Generated by Django 4.2.22 on 2025-10-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0006_attachmentfile_description_es_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachmentfile",
            name="title_ca",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="attachmentfile",
            name="title_de",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="attachmentfile",
            name="title_en",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="attachmentfile",
            name="title_es",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="attachmentfile",
            name="title_et",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="attachmentfile",
            name="title_fr",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="attachmentfile",
            name="title_nl",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="attachmentlink",
            name="title_ca",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="attachmentlink",
            name="title_de",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="attachmentlink",
            name="title_en",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="attachmentlink",
            name="title_es",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="attachmentlink",
            name="title_et",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="attachmentlink",
            name="title_fr",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="attachmentlink",
            name="title_nl",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="historicalattachmentfile",
            name="title_ca",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="historicalattachmentfile",
            name="title_de",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="historicalattachmentfile",
            name="title_en",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="historicalattachmentfile",
            name="title_es",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="historicalattachmentfile",
            name="title_et",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="historicalattachmentfile",
            name="title_fr",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="historicalattachmentfile",
            name="title_nl",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="historicalattachmentlink",
            name="title_ca",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="historicalattachmentlink",
            name="title_de",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="historicalattachmentlink",
            name="title_en",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="historicalattachmentlink",
            name="title_es",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="historicalattachmentlink",
            name="title_et",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="historicalattachmentlink",
            name="title_fr",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="historicalattachmentlink",
            name="title_nl",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="organizationattachmentfile",
            name="title_ca",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="organizationattachmentfile",
            name="title_de",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="organizationattachmentfile",
            name="title_en",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="organizationattachmentfile",
            name="title_es",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="organizationattachmentfile",
            name="title_et",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="organizationattachmentfile",
            name="title_fr",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
        migrations.AlterField(
            model_name="organizationattachmentfile",
            name="title_nl",
            field=models.CharField(blank=True, max_length=1020, null=True),
        ),
    ]
