# Generated by Django 4.0.10 on 2023-03-16 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_image_left_image_natural_ratio_image_right_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='right',
            new_name='top',
        ),
    ]
