# Generated by Django 4.2.1 on 2023-06-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0008_rename_right_image_top"),
    ]

    operations = [
        migrations.CreateModel(
            name="PeopleResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("people_id", models.CharField(max_length=255)),
                ("people_data", models.JSONField(default=dict)),
            ],
        ),
    ]
