# Generated by Django 4.2.3 on 2023-08-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0009_peopleresource"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="left",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="natural_ratio",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="scale_x",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="scale_y",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="top",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
