# Generated by Django 4.2.3 on 2023-11-24 15:36

import apps.files.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0010_alter_image_left_alter_image_natural_ratio_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="file",
            field=stdimage.models.StdImageField(
                force_min_size=False,
                height_field="height",
                upload_to=apps.files.models.dynamic_upload_to,
                variations={
                    "full": (1920, 10000),
                    "large": (1024, 10000),
                    "medium": (768, 10000),
                    "small": (500, 10000),
                },
                width_field="width",
            ),
        ),
    ]
