# Generated by Django 4.2.7 on 2023-11-20 15:18

import apps.files.models
from django.db import migrations
import pictures.models
from pictures.migrations import AlterPictureField


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0010_alter_image_left_alter_image_natural_ratio_and_more"),
    ]

    operations = [
        AlterPictureField(
            model_name="image",
            name="file",
            field=pictures.models.PictureField(
                aspect_ratios=[None],
                breakpoints={"full": 1920, "large": 1024, "medium": 768, "small": 500},
                container_width=1200,
                file_types=["WEBP"],
                grid_columns=12,
                height_field="height",
                pixel_densities=[1, 2],
                upload_to=apps.files.models.dynamic_upload_to,
                width_field="width",
            ),
        ),
    ]
