# Generated by Django 4.2.7 on 2023-12-06 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def migrate_images(apps, schema_editor):
    Image = apps.get_model("files", "Image")
    for image in Image.objects.all():
        image._owner = image.owner
        image.save()


def migrate_images_reverse(apps, schema_editor):
    Image = apps.get_model("files", "Image")
    for image in Image.objects.all():
        image.owner = image._owner
        image.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("files", "0011_alter_image_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="_owner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_images",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(migrate_images, migrate_images_reverse),
        migrations.RemoveField(
            model_name="image",
            name="owner",
        ),
        migrations.RenameField(
            model_name="image",
            old_name="_owner",
            new_name="owner",
        ),
        migrations.AlterField(
            model_name="image",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to=settings.AUTH_USER_MODEL,
                null=True,
            ),
        ),
    ]
