# Generated by Django 3.2.13 on 2022-05-15 20:31

import apps.commons.db.abc
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedbacks', '0003_alter_follow_follower'),
        ('projects', '0012_alter_projectmember_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_added_to_project', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL, to_field='keycloak_id')),
            ],
            bases=(models.Model, apps.commons.db.abc.HasOwner),
        ),
        migrations.CreateModel(
            name='MemberNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_changes', models.BooleanField(default=True)),
                ('notify_reviews', models.BooleanField(default=True)),
                ('notify_members', models.BooleanField(default=True)),
                ('notify_applications', models.BooleanField(default=False)),
                ('notify_blogentries', models.BooleanField(default=True)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='projects.projectmember')),
            ],
            bases=(models.Model, apps.commons.db.abc.HasOwner),
        ),
        migrations.CreateModel(
            name='FollowNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_changes', models.BooleanField(default=True)),
                ('notify_reviews', models.BooleanField(default=True)),
                ('notify_blogentries', models.BooleanField(default=True)),
                ('follow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='feedbacks.follow')),
            ],
            bases=(models.Model, apps.commons.db.abc.HasOwner),
        ),
    ]
