# Generated by Django 4.2.7 on 2024-01-05 17:16

import apps.commons.mixins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("invitations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notify_added_to_project", models.BooleanField(default=True)),
                ("announcement_published", models.BooleanField(default=True)),
                ("announcement_has_new_application", models.BooleanField(default=True)),
                ("followed_project_has_been_edited", models.BooleanField(default=True)),
                ("project_has_been_commented", models.BooleanField(default=True)),
                ("project_has_been_edited", models.BooleanField(default=True)),
                ("project_ready_for_review", models.BooleanField(default=True)),
                ("project_has_been_reviewed", models.BooleanField(default=True)),
                ("comment_received_a_response", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=(models.Model, apps.commons.mixins.HasOwner),
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_viewed", models.BooleanField(default=False)),
                ("to_send", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now=True)),
                (
                    "reminder_message",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "reminder_message_en",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "reminder_message_fr",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("comment", "Comment"),
                            ("reply", "Reply"),
                            ("review", "Review"),
                            ("ready_for_review", "Ready For Review"),
                            ("project_updated", "Project Updated"),
                            ("member_added_self", "Member Added Self"),
                            ("group_member_added_self", "Group Member Added Self"),
                            ("member_updated_self", "Member Updated Self"),
                            ("member_added", "Member Added"),
                            ("member_updated", "Member Updated"),
                            ("member_removed", "Member Removed"),
                            ("group_member_removed", "Group Member Removed"),
                            ("group_member_added", "Group Member Added"),
                            ("announcement", "Announcement"),
                            ("application", "Application"),
                            ("blog_entry", "Blog Entry"),
                            ("invitation_today_reminder", "Invitation Today Reminder"),
                            ("invitation_week_reminder", "Invitation Week Reminder"),
                        ],
                        default="project_updated",
                        max_length=30,
                    ),
                ),
                ("context", models.JSONField(default=dict)),
                ("count", models.IntegerField(default=1)),
                (
                    "invitation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="invitations.invitation",
                    ),
                ),
            ],
            bases=(models.Model, apps.commons.mixins.HasOwner),
        ),
    ]
