# Generated by Django 4.0.6 on 2022-07-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membernotificationsettings',
            name='notify_applications',
            field=models.BooleanField(default=True),
        ),
    ]
