# Generated by Django 4.0.7 on 2022-09-14 12:43

from django.db import migrations, models


def deactivate_notifications(apps, schema_editor):
    NotificationSettings = apps.get_model("notifications", "NotificationSettings")  # noqa
    MemberNotificationSettings = apps.get_model("notifications", "MemberNotificationSettings")  # noqa
    FollowNotificationSettings = apps.get_model("notifications", "FollowNotificationSettings")  # noqa

    NotificationSettings.objects.all().update(
        notify_added_to_project=False
    )
    MemberNotificationSettings.objects.all().update(
        notify_changes=False,
        notify_reviews=False,
        notify_members=False,
        notify_applications=False,
        notify_blogentries=False,
    )
    FollowNotificationSettings.objects.all().update(
        notify_changes=False,
        notify_reviews=False,
        notify_blogentries=False
    )


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_membernotificationsettings_notify_applications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follownotificationsettings',
            name='notify_blogentries',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='follownotificationsettings',
            name='notify_changes',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='follownotificationsettings',
            name='notify_reviews',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='membernotificationsettings',
            name='notify_applications',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='membernotificationsettings',
            name='notify_blogentries',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='membernotificationsettings',
            name='notify_changes',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='membernotificationsettings',
            name='notify_members',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='membernotificationsettings',
            name='notify_reviews',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='notify_added_to_project',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(deactivate_notifications, migrations.RunPython.noop)
    ]
