# Generated by Django 4.2.11 on 2024-03-28 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_organization_identity_providers"),
        ("notifications", "0003_notification_access_request_alter_notification_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="invitation",
        ),
        migrations.AddField(
            model_name="notification",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="notificationsettings",
            name="invitation_link_will_expire",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="notificationsettings",
            name="organization_has_new_access_request",
            field=models.BooleanField(default=True),
        ),
    ]
