# Generated by Django 4.2.10 on 2024-03-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_notification_access_request_alter_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationsettings",
            name="organization_has_new_access_request",
            field=models.BooleanField(default=True),
        ),
    ]
