# Generated by Django 4.2.11 on 2024-04-03 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("newsfeed", "0003_instruction_notified"),
        ("notifications", "0003_notification_access_request_alter_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="instruction",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="newsfeed.instruction",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("comment", "Comment"),
                    ("reply", "Reply"),
                    ("review", "Review"),
                    ("ready_for_review", "Ready For Review"),
                    ("project_updated", "Project Updated"),
                    ("member_added_self", "Member Added Self"),
                    ("group_member_added_self", "Group Member Added Self"),
                    ("member_updated_self", "Member Updated Self"),
                    ("member_added", "Member Added"),
                    ("member_updated", "Member Updated"),
                    ("member_removed", "Member Removed"),
                    ("group_member_removed", "Group Member Removed"),
                    ("group_member_added", "Group Member Added"),
                    ("announcement", "Announcement"),
                    ("application", "Application"),
                    ("blog_entry", "Blog Entry"),
                    ("invitation_today_reminder", "Invitation Today Reminder"),
                    ("invitation_week_reminder", "Invitation Week Reminder"),
                    ("access_request", "Access Request"),
                    ("instruction", "Instruction"),
                ],
                default="project_updated",
                max_length=30,
            ),
        ),
    ]
