# Generated by Django 4.2.27 on 2025-12-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationsettings",
            name="category_project_created",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="notificationsettings",
            name="category_project_updated",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("comment", "Comment"),
                    ("reply", "Reply"),
                    ("review", "Review"),
                    ("project_message", "Project Message"),
                    ("ready_for_review", "Ready For Review"),
                    ("project_created", "Project Created"),
                    ("project_updated", "Project Updated"),
                    ("member_added_self", "Member Added Self"),
                    ("group_member_added_self", "Group Member Added Self"),
                    ("member_updated_self", "Member Updated Self"),
                    ("member_added", "Member Added"),
                    ("member_updated", "Member Updated"),
                    ("member_removed", "Member Removed"),
                    ("group_member_removed", "Group Member Removed"),
                    ("group_member_added", "Group Member Added"),
                    ("announcement", "Announcement"),
                    ("application", "Application"),
                    ("blog_entry", "Blog Entry"),
                    ("invitation_today_reminder", "Invitation Today Reminder"),
                    ("invitation_week_reminder", "Invitation Week Reminder"),
                    ("access_request", "Access Request"),
                    ("pending_access_requests", "Pending Access Requests"),
                    ("new_instruction", "New Instruction"),
                ],
                default="project_updated",
                max_length=30,
            ),
        ),
    ]
