# Generated by Django 4.0.7 on 2022-09-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_follownotificationsettings_notify_blogentries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='announcement_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='followed_project_has_been_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='project_has_been_commented',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='project_has_been_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='project_has_been_reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notificationsettings',
            name='project_ready_for_review',
            field=models.BooleanField(default=False),
        ),
    ]
