# Generated by Django 4.2.10 on 2024-03-20 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_organization_identity_providers"),
        (
            "notifications",
            "0004_notificationsettings_organization_has_new_access_request",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="organization",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.organization",
            ),
        ),
    ]
