# Generated by Django 4.2.11 on 2024-04-11 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_notification_instruction_alter_notification_type"),
        ("notifications", "0004_remove_notification_invitation_and_more"),
    ]

    operations = []
