# Generated by Django 4.2.20 on 2025-04-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "notifications",
            "0006_notificationsettings_project_has_new_private_message_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="reminder_message_de",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
