# Generated by Django 4.2.20 on 2025-06-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0007_notification_reminder_message_de"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="reminder_message_ca",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="reminder_message_et",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="reminder_message_nl",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
