# Generated by Django 4.0.7 on 2022-09-27 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_auto_20220523_1643'),
        ('notifications', '0007_alter_notification_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')
        ),
    ]
