# Generated by Django 4.2.22 on 2025-09-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0008_notification_reminder_message_ca_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="reminder_message_es",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
    ]
