# Generated by Django 4.0.7 on 2022-10-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_alter_notification_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='announcement_has_new_application',
            field=models.BooleanField(default=True),
        ),
    ]
