# Generated by Django 4.0.7 on 2022-11-23 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_notification_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membernotificationsettings',
            name='member',
        ),
        migrations.DeleteModel(
            name='FollowNotificationSettings',
        ),
        migrations.DeleteModel(
            name='MemberNotificationSettings',
        ),
    ]
