# Generated by Django 4.0.7 on 2022-11-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0012_remove_membernotificationsettings_member_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='to_send',
            field=models.BooleanField(default=False),
        ),
    ]
