# Generated by Django 4.0.7 on 2022-11-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0013_notification_to_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationsettings',
            name='comment_received_a_response',
            field=models.BooleanField(default=False),
        ),
    ]
