# Generated by Django 4.0.7 on 2022-12-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0014_notificationsettings_comment_received_a_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='reminder_message',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
