# Generated by Django 4.0.7 on 2022-12-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0016_notification_message_en_notification_message_fr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='message',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='message_en',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='message_fr',
        ),
        migrations.AddField(
            model_name='notification',
            name='context',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('comment', 'Comment'), ('reply', 'Reply'), ('review', 'Review'), ('ready_for_review', 'Ready For Review'), ('project_updated', 'Project Updated'), ('member_added_self', 'Member Added Self'), ('member_updated_self', 'Member Updated Self'), ('member_added', 'Member Added'), ('member_updated', 'Member Updated'), ('member_removed', 'Member Removed'), ('announcement', 'Announcement'), ('application', 'Application'), ('blog_entry', 'Blog Entry')], default='project_updated', max_length=20),
        ),
    ]
