# Generated by Django 4.0.7 on 2022-12-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0017_remove_notification_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationsettings',
            name='announcement_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='comment_received_a_response',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='followed_project_has_been_edited',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='notify_added_to_project',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='project_has_been_commented',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='project_has_been_edited',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='project_has_been_reviewed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notificationsettings',
            name='project_ready_for_review',
            field=models.BooleanField(default=True),
        ),
    ]
