# Generated by Django 4.0.10 on 2023-03-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0018_alter_notificationsettings_announcement_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
