# Generated by Django 4.2.1 on 2023-06-20 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("invitations", "0005_alter_invitation_owner"),
        ("projects", "0020_remove_historicallinkedproject_reason_and_more"),
        ("notifications", "0020_alter_notification_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="invitation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="invitations.invitation",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.project",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("comment", "Comment"),
                    ("reply", "Reply"),
                    ("review", "Review"),
                    ("ready_for_review", "Ready For Review"),
                    ("project_updated", "Project Updated"),
                    ("member_added_self", "Member Added Self"),
                    ("member_updated_self", "Member Updated Self"),
                    ("member_added", "Member Added"),
                    ("member_updated", "Member Updated"),
                    ("member_removed", "Member Removed"),
                    ("announcement", "Announcement"),
                    ("application", "Application"),
                    ("blog_entry", "Blog Entry"),
                    ("invitation_reminder", "Invitation Reminder"),
                ],
                default="project_updated",
                max_length=20,
            ),
        ),
    ]
