# Generated by Django 4.2.1 on 2023-06-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "notifications",
            "0021_notification_invitation_alter_notification_project_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="expire",
            field=models.CharField(
                choices=[("", "Default"), ("week", "Week"), ("today", "Today")],
                default="",
                max_length=20,
            ),
        ),
    ]
