# Generated by Django 4.2.1 on 2023-07-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "notifications",
            "0021_notification_invitation_alter_notification_project_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("comment", "Comment"),
                    ("reply", "Reply"),
                    ("review", "Review"),
                    ("ready_for_review", "Ready For Review"),
                    ("project_updated", "Project Updated"),
                    ("member_added_self", "Member Added Self"),
                    ("member_updated_self", "Member Updated Self"),
                    ("member_added", "Member Added"),
                    ("member_updated", "Member Updated"),
                    ("member_removed", "Member Removed"),
                    ("announcement", "Announcement"),
                    ("application", "Application"),
                    ("blog_entry", "Blog Entry"),
                    ("invitation_today_reminder", "Invitation Today Reminder"),
                    ("invitation_week_reminder", "Invitation Week Reminder"),
                ],
                default="project_updated",
                max_length=30,
            ),
        ),
    ]
