# Generated by Django 4.2.1 on 2023-07-03 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0022_alter_notification_type"),
        ("notifications", "0022_notification_expire"),
    ]

    operations = []
