# Generated by Django 4.2.1 on 2023-07-03 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0023_merge_20230703_0948"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="expire",
        ),
    ]
