# Generated by Django 4.2.7 on 2023-12-06 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def migrate_notification_settings(apps, schema_editor):
    NotificationSettings = apps.get_model("notifications", "NotificationSettings")
    for notification_settings in NotificationSettings.objects.all():
        notification_settings._user = notification_settings.user
        notification_settings.save()

def migrate_notification_settings_reverse(apps, schema_editor):
    NotificationSettings = apps.get_model("notifications", "NotificationSettings")
    for notification_settings in NotificationSettings.objects.all():
        notification_settings.user = notification_settings._user
        notification_settings.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notifications", "0026_alter_notification_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationsettings",
            name="_user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="_notification_settings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(migrate_notification_settings, migrate_notification_settings_reverse),
        migrations.RemoveField(
            model_name="notificationsettings",
            name="user",
        ),
        migrations.RenameField(
            model_name="notificationsettings",
            old_name="_user",
            new_name="user",
        ),
        migrations.AlterField(
            model_name="notificationsettings",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_settings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
