apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ tpl $.Values.fullName $ }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ tpl $.Values.fullName $ }}
  minReplicas: 1
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
