apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- (tpl ($.Values.backend.commonLabels | toYaml ) $) | nindent 4 }}
  name: {{ tpl $.Values.fullName $ }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- (tpl ($.Values.backend.commonLabels | toYaml ) $) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- (tpl ($.Values.backend.commonLabels | toYaml ) $) | nindent 8 }}
        {{ printf "%s-client" $.Values.redis.helmReleaseName }}: "true"
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app.kubernetes.io/name
                  operator: In
                  values:
                  - {{ index $.Values.backend.commonLabels "app.kubernetes.io/name" }}
              topologyKey: "kubernetes.io/hostname"
      securityContext:
        runAsNonRoot: true
        runAsUser: 10000
        runAsGroup: 10000
        fsGroup: 10000
        seccompProfile:
          type: RuntimeDefault
      initContainers:
      {{- with $.Values.image }}
      - image: {{ tpl (printf "%s/%s:%s" .repository .path .tag) $ }}
      {{- end }}
        imagePullPolicy: IfNotPresent
        name: projects-backend-prestart
        args:
          - make
        {{- if .Values.runMigrations }}
          - prestart
        {{- else }}
          - prestart-no-migrate
        {{- end }}
        envFrom:
          - configMapRef:
              name: {{ tpl $.Values.fullName $ }}
        volumeMounts:
        - name: static-files
          mountPath: /app/static
        {{- if .Values.config.sensitive }}
        - name: secrets
          mountPath: "/secrets"
          readOnly: true
        {{- end }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: [ALL]
      containers:
      {{- with $.Values.image }}
      - image: {{ tpl (printf "%s/%s:%s" .repository .path .tag) $ }}
      {{- end }}
        imagePullPolicy: IfNotPresent
        name: projects-backend
        args:
          - make
          - start
        ports:
          - name: http
            containerPort: {{ .Values.backend.port }}
        livenessProbe:
          httpGet:
            port: http
            path: /v1/healthz/live
          timeoutSeconds: 20
        readinessProbe:
          httpGet:
            port: http
            path: /v1/healthz/ready
          timeoutSeconds: 20
        envFrom:
        - configMapRef:
            name: {{ tpl $.Values.fullName $ }}
        resources:
          {{- .Values.backend.resources | toYaml | nindent 10 }}
        volumeMounts:
        - name: static-files
          mountPath: /app/static
        {{- if .Values.config.sensitive }}
        - name: secrets
          mountPath: "/secrets"
          readOnly: true
        {{- end }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop: [ALL]
      volumes:
      - name: static-files
        emptyDir: {}
      {{- if .Values.config.sensitive }}
      - name: secrets
        secret:
          secretName: {{ tpl $.Values.fullName $ }}
      {{- end }}
