{{- if and .Values.celery.enabled $.Values.celery.metrics.enabled $.Values.celery.metrics.service.enabled }}
{{- with .Values.celery.metrics.serviceMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ tpl $.Values.fullName $ }}-celery-metrics
  labels:
  {{- (tpl ($.Values.celery.commonLabels | toYaml ) $) | nindent 4 }}
spec:
  endpoints:
    - port: http
  selector:
    matchLabels:
    {{- (tpl ($.Values.celery.commonLabels | toYaml ) $) | nindent 6 }}
{{- end }}
{{- end }}
