{{- with .Values.config.sensitive }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ tpl $.Values.fullName $ }}
  labels:
    {{- (tpl ($.Values.backend.commonLabels | toYaml ) $) | nindent 4 }}
stringData:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
{{- end }}
