{{- with .Values.config.sensitive }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ tpl $.Values.fullName $ }}
  labels:
    {{- (tpl ($.Values.backend.commonLabels | toYaml ) $) | nindent 4 }}
stringData:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-workflow" (tpl $.Values.fullName $) }}
  labels:
    {{- (tpl ($.Values.backend.commonLabels | toYaml ) $) | nindent 4 }}
stringData:
{{ $workflowConfigSecret := dict }}
{{ $workflowConfigSecret = merge $workflowConfigSecret .Values.config.sensitive}}
{{ $workflowConfigSecret = merge $workflowConfigSecret .Values.workflowConfig.sensitive}}
{{- range $key, $value := $workflowConfigSecret }}
  {{ $key }}: {{ (tpl $value $) | quote }}
{{- end }}

