{{- with .Values.config.nonSensitive }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ tpl $.Values.fullName $ }}
  labels:
    {{- (tpl ($.Values.backend.commonLabels | toYaml ) $) | nindent 4 }}
data:
{{- range $key, $value := . }}
  {{ $key }}: {{ (tpl $value $) | quote }}
{{- end }}
{{- end }}
