apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ tpl .Values.fullName . }}
  labels:
    {{- (tpl ($.Values.backend.commonLabels | toYaml ) $) | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-traefik
    kubernetes.io/ingress.class: traefik
    {{- $middlewares := .Values.ingressMiddlewares }}

    {{- if .Values.sablier.enabled }}
    {{- $middlewares = append $middlewares (tpl .Values.sablier.traefikMiddleware .) }}
    {{- end }}

    {{- if $middlewares }}
    traefik.ingress.kubernetes.io/router.middlewares: {{ join "," $middlewares }}
    {{- end }}
spec:
  rules:
    - host: {{ .Values.hostname }}
      http:
        paths:
          - path: {{ .Values.ingressPath }}
            pathType: Prefix
            backend:
              service:
                name: {{ tpl .Values.fullName . }}
                port:
                  name: http
  tls:
    - hosts:
        - {{ .Values.hostname }}
      secretName: {{ printf "%s-tls" .Values.hostname }}
