{{ include "common.security.networkPolicy" (dict
  "name" (tpl .Values.fullName .)
  "podSelector" (dict "matchLabels" (tpl (.Values.backend.commonLabels | toJson) .| fromJson) )
  "allowFromReverseProxy" true
  "reverseProxyNamespace" (ternary "traefik" "ingress-nginx" .Values.traefik  )
  "additionalIngresses":
  "commonLabels" (tpl (.Values.backend.commonLabels | toJson) . | fromJson)
) }}

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ tpl $.Values.fullName $ }}-celery
  labels:
  {{- (tpl ($.Values.celery.commonLabels | toYaml ) $) | nindent 4 }}
spec:
  podSelector:
    matchLabels:
    {{- (tpl ($.Values.celery.commonLabels | toYaml ) $) | nindent 6 }}
  policyTypes:
    - Ingress
  ingress:
    - from:
      # Metrics
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: monitoring
      ports:
        - protocol: TCP
          port: http
