apiVersion: v1
kind: Service
metadata:
  name: {{ tpl $.Values.fullName $ }}
  labels:
  {{- (tpl ($.Values.backend.commonLabels | toYaml ) $) | nindent 4 }}
spec:
  selector:
  {{- (tpl ($.Values.backend.commonLabels | toYaml ) $) | nindent 4 }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
      name: http
