{{- if .Values.workflow.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s.service-account-token" .Values.workflow.rbac.serviceAccountName }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.workflow.rbac.serviceAccountName }}
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.workflow.rbac.serviceAccountName }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.workflow.rbac.serviceAccountName }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.workflow.rbac.serviceAccountName }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.workflow.rbac.executorClusterRoleName}}
  apiGroup: rbac.authorization.k8s.io
---
{{- if .Values.workflow.lifecycle.enabled}}
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: {{ tpl .Values.workflow.lifecycle.resourceName $ }}
spec:
  entrypoint: create-db
  serviceAccountName: {{ .Values.workflow.rbac.serviceAccountName }}
  securityContext:
    runAsNonRoot: true
    runAsUser: 10000
    runAsGroup: 10000
    fsGroup: 10000
    seccompProfile:
      type: RuntimeDefault
  templates:
    - name: drop-db
      inputs:
        parameters:
          - name: dry_run
            value: "true"
            enum:
            - 'true'
            - 'false'
          - name: force_disconnect
            value: "false"
            enum:
            - 'true'
            - 'false'
      container:
      {{- with $.Values.image }}
        image: {{ tpl (printf "%s/%s:%s" .repository .path .tag) $ }}
      {{- end }}
        args: ["make", "dropdb"]
        env:
        - name: DRY_RUN
          value: {{ print "{{workflow.parameters.dry_run}}" | quote }}
        - name: FORCE_DISCONNECT
          value: {{ print "{{workflow.parameters.force_disconnect}}" | quote }}
        envFrom:
        - configMapRef:
            name: {{ printf "%s-workflow" (tpl $.Values.fullName $) }}
        volumeMounts:
        - name: secrets
          mountPath: "/secrets"
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: {{ printf "%s-workflow" (tpl $.Values.fullName $) }}
    - name: create-db
      inputs:
        parameters:
          - name: dry_run
            value: "true"
            enum:
            - 'true'
            - 'false'
      container:
      {{- with $.Values.image }}
        image: {{ tpl (printf "%s/%s:%s" .repository .path .tag) $ }}
      {{- end }}
        args: ["make", "createdb"]
        env:
        - name: DRY_RUN
          value: {{ print "{{workflow.parameters.dry_run}}" | quote}}
        envFrom:
        - configMapRef:
            name: {{ printf "%s-workflow" (tpl $.Values.fullName $) }}
        volumeMounts:
        - name: secrets
          mountPath: "/secrets"
          readOnly: true

      volumes:
      {{- if .Values.config.sensitive }}
      - name: secrets
        secret:
          secretName: {{ printf "%s-workflow" (tpl $.Values.fullName $) }}
      {{- end }}
{{- end }}
{{- if .Values.workflow.backups.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: {{ tpl .Values.workflow.backups.resourceName $ }}
spec:
  hooks:
    failed:
      expression: workflow.status != "Succeeded"
      templateRef:
        name: notify-slack
        template: send-request
        clusterScope: true
      arguments:
        parameters:
        - name: message
          value: Backup check failed !
        - name: slackChannel
          value: {{ .Values.workflow.backups.slackChannel | quote }}
  entrypoint: check-presence
  serviceAccountName: {{ .Values.workflow.rbac.serviceAccountName }}
  securityContext:
    runAsNonRoot: true
    runAsUser: 10000
    runAsGroup: 10000
    fsGroup: 10000
    seccompProfile:
      type: RuntimeDefault
  templates:
  - name: check-presence
    steps:
    - - name: check-presence
        templateRef:
          name: postgres-backuper
          template: check-presence
          clusterScope: true
        arguments:
          parameters:
          - name: storage_container_name
            value: {{ .Values.workflow.backups.storageContainerName }}
{{- end }}
{{- end }}
