{{- if .Values.workflow.lifecycle.enabled}}
{{ $resourceName := (tpl $.Values.workflow.resourceName .) }}
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ $resourceName }}
  labels:
    {{- (tpl ($.Values.backend.commonLabels | toYaml ) $) | nindent 4 }}
data:
{{- $workflowConfig := dict }}
{{- $workflowConfig = merge $workflowConfig .Values.config.nonSensitive}}
{{- $workflowConfig = merge $workflowConfig .Values.workflow.lifecycle.config.nonSensitive }}
{{- range $key, $value := $workflowConfig }}
  {{ $key }}: {{ (tpl $value $) | quote }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $resourceName }}
  labels:
    {{- (tpl ($.Values.backend.commonLabels | toYaml ) $) | nindent 4 }}
stringData:
{{- $workflowConfigSecret := dict }}
{{- $workflowConfigSecret = merge $workflowConfigSecret .Values.config.sensitive}}
{{- $workflowConfigSecret = merge $workflowConfigSecret .Values.workflow.lifecycle.config.sensitive}}
{{- range $key, $value := $workflowConfigSecret }}
  {{ $key }}: {{ (tpl $value $) | quote }}
{{- end }}
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: {{ tpl .Values.workflow.lifecycle.resourceName $ }}
spec:
  entrypoint: create-db
  serviceAccountName: {{ .Values.workflow.rbac.serviceAccountName }}
  securityContext:
    {{- include "common.security.podSecurityContext.restricted" dict | nindent 4 }}
  templates:
  - name: drop-db
    inputs:
      parameters:
        - name: dry_run
          value: "true"
          enum:
          - 'true'
          - 'false'
        - name: force_disconnect
          value: "false"
          enum:
          - 'true'
          - 'false'
    steps:
    - - name: drop-db
        templateRef:
          clusterScope: true
          name: {{ .Values.workflow.databaseWorkflowTemplate.name }}
          template: {{ .Values.workflow.databaseWorkflowTemplate.dropDb.templateName }}
        arguments:
          parameters:
          - name: dry_run
            value: {{ print "{{inputs.parameters.dry_run}}" | quote }}
          - name: force_disconnect
            value: {{ print "{{inputs.parameters.force_disconnect}}" | quote }}
          - name: environmentSecretName
            value: {{ $resourceName }}
          - name: environmentConfigmapName
            value: {{ $resourceName }}
  - name: create-db
    steps:
    - - name: create-db
        templateRef:
          clusterScope: true
          name: {{ .Values.workflow.databaseWorkflowTemplate.name }}
          template: {{ .Values.workflow.databaseWorkflowTemplate.createDb.templateName }}
        arguments:
          parameters:
          - name: environmentSecretName
            value: {{ $resourceName }}
          - name: environmentConfigmapName
            value: {{ $resourceName }}
{{- end }}
