apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s.service-account-token" .Values.workflowRbac.serviceAccountName }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.workflowRbac.serviceAccountName }}
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.workflowRbac.serviceAccountName }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.workflowRbac.serviceAccountName }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.workflowRbac.serviceAccountName }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.workflowRbac.executorClusterRoleName}}
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: {{ tpl $.Values.fullName $ }}
spec:
  entrypoint: sort
  serviceAccountName: {{ .Values.workflowRbac.serviceAccountName }}
  securityContext:
    runAsNonRoot: true
    runAsUser: 10000
    runAsGroup: 10000
    fsGroup: 10000
    seccompProfile:
      type: RuntimeDefault
  templates:
    - name: drop-db
      inputs:
        parameters:
          - name: dry_run
            value: "true"
            enum:
            - 'true'
            - 'false'
      container:
      {{- with $.Values.image }}
        image: {{ tpl (printf "%s/%s:%s" .repository .path .tag) $ }}
      {{- end }}
        args: ["make", "dropdb"]
        env:
        - name: DRY_RUN
          value: {{ print "{{workflow.parameters.dry_run}}" | quote}}
        envFrom:
        - configMapRef:
            name: {{ printf "%s-workflow" (tpl $.Values.fullName $) }}
        volumeMounts:
        - name: secrets
          mountPath: "/secrets"
          readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: {{ printf "%s-workflow" (tpl $.Values.fullName $) }}
    - name: create-db
      inputs:
        parameters:
          - name: dry_run
            value: "true"
            enum:
            - 'true'
            - 'false'
      container:
      {{- with $.Values.image }}
        image: {{ tpl (printf "%s/%s:%s" .repository .path .tag) $ }}
      {{- end }}
        args: ["make", "createdb"]
        env:
        - name: DRY_RUN
          value: {{ print "{{workflow.parameters.dry_run}}" | quote}}
        envFrom:
        - configMapRef:
            name: {{ printf "%s-workflow" (tpl $.Values.fullName $) }}
        volumeMounts:
        - name: secrets
          mountPath: "/secrets"
          readOnly: true

      volumes:
      {{- if .Values.config.sensitive }}
      - name: secrets
        secret:
          secretName: {{ printf "%s-workflow" (tpl $.Values.fullName $) }}
      {{- end }}
